### ISSUE TITLE
ORDER_ALREADY_COMPLETED error after updating to v2.0.0

### ISSUE THREAD

**Issue by AndrijaSobak** [woocommerce/woocommerce-paypal-payments#1023]
Until now I didn't have any problems with PayPal other than [#952](https://github.com/woocommerce/woocommerce-paypal-payments/issues/952#issue-1429739827) which I fixed with help from another person experiencing the same problem.

This time around I have three failed orders with next error:
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED PayPalGateway.php:525 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-ORDER_ALREADY_COMPLETED OrderEndpoint.php:551

All orders that got this error came twice into WC orders.
First order is accepted and goes through and in 10 minutes same order is created with above error.

Can you please fix this?

**Comment by Sirvijver** [comment]
Hello @AndrijaSobak 

thank you for reaching out to us, however, I would advise you to contact us via another support interface, since we only use GitHub for development activities. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing is expected to be caused by a conflict, and I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

As said, if you need additional support, reach out to our support team as explained above.

Kind regards, 
Joost
