### ISSUE TITLE
al seleccionar en mi tienda pagar con paypal me sale error y no me abre la ventana  de paypal para generar el pago 

### ISSUE THREAD

**Issue by masterimportstore** [woocommerce/woocommerce-paypal-payments#1026]
ese mensaje me sale  que ago Algo ha salido mal. Por favor, inténtalo de nuevo o elige otra fuente de pago.

**Comment by Sirvijver** [comment]
Hello @masterimportstore,

Thank you for reaching out to us, we are here to help. The GitHub platform is only used by us for development activities and I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. When you do, please add the system report, logs and any errors/screenshot available to you, in order to help you out as efficient as possible.

I will close this ticket.

Kind regards, 
Joost
