### ISSUE TITLE
Paypal payment method loading spinner is showing non-stop

### ISSUE THREAD

**Issue by Bilalshaikh1996** [woocommerce/woocommerce-paypal-payments#1028]
### Describe the Bug

Hello, Kindly check this Bug i have attached a screenshot, when i select PayPal as a payment method it start showing loading spinner and never stops loading..!  Kindly anyone identify this issue,
![image](https://user-images.githubusercontent.com/30807790/204258239-7e84c2f2-e7f9-48c2-bff1-457e3cd93053.png)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![image](https://user-images.githubusercontent.com/30807790/204258539-12d34770-46a5-4446-9b27-b662f9b024d6.png)

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.1.0
 - Plugin Version 2.0.0
 - Browser [e.g. Chrome, Safari] and Version: latest version chrome
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello,

Thank you for reaching out to us. We don't handle support request via GitHub and want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing sounds like the theme or a plugin is blocking our plugin from replacing the WooCommerce button with the PayPal button. To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

If this did not help you resolve the issue, please open the support thread as explained above for getting additional support from our support team.

Kind regards, 
Joost
