### ISSUE TITLE
woocommerce-paypal-payments-button

### ISSUE THREAD

**Issue by T-raspberrypi** [woocommerce/woocommerce-paypal-payments#1044]

**Comment by Sirvijver** [comment]
Hello @T-raspberrypi

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If you need additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We will close this issue, because it is an support request and we only manage developers issues on GitHub.

Kind regards,
Joost
