### ISSUE TITLE
PROBLEM WITH PAYPAL IN CHECKOUTS

### ISSUE THREAD

**Issue by PowerExplosive** [woocommerce/woocommerce-paypal-payments#1052]
### Describe the Bug

-----------------------

Hi,

When a user is logged, in wordpress, it does not let them pay with PayPal until 5 minutes have passed since they logged.

Thanks.

![Screenshot_2](https://user-images.githubusercontent.com/71507913/204868420-fb660d70-a903-401b-b5dd-2af97882e893.png)

-----------------------

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by femiyb** [comment]
Hello @PowerExplosive 

You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If you need additional support, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We will close this issue because it is a support request and we only manage development issues on GitHub.

Regards,
Femi.
