### ISSUE TITLE
Failed to create order tracking information

### ISSUE THREAD

**Issue by frozen-media-ts** [woocommerce/woocommerce-paypal-payments#1071]
### Describe the Bug

Every time a PayPal order comes in, we have on the right side Errors (Edit order, please see attachment Error1)
We use:
WooCommerce PayPal Payments 2.0 together with all the latest Plugins, Wordpress etc. All Up to Date.
Additional we use Germanize 

### To Reproduce

1. Go to Orders
2. Click on Order
3. Go to the right side

### Screenshots

I attached 2 Screenshort and a error log

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.1.1
 - WooCommerce PayPal Payments 2.0
 - Any Browser
 - shipcloud für WooCommerce 2.0.5
 - Flexible Shipping 4.17.0
 - Germanized für WooCommerce Pro 3.6.2

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
![error1](https://user-images.githubusercontent.com/47541222/206568513-c64ca68b-5392-4897-a4d9-5b45793e3849.jpg)
![error2](https://user-images.githubusercontent.com/47541222/206568531-b206e209-0c20-4289-822d-78ac450c9b7d.jpg)
[error-log.txt](https://github.com/woocommerce/woocommerce-paypal-payments/files/10189479/error-log.txt)

**Comment by femiyb** [comment]
Hello @frozen-media-ts 

The error message from the issue you have reported does not look like one from the WooCommerce PayPal Payments.
You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If the issue persists, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We will close this issue, because it is a support request and we only manage developers issues on GitHub.

Regards,
Femi.

**Comment by frozen-media-ts** [comment]
Hi Femi,

The Report on Github comes direct from your Plugin Link “Submit a bug”.

The Error is in the error log of WooCommerce PayPal Payments and its gone as soon in turn off  “Pay upon Invoice” and deactivate “Shipment tracking” on the Connection Tab of the plugin!

Best regards
Tom
