### ISSUE TITLE
Order Update Issue With Woocommerce

### ISSUE THREAD

**Issue by ShawnW86** [woocommerce/woocommerce-paypal-payments#1072]
### Describe the Bug

There is a random bug occurs on our Paypal plugin , the issue is after customer paied the money from Paypal pop-up window then the woocommerce could not receive the order. This is meaning the customer has already paid the money but we could not see the order from woocommerce. There was not any information from woocommerce about this order and this error was happened randomly.

### To Reproduce

1. Go to Checkout
2. Click on Paypal payment the finished the payment
3. The transaction was happened then not order information for woocommerce order

### Screenshots

<img width="555" alt="image" src="https://user-images.githubusercontent.com/116044507/206595226-f251c770-736c-4346-9834-b06fd0998210.png">
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/116044507/206595339-8625bbfe-3160-4b2b-a09d-6fb8d447b5ef.png">

### Environment

 - WordPress Version 6.11
 - WooCommerce Version 6.8
 - Plugin Version 2.0
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

please contact us as soon as possible, Shawn@kongfuseo.com.au

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @ShawnW86 

this issue is most likely related to something that can happen when paying with Alternative Payment Methods, but we would expect this was mostly resolve with our 2.0.0 release.

Alternative payment methods such as iDEAL are push payments, so it will debit the customer's bank account as soon as they have authorized/approved the payment.
If the merchant doesn't capture this payment, it will be refunded automatically after 3 hours. Depending on the bank, the buyer should see the refund in a few days as SEPA transactions take a day to process.
When no order has been created in WooCommerce, then PayPal Payments will also not have captured the payment and so no funds will be added to the merchant account.
The only scenarios in which I could see this happen are either when the webhooks are not registered, or the buyer did not correctly complete the checkout process (e.g. buyer is not redirected to the order-received page).

Please check if this issue was resolved and [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We don't really provide support via GitHub, so I will close this thread.

Kind regards, 
Joost
