### ISSUE TITLE
Disputed payments not putting orders on-hold

### ISSUE THREAD

**Issue by jjcoffee** [woocommerce/woocommerce-paypal-payments#1078]
### Describe the Bug

When a customer disputes a payment via Paypal, nothing is happening on the Woocommerce end to place the order on hold (this was happening with the previous official Woocommerce Paypal plugin).

### Expected Behavior

Disputed payments should trigger Woocommerce to change order status, so that we are able to see which orders we can actually process.

### Actual Behavior

Disputed payments do not affect order status.

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.1.0
 - Plugin Version 1.9.5

**Comment by Sirvijver** [comment]
Hello @jjcoffee 

Thank you for opening this thread, however, we do not provide plugin support via the GitHub forum. This the reason it took so long before you got this response. I have to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you encountered is something we need to look into, but in order to do that we need more details from you. We will need the system report to start with, but probably more once we have taken a look. There is only a known issue like this, when using bundled products, but this might not be the case for you.

We will close this thread and wait for you to open a ticket with our support team.

Kind regards, 
Joost
