### ISSUE TITLE
Hi, I seem to be having an issue with my Paypal buttons not showing everywhere they should be on my website occasionary.co.uk

### ISSUE THREAD

**Issue by occasionary** [woocommerce/woocommerce-paypal-payments#1091]
Hi, I seem to be having an issue with my Paypal buttons not showing everywhere they should be on my website occasionary.co.uk

To Reproduce

1. Go to 'occasionary.co.uk'
2. Click on 'shop and add a product to the basket'
3. When you view the mini checkout basket in the top right corner on the product page it shows the option.
4. When you go to checkout, it doesn't show any Paypal options.

**Comment by InpsydeNiklas** [comment]
Hi there,
The [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) is taking care of this request in the official plugin support channel,
This is most likely some compatibility problem with another plugin or the theme, and the team should be able to figure it out together with you.
So I will close this issue here until an eventual issue was identified.
