### ISSUE TITLE
Something went wrong. Please try again or choose another payment source.

### ISSUE THREAD

**Issue by igorsebiski** [woocommerce/woocommerce-paypal-payments#1101]
### Describe the Bug
PayPal woocommerce payment plugin does not process payments. Error: Something went wrong. Please try again or choose another payment source. I disconnected and connect my account to PayPal but still not working

My website: imagicset.com

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version <html> 7.2.2

 - Plugin Version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version - All Browser
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
This error could be caused by [various different things](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors) and is difficult to pinpoint without more details. Please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your system report for more guidance. Thanks!
