### ISSUE TITLE
The Paypal feature on my website worked but now doesn't. It just says 'Something went wrong. Please try again or choose another payment source'. To the best of my knowledge I haven't changed anything?

### ISSUE THREAD

**Issue by silcockb** [woocommerce/woocommerce-paypal-payments#1105]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @silcockb 

We have seen that this can be related to the PayPal account. The account can be limited and under review. During this time, the account can't be used, and that message will show up. Please get in touch with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to have your account reviewed.

If you need additional support, I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, since we don't provide plugin support via GitHub (only do development).

Kind regards, 
Joost
