### ISSUE TITLE
There is not a button for activate paypal

### ISSUE THREAD

**Issue by stlntdot** [woocommerce/woocommerce-paypal-payments#1108]
![error](https://user-images.githubusercontent.com/13181858/210280511-e86cb1b1-b0e0-419e-9ad6-e525cc101362.jpg)

I am not able to connect my paypal account because there is not a button that says to activate paypal

**Comment by Sirvijver** [comment]
Hello @stlntdot 

Thank you for raising this request, however, this is not the correct platform for support request and I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you need additional guidance.

This issue was not seen before, but I would expect this is probably caused by a 3rd party plugin. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
.

Kind regards, 
Joost
