### ISSUE TITLE
Fatal error after putting a product into menu cart

### ISSUE THREAD

**Issue by chrizmc** [woocommerce/woocommerce-paypal-payments#1109]
I use Version plugin version 2.0.1 and Wordpress WordPress 6.1.1. There occurs a permanent fatal error after putting a product into menu cart:

Fatal error: Uncaught TypeError: Argument 1 passed to WooCommerce\PayPalCommerce\ApiClient\Entity\Address::__construct() must be of the type string, bool given, called in /kunden/xxx_xxx/webseiten/35_xxx/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/AddressFactory.php on line 41 and defined in /kunden/xxx_xxx/webseiten/35_xxx/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Entity/Address.php:69 Stack trace: #0 /kunden/xxx_xxx/webseiten/35_xxx/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/AddressFactory.php(41): WooCommerce\PayPalCommerce\ApiClient\Entity\Address->__construct(false, 'Asamstra\xC3\x9Fe 1', '', 'DE-BY', 'M\xC3\xBCnchen', 12345) #1 /kunden/xxx_xxx/webseiten/35_xxx/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Factory/PayerFactory.php(111): WooCommerce\PayPalCommerce\ApiClient\Factory\AddressFactory->from_wc_customer(Object(WC_Customer), 'bi in /kunden/xxx_xxx/webseiten/35_xxx/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Entity/Address.php on line 69

**Comment by Sirvijver** [comment]
Hello @chrizmc 

We do no use GitHub for support activities, so we want to advise you to[reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you need more guidance.

The issue you reported has not yet been identified, and I would expect this to caused by a conflict with the theme or another plugin. To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

This thread will now be closed, please open a new thread if you require additional support.

Kind regards, 
Joost
