### ISSUE TITLE
ERROR Failed to retrieve stored webhook data.

### ISSUE THREAD

**Issue by moarf56** [woocommerce/woocommerce-paypal-payments#1118]
### Describe the Bug

I just see lot of error message in my log website.
And it's about the error :

ERROR Failed to retrieve stored webhook data.
ERROR Failed to retrieve stored webhook data.
.....

I've had a daily message log since early December!
The plugin seems to work well, indeed a few orders have been placed with it over the days despite this error message.

### Expected Behavior

A solution to find and remove that error message.

### Environment

 - WordPress Version  6.1.1
 - WooCommerce Version 7.2.2
 - Plugin Version 2.0.1
 - Browser [e.g. Chrome, Safari] and Version Firefox 108.0.2
 - Any other plugins installed :
WooCommerce Stripe Gateway
WP Rocket

**Comment by Sirvijver** [comment]
Hello @moarf56 

This issue seems to be a support request, which we handle outside our GitHub platform. If after this response you require additional support, I would ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Our plugin has got a 2 webhook tools under the settings tab "connection". In the bottom of this tab you will find the buttons "Resubscribe" and "Simulate". Please use these 2 to see if the webhooks are functioning correctly.

It could be that only some webhooks are failing, but you could encounter issue with that over time, so it is best to use these options to restore them. For now, I will close this request, since we use GitHub only for development and not for support requests.

Kind regards, 
Joost

**Comment by black-jmyntrn** [comment]
well, i have the same issue and contacted support via the form on your site and looking to find out why this is happening and how to stop it from happening.

**Comment by daretothink1** [comment]
Did anybody manage to get this resolved. I'm getting the same thing happen, even though the plugin appears to work okay.

**Comment by jpthomasset** [comment]
I had the same issue and it is related to a missing option key in the database `ppcp-webhook` for paypal webhooks. This option is supposed to be generated when webhooks are subscribed. I'm posting here as this is where you land when you google that error.

You can check if you have the entry in your DB using this SQL Command:
```sql
select option_name, option_value from wp_options where option_name='ppcp-webhook';
```

To recreate this option and solve your issue you can either 
* Try clicking on "resubscribe webhooks" in your paypal settings/connection in woocommerce.
* If it doesn't work (it didn't for me), you can go to the paypal developer dashboard and manually remove the webhooks subscription from your connected app (`something_woocommerce` probably) and then click on "resubscribe" on your own website.

**Comment by lacikawiz** [comment]
It just happened to me. After a plugin update the logs had the `ERROR Failed to retrieve stored webhook data` 

In my case, the option value that @jpthomasset pointed out got changed to contain an invalid ID for the webhook. So when Paypal made the request to the webhook, the two IDs didn't match and the request was rejected. It showed up as a `401` status code in the Apache logs. (Interestingly and luckily enough, payments still got approved).

After restoring the previous value in that option the errors went away.

**Comment by jnz31** [comment]
i just had the same issue. i recreated the webhooks on the ppcp connections page and now the hooks work properly again.
