### ISSUE TITLE
no available payment methods for your state

### ISSUE THREAD

**Issue by ShockwaveSeats** [woocommerce/woocommerce-paypal-payments#1154]
Heyhey,

I've installed and set up WooCommerce PayPal, but as soon as I enable it as a payment option, the error code "Sorry, it seems that there are no available payment methods for your state. Please contact us if you require assistance or wish to make alternate arrangements." shows up on the cart page of our online shop. 
The shipping plugin I use is WooCommerce FedEx with print label from PluginHive. 
I have no shipping zones defined, but tried to define some for testing purposes in-between, that also didn't help. 

We used Moneris before, and as soon as I enable that, payment option appear.

Any ideas?

**Comment by InpsydeNiklas** [comment]
Hi @ShockwaveSeats, issues like this are most often caused by third-party plugins. For example, many currency switcher plugins require you to enable new payment gateways for specific currencies.
But it depends on the site configuration, and it's difficult to judge without more context about the site. If you are not sure what could be causing this behavior for you, I suggest[ performing a conflict test](https://woocommerce.com/document/woocommerce-paypal-payments/#troubleshooting) to see if the problem persists with only WooCommerce and PayPal Payments enabled. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly if you need more guidance. Thanks!
