### ISSUE TITLE
Cart broken link after setting up PayPal as payment method (woo commerce/wordpress)

### ISSUE THREAD

**Issue by chekorbla** [woocommerce/woocommerce-paypal-payments#1159]
Cart will not load after setting up PayPal as payment method. If PayPal is deactivated as a payment method, I am able to go to Cart page with no issues.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello,

Thank you for reaching out to us, we are here to help.
This is not an issue we have seen before, so have no direct conflict or resolution we can advise you about. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

We do not use GitHub for support request, so if this does not show you any indication of what is causing the issue and guide you towards a solution, we would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for additional support. If you open this ticket, it would be helpful for us if we can check this issue on a staging site, since I would expect you not to activate this in this state on your live site. We will now close this request.

Kind regards, 
Joost

**Comment by chekorbla** [comment]
I was able to resolve the issue. It turned out that Shipping and Selling locations settings under General setting was incorrect.
