### ISSUE TITLE
PayPal for WooCommerce Single Product Page Buttons Gone

### ISSUE THREAD

**Issue by TPCLTD** [woocommerce/woocommerce-paypal-payments#1162]
### Describe the Bug
The PayPal buttons are no longer displaying on my single product pages after the last update.

### To Reproduce

1. Go to 'https://thepartycake.co.uk/product/bosch-3-piece-pan-set'

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.3.0
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
`

`
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @TPCLTD 

Thank you for reaching out to us, we are here to help.
I quickly check the issue you report and in my testing environment I am seeing the PayPal buttons displayed in the Product pages. This makes me believe the issue is caused by another element on your site. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

Since we don't provide plugin support via GitHub, I would ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, in case needed.
I will mark this thread as closed.

Kind regards, 
Joost
