### ISSUE TITLE
Woo Commerce PayPal not showing up at Checkout

### ISSUE THREAD

**Issue by Papabaum** [woocommerce/woocommerce-paypal-payments#1163]
### Describe the Bug
I have disconnected and reconnected my paypal account to woo commerce.
At checkout, paypal does not show up as an option for payment.
All features are enabled for a horizontal emblem to show at checkout.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Papabaum 

There are many causes that this can occur. One of the most common cause for this is when you use a page builder and the correct short codes are used. You can verify this situation by creating a new page and only add the short code [woocommerce_checkout]. When you preview this page, you will see the PayPal button if this is the cause of the problem.

Since I don't have any details from your site, I cannot do any further checking. If you require more advice or support from our end, please [open a new thread with our support team via these instructions](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), since we don't provide support via our GitHub site.
I will mark this thread as closed.

Kind regards, 
Joost
