### ISSUE TITLE
Users report the process get stuck

### ISSUE THREAD

**Issue by fiesta-descargable** [woocommerce/woocommerce-paypal-payments#1166]
Some users report that the process gets stuck (image attached).

![paypal-cargando](https://user-images.githubusercontent.com/77939972/216797305-02ae0a2e-9e10-4e71-97f2-1e83aee4f90c.jpg)

**Comment by Sirvijver** [comment]
Hello @fiesta-descargable 

Thank you for reaching out to us, we are here to help.

We have seen this pop up a few times and believe there was made a change on the PayPal server side, since the plugin does not have much control over the standard card payment option that is causing this. I would also not think switching to PayPal standard would fix this issue, but you might have experience with this and can tell?

We believe there are 2 options for possibly fixing this.

We recommend you to change the Card billing data handling setting to not send the WC form data to PayPal.
Use WC checkout form data is the default and makes the payment for buyers more convenient because they only have to add card number details.
But this only works as long as the WC billing information also match up with the card billing details. E.g. setting Do not use WC checkout form data would result in the user having to double enter payment details. First in WC, then after clicking the black button in the PayPal smart card fields. The best solution in between is Request only name and postal code as this is a mix between the two that should, in theory, prevent billing-details related problems.
Switch to the Advanced Card Processing payment option. This option is controlled from our plugin and should not encounter the problem you are describing (since no pop up should be required for the payment, only for the instances that 3DS is required). You can read more about this payment option here.

We do actually not provide plugin support via GitHub, so I will close this thread and ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly in case you require more guidance.

Kind regards,
Joost
