### ISSUE TITLE
My checkout page does not show any payment methods anymore

### ISSUE THREAD

**Issue by ElinaZandere** [woocommerce/woocommerce-paypal-payments#1175]
### Describe the Bug

My checkout page does not show any payment methods anymore – I have checked the WP Woocomerce payments settings and from my view, everything is still switched on – enable and connected (stripe card payments and Paypal). What could cause this error? I notice some strange things – the WP dashboard Woocomerce payment settings do not show any preview of cards and PayPal buttons – just a short flash of the images. yesterday I worked on the plugin Smush but I tried to deactivate the last plugins I have added but still nothing. And after all, I see that also apple pay is gone. So the only "place order" is the option I see now on the checkout. When I am going from tab to tab in WP Woocomerce payments settings they are showing empty grey boxes and after just some time loading the images: For example, I am choosing to manage stripe card settings and in the first seconds I see just empty boxes and after they are loading just options – I also add screenshots. Of course, I do not know if is it somehow connected but I add all info I can figure out :) 
![Screenshot 2023-02-09 at 12 23 18](https://user-images.githubusercontent.com/124814175/217787124-362e6fc6-dc58-4c93-99c3-1d0b6c2be2e2.png)
![Screenshot 2023-02-09 at 12 27 37](https://user-images.githubusercontent.com/124814175/217787133-e6a6149f-1440-4b1c-ab31-b8a2ca239aeb.png)

![Screenshot 2023-02-08 at 21 15 02](https://user-images.githubusercontent.com/124814175/217783518-280d719d-bbd3-4d93-b4d1-d64a59835f85.png)
![Screenshot 2023-02-08 at 21 14 32](https://user-images.githubusercontent.com/124814175/217783525-1356c293-1bd1-40d4-93bd-0847dc81f919.png)
 page. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

I have added 2 screenshots to show the flash of images that disappears after a second in WP payment settings 

### Environment

 - WordPress Version WordPress 6.1.1
 - WooCommerce Version Version 7.3.0
 - Plugin Version WooCommerce PayPal Payments Version 2.0.2 WooCommerce Stripe Gateway Version 7.0.2
 - Browser [e.g. Chrome, Safari] and Version I tried different – the same
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @ElinaZandere, I understand you are encountering some issues with your payment settings. Based on the information provided, it appears that the Stripe plugin is causing some modifications to the WooCommerce settings page. If you disable the plugin, the page should return to its normal state.
Regarding the "flashing images", these are parts of the PayPal Payments settings that are temporarily visible before being hidden via JavaScript. These are not needed when your account is already connected. To ensure that the issue is thoroughly addressed, I recommend [reaching out directly to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) . Thanks!
