### ISSUE TITLE
iDeal issue via mobile phone

### ISSUE THREAD

**Issue by jairzino** [woocommerce/woocommerce-paypal-payments#1179]
### Describe the Bug

When paying via iDeal, 2 new windows open. 1 from paypal and 1 from the bank (in my situation it was the ING bank).
When succesful paid, the window stays open mentioning I recieve an e-mail with the order confirmation. The window does not close nor am I getting redirected to the store. 
I close the window and also need to close the paypal window. I see the checkout page of the store but not mentioning I succesfully paid. It is like I still need to pay. Though I see the payment reducted from my bankaccount. Unfortunately I can not see the payment on my paypal account nor do I see an order at the backend.

I have tried it 3 times. The money is misteriously missing.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.3.0
 - Plugin Version 2.0.2
 - Browser [e.g. Chrome, Safari] and Version Chrome android mobile (galaxy 22 ultra)
 - Any other plugins installed No

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @jairzino 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

However, the issue is a known one and is related to these push payments, such as iDEAL. 
Alternative payment methods such as iDEAL are push payments, so it will debit the customer's bank account as soon as they have authorized/approved the payment.
If the merchant doesn't capture this payment, it will be refunded automatically after 3 hours. Depending on the bank, the buyer should see the refund in a few days as SEPA transactions take a day to process.
When no order has been created in WooCommerce, then PayPal Payments will also not have captured the payment and so no funds will be added to the merchant account.
The only scenarios in which I could see this happen are either when the webhooks are not registered, or the buyer did not correctly complete the checkout process (e.g. buyer is not redirected to the order-received page).

If you have additional questions about this situation, I suggest you open a new thread with our support team. This thread will be closed.

Kind regards, 
Joost
