### ISSUE TITLE
Form to input credit cards not aligned correctly

### ISSUE THREAD

**Issue by Catelynn** [woocommerce/woocommerce-paypal-payments#1180]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots

[Screenshot 2023-02-10 14 40 05](https://user-images.githubusercontent.com/7873658/218200055-ef47820d-cea2-4ed7-9e77-ea8645ae568e.png)

![Screenshot 2023-02-10 14 42 57](https://user-images.githubusercontent.com/7873658/218200320-e368ef16-c687-445a-a9ad-a64a8a9d220f.png)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
@Catelynn The card fields are styled by your theme, so I suggest reaching out to your theme developer. The field styling can also be adjusted via CSS: https://woocommerce.com/document/woocommerce-paypal-payments/#customizing-hosted-fields

But for any additional questions, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly to receive more guidance. Thanks!

**Comment by Catelynn** [comment]
Hi,

I use this theme for 2 other sites and Woo commerce using other CC
providers and I do not have this problem.

**Comment by InpsydeNiklas** [comment]
Hi @Catelynn,
 
> using _other CC providers_ and I do not have this problem.

Most other card providers are working differently and insert iframes instead of hosted fields on your checkout page.
Unlike most iframes, hosted fields can be styled with CSS, e.g. by your theme.

When using the free version of the theme you mentioned, I can reproduce the behavior with the fields not being aligned.
So I still recommend reaching out to the theme developer as the theme is effectively styling the card fields. With a different theme like Storefront or a default WordPress theme, this behavior should be resolved.

That being said, if anything remains unclear or if you need further guidance, please [get in touch with the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).
Thanks!
