### ISSUE TITLE
Performance issue (1448)

### ISSUE THREAD

**Issue by ijerkov** [woocommerce/woocommerce-paypal-payments#1182]
### To Reproduce

1. Go to any page and open Query monitor
2. Check the slow query log

### Screenshots

https://prnt.sc/pklVJtAX8P4o
### Expected Behavior

Not seeing this 

### Actual Behavior

Slowing down every page for 10ms

### Environment

 - WordPress Version
 - WooCommerce Version Version 7.3.0 
 - Plugin Version Version 2.0.2

### Additional Details

SELECT 1
FROM wp_posts p JOIN wp_postmeta pm
ON pm.post_id = p.ID
WHERE p.post_type = 'shop_subscription'
AND p.post_status != 'trash'
AND pm.meta_key = '_payment_method'
AND pm.meta_value = 'ppec_paypal'
LIMIT 1

Called by
WooCommerce\P\C\P\PPECHelper::site_has_ppec_subscriptions()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/PPEC/PPECHelper.php:79
WooCommerce\P\C\P\PPECHelper::use_ppec_compat_layer_for_subscriptions()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/PPEC/PPECHelper.php:95
WooCommerce\P\C\P\SubscriptionsHandler->maybe_hook()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/PPEC/SubscriptionsHandler.php:55
WooCommerce\P\C\CompatModule->initialize_ppec_compat_layer()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/CompatModule.php:79
WooCommerce\P\C\CompatModule->run()
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-compat/src/CompatModule.php:48
{closure}()
wp-content/plugins/woocommerce-paypal-payments/bootstrap.php:54
WooCommerce\PayPalCommerce\init()
wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php:75
WooCommerce\PayPalCommerce\{closure}()
wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php:88
do_action('plugins_loaded')

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
PayPal Payments automatically takes over subscriptions from the PayPal Checkout plugin. This feature can be disabled with a filter: 
```php
add_filter('woocommerce_paypal_payments_process_legacy_subscriptions', static function(){
return false;
});
```
https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-paypal-checkout-gateway-migration-layer-ppec-helper

**Comment by ijerkov** [comment]
Thanks for the snippet but it doesn't work unless you rewrite the line of
code like this:

  /**

   * The filter returning whether the compatibility layer for PPEC
Subscriptions should be initialized.

   */

  return ( ! self::is_gateway_available() ) && apply_filters(
'woocommerce_paypal_payments_process_legacy_subscriptions', true ) && self::
site_has_ppec_subscriptions() ;

}

Because the SQL is run before the filter is checked. Can you fix this in
the future?

Thanks,
Ivo

**Comment by prettyboymp** [comment]
This query doesn't scale well and runs by default on every page load with the plugin installed and active.  On sites with large ~~numbers of post/post meta~~ order/subscription data, it will quickly take the site down.

```
+----+-------------+-------+--------+--------------------------+----------+---------+---------------------+--------+------------------------------------+
| id | select_type | table | type   | possible_keys            | key      | key_len | ref                 | rows   | Extra                              |
+----+-------------+-------+--------+--------------------------+----------+---------+---------------------+--------+------------------------------------+
| 1  | SIMPLE      | pm    | ref    | post_id,meta_key         | meta_key | 258     | const               | xxxxxx | Using index condition; Using where |
| 1  | SIMPLE      | p     | eq_ref | PRIMARY,type_status_date | PRIMARY  | 8       | xxxxxxxx.pm.post_id | 1      | Using where                        |
+----+-------------+-------+--------+--------------------------+----------+---------+---------------------+--------+------------------------------------+
```

**Comment by ijerkov** [comment]
Hi, I fixed the problem by adding index to postmeta table. It's not a
problem anymore.

**Comment by markdavella** [comment]
@InpsydeNiklas I just want to echo @ijerkov's comment here.  That feature may be disabled but it certainly doesn't resolve the performance issue with how you have the code written.  I installed this plugin a few days ago and it has quickly become a performance bottleneck, despite processing 0 payments so far.

You can see the impact once I installed it on April 17th:
<img width="1872" alt="image" src="https://user-images.githubusercontent.com/6005331/233697182-d7aa5398-b166-41a4-8d6b-47065d139b71.png">

I've never used Paypal Checkout Gateway so your support team told me I could disable the migration layer using the 'woocommerce_paypal_payments_process_legacy_subscriptions' filter.  However, as noted above, because of the order of the conditions the query still runs no matter what the filter is set to.  I understand that setting an index on the database will improve performance but the real solution here is to not run queries that don't need to be run.

How can we get this issue re-opened and prioritized as this plugin is killing sites with large databases?

Here's the impact of the plugin on my apdex score:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/6005331/233698142-3f063878-b5d0-4945-bee1-5329faece61d.png">

**Comment by ijerkov** [comment]
I resolved this issue by adding index on postmeta, I have to check what
exactly I did.

**Comment by prettyboymp** [comment]
> I resolved this issue by adding index on postmeta, I have to check what exactly I did.

That isn't a great long term solution as there are storage and insert performance costs to consider when adding an index on `post_meta.meta_value`.  Adding a transient around the query to avoid having to run it on every load would go a long way.  At least until a full migration from the old PayPal subscriptions can be dealt with.

**Comment by ijerkov** [comment]
Agreed, I don't understand why this query runs on every page.

**Comment by InpsydeNiklas** [comment]
The behavior is under investigation but that's all I can say for now. Will reopen this in the meantime and provide new details when they are available.

**Comment by markdavella** [comment]
Thanks for re-opening, appreciate that!

I ended up overriding the plugin code while you guys work on this on your end.

I re-arranged the conditional so that the query doesn't run when 'woocommerce_paypal_payments_process_legacy_subscriptions' is disabled and you can see the impact of that update here (made update April 24th):

<img width="1875" alt="image" src="https://user-images.githubusercontent.com/6005331/234678513-4cff5881-2378-4e94-863e-78144f7e8608.png">

**Comment by ijerkov** [comment]
I did that too and the next day client told me he received some paypal
payments for the subscriptions that were cancelled long time ago. I don't
know if these events are connected or not but I reverted the change
immediately.

**Comment by Braintelligence** [comment]
Hello everyone; I'm suffering greatly from this issue. We have a shop here with variant products that result in more than a million products.

The checkout page needs >20 seconds to load, this is very bad.

Is there any ETA on a fix?

**Comment by InpsydeNiklas** [comment]
The PR linked above will be included in the upcoming update. This should result in the queries only running after a transient expires **&** the migration filter is enabled, resulting in improved performance.
A new pre-release version for this update will be available for testing within the next couple of days  [here on GitHub](https://github.com/woocommerce/woocommerce-paypal-payments/releases).

> I did that too and the next day client told me he received some paypal
> payments for the subscriptions that were cancelled long time ago. I don't
> know if these events are connected or not but I reverted the change
> immediately.

@ijerkov This doesn't sound related, but if you encounter any problems of such kind, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly so we can investigate it deeper. Thanks!
