### ISSUE TITLE
webhook simulation is not working

### ISSUE THREAD

**Issue by lisaiceland** [woocommerce/woocommerce-paypal-payments#1190]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @lisaiceland 

I am not seeing any details in your support request. We do however not provide support via GitHub, so I want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Please also provide more details and a proper problem description. I will close this thread.

It does sound like you need to perform [conflict testing](https://woocommerce.com/document/how-to-test-for-conflicts/), so that might be something you should do before opening a new support request with us.

Kind regards,
Joost
