### ISSUE TITLE
I can not connect my paypal account.

### ISSUE THREAD

**Issue by Chestita1** [woocommerce/woocommerce-paypal-payments#1191]
### Describe the Bug

When I try to connect my paypal account, not happens. I do the steps and the I come back to the wocommerce page and my paypal account it is not sincronized.

**Comment by Sirvijver** [comment]
Hello @Chestita1 

I am not seeing any details in your support request. We do however not provide support via GitHub, so I want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Please also provide more details and a proper problem description. I will close this thread.

There is an issue with the onboarding process where when you go through the onboarding process too quickly, the background processes don't get completed, so you might want to try again and take a few seconds before clicking next or completing the process.
Another option is to [manually onboard the PayPal account](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input), but that is a last resort, since it could potentially skip some processes that affect functionalities of the plugin.

Kind regards,
Joost
