### ISSUE TITLE
Unable to connect paypal account to woocommerce

### ISSUE THREAD

**Issue by abdougbs** [woocommerce/woocommerce-paypal-payments#1197]
I go through a loop of PayPal saying "You now have an account, and you've successfully integrated PayPal with WooCommerce." but when I go back to Woocommerce it still says that I have to connect to PayPal

To Reproduce 
1. Go to the woocommerce plug in
2. click the payments tab
3. Click Activate PayPal
4. Login to PayPal
5. Click "Agree and Connect"
6. Paypal says "You now have an account, and you've successfully integrated PayPal with WooCommerce."

1. Go to '…'
7. Click on '…'
8. Scroll down to …'
9. See error

### Screenshots
<img width="1151" alt="Screen Shot 2023-02-17 at 2 56 06 PM" src="https://user-images.githubusercontent.com/125696229/219779018-dbca8770-d92e-470a-93fc-0d7704499869.png">

### Expected Behavior

Paypal to successfully connect to woocommerce

### Actual Behavior

Paypal is not connected and the activate button sends me through the same loop again with the same results of not connecting

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.0
 - Plugin Version 2.0.2
 - Browser Chrome
 - Any other plugins installed - 44 diff plugins installed.

**Comment by Sirvijver** [comment]
Hello @abdougbs 

We do  not provide support via GitHub, so I want to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Please also provide more details and a proper problem description. I will close this thread.

There is a known situation with the onboarding process where when you go through the onboarding process too quickly, the background processes don't get completed, so you might want to try again and take a few seconds before clicking next or completing the process.
Another option is to [manually onboard the PayPal account](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input), but that is a last resort, since it could potentially skip some processes that affect functionalities of the plugin.

Kind regards,
Joost
