### ISSUE TITLE
BUG paypal on woocommerce

### ISSUE THREAD

**Issue by DodoGirl** [woocommerce/woocommerce-paypal-payments#1198]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @DodoGirl 
I am not seeing any information on this entry, so I will close it. You might want to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, since we do the basic support via other platforms and GitHub only for development activities.

Kind regards, 
Joost
