### ISSUE TITLE
Error during payment procedure. Retry later

### ISSUE THREAD

**Issue by pitufo13** [woocommerce/woocommerce-paypal-payments#1199]
### Describe the Bug

Non è possibile completare la procedura di pagamento di un 'Pacchetto'. Al termine della procedura esce un messaggio di errore che dice **Error during payment procedure. Retry later**

### To Reproduce

1. Go here https://www.dijoapicoltura.it/prodotto/pacchetto-sostenitore/
2. Click on 'Aggiungi al carello', then click on 'Visualizza Carrello'
3. Click on 'Clicca per Procedere'
4. Complete mandatory fields then click on Paypal button and procede with PayPal
5. At the end an error message come out

### Screenshots

![image](https://user-images.githubusercontent.com/125906460/220162455-7a07b66c-e2de-411a-b2f2-685e22fbc419.png)

### Expected Behavior

Complete correctly the checkout

### Actual Behavior

Not possible to complete the checkout

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.4
 - Plugin Version - WooCommerce PayPal Payments 2.0.2
 - Browser [e.g. Chrome, Safari] and Version - Chrome latest
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @pitufo13 

The issue you have encountered seems to be related to your account. You could try to disconnect and onboard your account again, this could be an option to resolve the issue. 
It would be wise to activate the logging function on our plugin, so you will get more details on this issue. You can also get in contact with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to have your account and a possible transaction (if available) reviewed.

We only use GitHub for development activities and since this is a support request, I will close this thread. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance if that is required.

Kind regards, 
Joost
