### ISSUE TITLE
Endless loading/spinner on the checkout page - WooCommerce - Paypal option

### ISSUE THREAD

**Issue by Sarel12** [woocommerce/woocommerce-paypal-payments#1204]
### To Reproduce

1. Go to 'creationhub.shop'
2. Click on 'shop and select digital item'
3. Scroll down to  and check out, select paypal option'

### Screenshots
![image](https://user-images.githubusercontent.com/125990269/220370324-7da0b91e-c4cf-45f9-9612-52c257cf0f53.png)

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.0
 - Plugin Version - WooCommerce PayPal Payments 2.0.2
 - Browser [e.g. chrome and edge
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @Sarel12, this could be caused by many things, including unsupported currencies. With the provided details, we can't tell for sure, but it's unlikely to be a bug in the plugin. So I recommend [contacting the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
