### ISSUE TITLE
Description is diffrent when user Pay using PayPal vs Cradit Card.

### ISSUE THREAD

**Issue by vermadilipjpr** [woocommerce/woocommerce-paypal-payments#1206]
![18](https://user-images.githubusercontent.com/7532326/220633303-4d9fb6f1-0446-4c0a-85a1-11920ecdd4c4.png)
![Screenshot_17](https://user-images.githubusercontent.com/7532326/220633306-ed45d253-0103-44d4-a244-0ae118fe2537.png)
When a customer made a payment to purchase a product from my website I received an Email from Paypal regarding that Transaction but here is the point......

if at the time of checkout, the customer chooses the debit/credit card option to make the payment then the mail I get from Paypal is well managed, and the description of the mail contains all the products purchased by the customer in new lines.

but if they choose the PayPal option for payment then the mail I got from Paypal does not have a well-managed description instead of it it has all the products in one line and you can't tell how many products are purchased by the customer.

I want both emails in the same format where each product is listed in the new line in the transaction description field. like the email, I received when customers pay with a debit/credit card
![Screenshot_17](https://user-images.githubusercontent.com/7532326/220632761-6a1567c6-6a76-47c7-8ef3-4a1f347d9703.png)
![Screenshot_4](https://user-images.githubusercontent.com/7532326/220632782-353ec481-e02a-4af3-9748-c258953cf96a.png)
![Screenshot_17](https://user-images.githubusercontent.com/7532326/220632783-4ce0a118-7e69-499f-b468-9defbe5db4b2.png)

Am I able to customize the PayPal emails to show the individual items within the order?

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @vermadilipjpr 
If this behavior persists for you, I suggest contacting the [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to understand what would make the difference in this regard.
I can't reproduce this reported behavior in the PayPal sandbox, and the plugin does not directly control how the emails look. Regardless of whether you use PayPal or credit cards, the items should be in separate lines in any case.
But when logging is enabled in the plugin, the PayPal technical support usually can provide guidance.

Otherwise, if you encounter any problems with PayPal Payments, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a link to this issue for more guidance. Thanks!
