### ISSUE TITLE
Oxxo activated by default even with the option deactivated

### ISSUE THREAD

**Issue by Bebuk85** [woocommerce/woocommerce-paypal-payments#1211]
Hi, Oxxo is showing up in the checkout as payment method, but i didn't manage that setting in the PayPal settings, also it's deactivated.

![image](https://user-images.githubusercontent.com/72046610/221294825-fea70c15-9fe5-4b53-acff-30c5ce261f15.png)

![image](https://user-images.githubusercontent.com/72046610/221294870-046bb3bb-3266-4c63-9ebb-641f24983c5d.png)

**Comment by InpsydeNiklas** [comment]
Hi @Bebuk85 
This OXXO JSSDK button from your screenshot usually should not appear.
If you see this button with your live PayPal account and you don't want it, I suggest contacting the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) to have this feature turned off. 
As far as I am aware, PayPal is testing certain APMs in a limited beta, but this is not part of PayPal Payments at this time.

The OXXO integration in PayPal Payments creates a separate gateway instead of loading the JSSDK button:
![image](https://user-images.githubusercontent.com/70433191/227604811-e728439f-a163-464b-bb2c-1eab104eb4d9.png)

If any questions remain, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
