### ISSUE TITLE
Connect account button does nothing

### ISSUE THREAD

**Issue by byramsewell** [woocommerce/woocommerce-paypal-payments#1212]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @byramsewell 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There are some things you can do to try to get your account onboarded successfully:
**1. Take your time.** When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.
**2. Another plugin can be blocking the onboarding process.** You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.

The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input).

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost
