### ISSUE TITLE
After Credit card payment user is invited to log on paypal

### ISSUE THREAD

**Issue by Yellink** [woocommerce/woocommerce-paypal-payments#1213]
Hello

### Describe the Bug
Since january (sorry can't be precise on the date, maybe one of the last release) clients are complaining about a problem  when they pay by credit card (using paypal without log in)

AFter paiement by credit card the client are invited to log on paypal, if they close the paypal window... transaction appears nowhere, client is frustrated, and merchant lost a transaction. What to do ??
### To Reproduce

1/ Click and choose the black credit card button (to avoid login on paypal)   to pay
2/ Fill Credit card infos
3/ Validate and Confirm the paiement on the bank app if needed (3D secure)
4/ Redirecton on the merchant website works
5/ PROBLEM HERE : we are invited to log on paypal
6/ Close the paypal window
7/ Page is never loaded (turning turning), nothing happend.... transaction is like never happened

### Expected Behavior
we expected it works well like it always been. When you want to pay by credit card without paypal account, you of course don't want to log in paypal at the end of the process. So we except this log in window does not appear and transcation is validated. So everyone is happy ;)

### Environment

 - WordPress Version : WordPress 6.1.1
 - WooCommerce Version : Version 7.4.0
 - Plugin Version : Version 2.0.2
 - Browser [e.g. Chrome, Safari] and Version : Tested on desktop, and mobile, safari and chrome latest releases
 - Any other plugins installed

410 for WordPress | Version 0.8.7
Advanced Custom Fields | Version 6.0.7 
All In One WP Security | Version 5.1.5
Event Tickets | Version 5.5.8
Getwid | Version 1.8.3 par MotoPress
Gravity Forms | Version 2.7.1
Homepage Control | Version 2.0.3
Product Delivery Date Pro for WooCommerce | Version 3.13.1
tarteaucitron.js - Cookies legislation & GDPR | Version 1.6.4 par tarteaucitron.io
The Events Calendar | Version 6.0.10 par The Events Calendar
WooCommerce | Version 7.4.0 par Automattic
WooCommerce Advanced Shipping Packages | Version 1.1.8
WooCommerce Checkout Manager | Version 7.0.6
WooCommerce Conditional Shipping | Version 1.4.1
WooCommerce PayPal Payments | Version 2.0.2
WP Rocket | Version 3.12.5.3
YITH WooCommerce Product Add-ons & Extra Options Premium | Version 3.11.0
Yoast SEO | Version 20.1 par Team Yoast

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by thinkjarvisdesignandmarketing** [comment]
I can also confirm this issue.
Same problem asks user to sign in to PayPal when using the pay by debit card option.

This worked fine 2 weeks ago.

**Comment by thinkjarvisdesignandmarketing** [comment]
**How to recreate and other issues surrounding this problem**

**Recreate issue every time**

1. This problem always occurs in a private browsing window or when you are using the mini browser that opens when you follow a link in an app like instagram or facebook.
2. When you hit the payment screen in a private browsing window fill out your details and clickthe Paypal pay by direct debit/ credit card button
3. After you have entered your card details in the on page dropdown and clicked pay the 3d secure box appears
4. In this box it then asks for a paypal email and password - IT IS NOT SUPPOSED TO!!! This is a guest method of payment.
5. It then hangs on processing.
6. The order is not processed and it is impossible to pay using this method
7. If you try clicking Pay Pal and sign in using the usual route it works fine.

This affects ALL WooCommerce websites on my server that use PayPal. I think this is a global problem.

**Workaround and new issue**
If you disable the Pay by Debit/Credit Card option and change the Landing Page in the Paypal plugin settings to Billing (Non-Paypal Account). On Desktops you can pay without creating an account but the slider switch disappears on mobile phones. So it forces you to create an account.

**I therefore think there is a bug in this part of the system because it forces you to create an account when paying by direct debit or credit card as a guest without a paypal account**

I was only able to make this work in a normal browsing window on my desktop PC.

So the issue where it asks the user to sign in even though they chose the guest pay by card option occurs 100% of the time in an incognito browser or in a social refer app mini browser.

The secondary issue where the slider switch is missing is just a pain because this was my workaround solution but this also does not work.

**Please can the developer confirm that this issue has been confirmed and added to an urgent bug fix.**

**Comment by thinkjarvisdesignandmarketing** [comment]
This has been tested on a windows PC, an android smartphone and two different iphones. (I am a web dev so I had to investigate this properly for the client).

There are no errors in the console the process followed by the plugin to process the payments appears to be programmed incorrectly.

**Comment by Sirvijver** [comment]
Hello @Amanshaya and @thinkjarvisdesignandmarketing 

Thank you for reaching out to us. You have reached out to the plugin support, and we believe this issue is caused on the PayPal server, since the problem occurs only with the Standard Card Processing payment option (correct me if I'm wrong).
We have asked PayPal to look into this and get it corrected. I have now also advised them of this GH thread and linked it to our internal bug we opened for this (in order to gather all related support requests).

If you want to switch over to the Advanced Card Processing payment method (which could resolve this issue for you), you should look here for more information on this:
- [Advanced Card Processing](https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-card-processing-acdc).
- [Manual Onboarding/vetting process for Advanced Card Processing](https://woocommerce.com/document/woocommerce-paypal-payments/#sign-up-for-advanced-card-payments).
- [Adding countries in case the required country is not allowed Advanced Card Processing to be used](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#add-advanced-credit-and-debit-card-acdc-countries).

I will keep this GitHub thread open for now, to continue our communication, but if you require additional support from our support team, I would advise to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost

**Comment by InpsydeNiklas** [comment]
PayPal confirmed to have resolved this issue on March 28th. 
No plugin update is needed. But if you haven't updated to 2.0.4 yet, we recommend doing so.
If this issue persists for you, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this issue.
Thanks!
