### ISSUE TITLE
PayPal plugin error

### ISSUE THREAD

**Issue by edgargold09** [woocommerce/woocommerce-paypal-payments#1218]
### To Reproduce

1 - go to woocommerce payments settings
2 - go to paypal settings
3 - click on the button to activate paypal
4 - enter my paypal username and password

### Screenshots

![Captura de pantalla 2023-02-28 a las 9 55 15](https://user-images.githubusercontent.com/126595465/221916692-21bff6b0-c463-4f85-9fa5-4a5bf7da3f74.png)

### Environment

 - WordPress Version 6.1.1
 - WooCommerce Version 7.4.0
 - Plugin Version (WooCommerce PayPal Payments 2.0.2) 
 - Browser [e.g. Chrome, Safari] and Version chrome 87.0.4280.88

</details>

**Comment by Sirvijver** [comment]
Hello @edgargold09 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There are some things you can do to try to get your account onboarded successfully:
1) take your time. When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.
2) Another plugin can be blocking the onboarding process. You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.

The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input).

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost
