### ISSUE TITLE
Generic error not handled if the mandatory fields are not completed at checkout

### ISSUE THREAD

**Issue by filippo1996** [woocommerce/woocommerce-paypal-payments#1235]
### Describe the Bug
Hi, a customer informed us that he couldn't make a payment with paypal because it gave him an error:

Something went wrong. Please try again or choose another payment source.
Unfortunately, being such a generic error, the user did not know what to do and contacted us.

I noticed that the customer failed to check the box to accept the terms and conditions. But the paypal plugin wasn't exactly showing the error.
I also noticed that pressing the paypal buy button sometimes showed the actual message (terms and conditions) and other times it didn't (showing the generic error mentioned above).
Unfortunately it is unpredictable and I had to disable your plugin as we cannot afford to lose purchases.
I hope you can help me solve the problem, thanks

### To Reproduce
This generic error message occurs more often in mobile mode, in fact the screen is from an iphone.

### Screenshots
<img width="1058" alt="Screenshot 2023-03-07 alle 21 23 34" src="https://user-images.githubusercontent.com/32218336/223550159-96391273-764a-4bbe-85bf-c1083b9027ac.png">

![IMG_8089](https://user-images.githubusercontent.com/32218336/223551130-275adae2-9ac4-4b0b-971e-53d578003112.PNG)

### Environment

 - WordPress Version: 6.1.1
 - WooCommerce Version: 7.4.1
 - Plugin Version: 2.0.2
 - Browser [e.g. Chrome, Safari] and Version: Chrome 110.0.5481.177 (Build ufficiale) (x86_64)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
### WordPress Environment ###

WordPress address (URL): https://www.forap.it
Site address (URL): https://www.forap.it
WC Version: 7.4.1
REST API Version: ✔ 7.4.1
WC Blocks Version: ✔ 9.4.4
Action Scheduler Version: ✔ 3.5.4
Log Directory Writable: ✔
WP Version: 6.1.1
WP Multisite: –
WP Memory Limit: 256 MB
WP Debug Mode: –
WP Cron: –
Language: it_IT
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.20.1
PHP Version: 8.0.16
PHP Post Max Size: 64 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.68.0
OpenSSL/1.1.1f

SUHOSIN Installed: –
MySQL Version: 10.4.24-MariaDB-1:10.4.24+maria~focal-log
Max Upload Size: 64 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @filippo1996 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I checked the same situation on my testing environment and when I don't check the terms & conditions box, I get the error "Please read and accept the terms and conditions to proceed with your order.".
There must be something on your site that is avoiding this error to be displayed. Can you do some more testing and see if any other plugin might be causing this? To get to the bottom of this, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin.
Please create a backup of the site first before proceeding.

We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
For more detailed instructions, check out [How to test for plugin and theme conflicts](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Conflict testing should always be done on a staging site if possible. If your host doesn't provide a staging site, we can recommend the plugin [WP STAGING](https://wordpress.org/plugins/wp-staging/) to create a staging site with a few clicks.
Please remember first creating a new backup and checking available disk space before making any changes to your live site like creating a staging clone.

Alternatively, you can also install the plugin Check Conflicts - https://wordpress.org/plugins/check-conflicts/ - This allows you to change theme and plugin activations only for your IP address, so the changes are not visible to other visitors of your site.
Here is the brief instruction on how to do conflict testing with the said plugin:
Prerequisites:
- Install [Check Conflicts](https://wordpress.org/plugins/check-conflicts/) plugin
- Install [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme
Conflict Testing:
1. Navigate to Check Conflicts on the side navigation bar. Choose [Storefront](https://woocommerce.com/storefront/?aff=10486&cid=1131038) theme. Then click "Save"
2. Try to reproduce the problem: Check Credit Card fields on Checkout page. If the problem is resolved, it's a theme conflict. If not, continue to the next steps.
3. Navigate back to Check Conflict. Temporarily deactivate all plugins except for WooCommerce and PayPal Payments.
4. Try to reproduce the issue again. If the problem is resolved, it's a plugin conflict. To figure out which plugin is causing the problem, continue to the next step.
5. Navigate back to Check Conflict. Select one plugin at a time and click "Save" (To multi-select, you need to hold on the "Crtl" key on PC or "Cmd" key on Mac)
When you are using the Check Conflicts plugin, you can click on "Cancel" to immediately stop the conflict testing mode.
Here is a quick instructional video on how to use the plugin: https://cln.sh/rjELyp

As said before, we don't provide plugin support via this interface, please use the link provided above to engage our support team if you require additional support. This ticket will now be closed.

Kind regards, 
Joost
