### ISSUE TITLE
WooCommerce PayPal Payments - reference_id error

### ISSUE THREAD

**Issue by christinemh** [woocommerce/woocommerce-paypal-payments#1253]
### Describe the Bug
I am not a coder. I just clicked on "report a bug" in WP admin for this plugin WooCommerce PayPal Payments.
I installed this plugin a few days ago, and just received 2 failed orders.
The note in the order says: _Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID CreditCardGateway.php:406 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID OrderEndpoint.php:327_ 
This PayPal developer page doesn't even list the error DUPLICATE_INVOICE_ID in the list of errors in the section UNPROCESSABLE_ENTITY.
https://developer.paypal.com/api/rest/reference/orders/v2/errors/
Can someone help?
Thanks

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @christinemh 

Thank you for reaching out to us. However, you are not reporting a bug, but request support for getting the plugin to function correctly. In this case, you should have chosen the "Get Help" button instead. I will provide you our initial response on this issue now, but will close the thread, since we only do development activities here and don't provide support. I would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance if required.

The error DUPLICATE_INVOICE_ID error is a security feature from PayPal which aims to prevent accidental double-payments.

PayPal Payments automatically sets an "invoice prefix" and then sends the WooCommerce order numbers in the pattern "invoice prefix+ordernumber" to PayPal.
So when your prefix is set to "cfbdg-" and your order number is "123", PayPal Payments sends the invoice ID "cfbdg-123" to PayPal.

Now, when you restore a backup from your website, it is possible that the most recent WooCommerce orders do not exist anymore after the restore.
So as soon as WooCommerce attempts to create a new order with the number 123 and the same invoice prefix, PayPal would throw this error to prevent accidental double payments because there is already a payment at PayPal with the same invoice ID.
This feature can be disabled, though we usually recommend keeping it enabled. To disable it, follow these steps:

1. Log in to your Business PayPal account (https://www.paypal.com/businessmanage/preferences/payments)
2. Go to the Payments Preferences section
3. Under the "Block accidental payments:" section, select the option "No, allow multiple payments per invoice ID"

With this feature disabled, PayPal would no longer complain when you submit an invoice number that already exists in the system.

I will mark this thread as closed now.

Kind regards, 
Joost
