### ISSUE TITLE
Kauf auf Rechnung Bestellung steht auf "In Wartestellung" Geld ist aber gebucht

### ISSUE THREAD

**Issue by vonzurgathen** [woocommerce/woocommerce-paypal-payments#1255]
Kauf auf Rechnung Bestellung steht auf "In Wartestellung" - wir als Händler haben das Geld aber über PayPal erhalten.
Das Plugin hat dies nur nicht registriert und die Bestellung bleibt auf "In Wartestellung" (auch nach 18 Std. noch) 
Bearbeiten wir die Bestellung nun manuell erhält der Kunde später eine Mail ohne Angaben wohin er überweisen muss.

Bitte überweisen Sie den Betrag in Höhe von 929,00 € bis zum 13-04-2023 auf das unten angegebene Konto. Wichtig: Bitte geben Sie unbedingt als Verwendungszweck an, sonst kann die Zahlung nicht zugeordnet werden.
•	Empfänger: 
•	IBAN: 
•	BIC: 
•	Name der Bank: 
•	Verwendungszweck: 

WooCommerce 7.50
PayPal Payments Version 2.0.3

**Comment by Sirvijver** [comment]
Hello @vonzurgathen 

This platform is intended mainly for development. We will give you our initial idea of what could be causing this issue, but have to advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for additional guidance.

It sounds like the WooCommerce site is not receiving the confirmation of the payment. This is usually caused by webhook issues, so I would advise you to use the webhook tools that can be found in the bottom of the settings page under the tab "Connection". Please use the "Simulate" and "Resubscribe" option here and open a new support thread as mentioned before if additional support is required.

I will mark this support thread as resolved.

Kind regards, 
Joost
