### ISSUE TITLE
PayPal checkout constantly loading

### ISSUE THREAD

**Issue by tharteveld26** [woocommerce/woocommerce-paypal-payments#1260]
When checking out the PayPal option won’t load

**Comment by Sirvijver** [comment]
Hello @tharteveld26 

I think this issue might be related to a support request that we handled via this [.org thread](https://wordpress.org/support/topic/version-2-0-3-issue/#post-16562394). Please see if that can help you resolve the issue.

If this is not related to that caching issue, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. I will mark this thread as closed, since we don't provide support via GitHub (only development activities are recorded here).

Kind regards, 
Joost
