### ISSUE TITLE
Error message displayed to customers during checkout

### ISSUE THREAD

**Issue by neo-con** [woocommerce/woocommerce-paypal-payments#1281]
### Describe the Bug

When a customer attempts to checkout, they receive an unfriendly and complex error message related to PayPal payment processing. The error message should be user-friendly and easily understood by the customer.

### To Reproduce

Go to the WooCommerce store as a customer
Add items to the cart
Proceed to the checkout page
Fill in the required information and choose PayPal as the payment method
Click on the 'Place Order' button (authorized mode)
See the error message

### Expected Behavior

The customer should see a user-friendly error message that informs them there was a problem processing the payment and to try again or contact the shop admin for assistance.

### Actual Behavior

The customer sees a complex error message that includes technical details, which can be confusing:

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYER_CANNOT_PAY PayPalGateway.php:525 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYER_CANNOT_PAY OrderEndpoint.php:406 Order status changed from Pending payment to Failed.

### Environment

WordPress Version: 5.9.5
WooCommerce Version: 6.9.3
Plugin Version: 2.0.3
Browser: N/A (assuming issue occurs in all browsers)
Other plugins installed: N/A (assuming issue occurs with or without other plugins)

### Additional Details

Update the error handling code to display a generic user-friendly message such as: "Failed to process the payment. Please try again or contact the shop admin for assistance."

**Comment by myclassicparts** [comment]
I have the same issue and cannot find the solution

**Comment by Sirvijver** [comment]
Hello,

we have created an improvement request on this error message. Since this is not a payment affecting issue, this might take some time before picked up and resolved, so please be patient for the solution to become available.

Kind regards, 
Joost

**Comment by myclassicparts** [comment]
Dear Joost,
Thank you for your reply. Actually, this was an error affecting the payments and no payments could be made because of this error.

That's for your information.
Thank you



Mauricio Azar
Founder & CEO, MY Classic Parts

Website:     www.myclassicparts.com<http://www.myclassicparts.com>

Email:          ***@***.******@***.***>

Whatsapp: +971 58 58 28 918<https://wa.me/message/BT77FHVAZPQLK1>


Mailing address:

Madinat Badr, Qamar 4, 110

Muhaisnah 1, Dubai - UAE

________________________________

**Comment by Sirvijver** [comment]
Hello @myclassicparts 
yes, but the error is not caused by our plugin, but by the payment option that the customer is using. If you want to get more details on why the payment was declined, please reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport). They will be able to give you back-end details about the failed transaction. Please be sure to provide them with the Transaction ID and possibly the Debug ID (that you can find in the logs fi you activate it).

The only action we can take is on the error message improvement.

Kind regards, 
Joost

**Comment by myclassicparts** [comment]
Thank you again for a reply.

I reached out by email and through phone call and they confirmed that as per PayPal nothing was an issue for all the failed transactions. They confirmed that the issue was the website itself as a result the plug in for the payment and asked me to check with you instead.

Thank you


Mauricio Azar
Founder & CEO, MY Classic Parts

Website:     www.myclassicparts.com<http://www.myclassicparts.com>

Email:          ***@***.******@***.***>

Whatsapp: +971 58 58 28 918<https://wa.me/message/BT77FHVAZPQLK1>


Mailing address:

Madinat Badr, Qamar 4, 110

Muhaisnah 1, Dubai - UAE

________________________________

**Comment by Sirvijver** [comment]
Hello @myclassicparts 

I checked with my team, but they agreed that PAYER_CANNOT_PAY is not a plugin problem. However, usually it is also not a technical problem, so the MTS may say that it is not their problem. We think this is something for the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) might be able to help you with if it happens to all potential buyers.

In any case, this is not a development case and should not be opened in GitHub. If you need our continued support, you can [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. 

Kind regards, 
Joost

**Comment by myclassicparts** [comment]
The error was not payer cannot pay.

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-CITY_REQUIRED

Thank you


Mauricio Azar
Founder & CEO, MY Classic Parts

Website:     www.myclassicparts.com<http://www.myclassicparts.com>

Email:          ***@***.******@***.***>

Whatsapp: +971 58 58 28 918<https://wa.me/message/BT77FHVAZPQLK1>


Mailing address:

Madinat Badr, Qamar 4, 110

Muhaisnah 1, Dubai - UAE

________________________________

**Comment by myrandomtips** [comment]
I have been getting same thing some orders seem ok other seem to get this:

2023-03-19T00:04:00+00:00 CRITICAL Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. in /home/grasslan/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:455
Stack trace:
#0 /home/grasslan/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/Endpoint/ReturnUrlEndpoint.php(64): WooCommerce\PayPalCommerce\ApiClient\Endpoint\OrderEndpoint->order()
#1 /home/grasslan/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-wc-gateway/src/WCGatewayModule.php(240): WooCommerce\PayPalCommerce\WcGateway\Endpoint\ReturnUrlEndpoint->handle_request()
#2 /home/grasslan/public_html/wp-includes/class-wp-hook.php(308): WooCommerce\PayPalCommerce\WcGateway\WCGatewayModule::WooCommerce\PayPalCommerce\WcGateway\{closure}()
#3 /home/grasslan/public_html/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#4 /home/grasslan/public_html/wp-includes/plugin.php(517): WP_Hook->do_action()
#5 /home/gra in /home/grasslan/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php on line 455

**Comment by dakman** [comment]
we are having this problem and it also is leading to duplicate orders... and orders with no customer/shipping addresses.. very weird

**Comment by Aennemel** [comment]
I have exactly the same problem!
since yesterday, the orders are no longer going through correctly. Order numbers are assigned, but without data. The order with Paypal is correct, the money is also received on my Paypal account.
After a few minutes, another doubled order be created. This includes the data, but the order is set to "failed".
No automatic emails will be sent afterwards. Neither to the customer nor to me. The e-mails cannot be sent manually from the order either.
Please fix this problem asap.

**Comment by neo-con** [comment]
@dakman @myrandomtips @Aennemel , you guys should open separate issue tickets, as this original issue is based on non-friendly error messages.

**Comment by InpsydeNiklas** [comment]
Hi @neo-con, thanks for the feedback, and apologies for the noise. Many API errors already result in a rather generic error, but the team is working on improving more front-end error messages, as some of them certainly could be more user-friendly. We hope to include some of the improved errors in the upcoming update.

But everyone else who is encountering any problems, please [reach out to the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for more guidance on how to deal with eventual errors, as this GitHub issue is not the right place to discuss eventual problems you encounter. Thanks!
