### ISSUE TITLE
woocommerce-paypal-payments 

### ISSUE THREAD

**Issue by peterkuch** [woocommerce/woocommerce-paypal-payments#1283]
After intergrade with Paypal i try both business , personal account with  Wordpress  and woocommerce-paypal-payments  both latest.
 
- Testing it's working fine with login with PayPal testing account
- live: not working -> We aren't able to process your payment using your PayPal account at this time. Please go back to merchant and try using a different payment method.

I don't how i can know the problem. Please kindly help me. 
<img width="506" alt="Screen Shot 2023-03-27 at 1 03 23 PM" src="https://user-images.githubusercontent.com/14107698/227907710-8683fae5-67d4-46d1-8b97-39efb0143d76.png">
<img width="846" alt="Screen Shot 2023-03-27 at 4 46 30 PM" src="https://user-images.githubusercontent.com/14107698/227907996-df4b170d-29ac-4782-b13a-edca231b9fb3.png">

**Comment by Sirvijver** [comment]
Hello @peterkuch 

This does indeed look like an account issue, since the sandbox accounts did seem to function.
I can only advise you to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) that can take a look into your account and tell you if there is anything wrong with it (and possibly correct it).

If they tell you that this is an issue with the plugin, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We only use the GitHub platform for development cases, and this is a support request. We will close this thread now.

Kind regards, 
Joost
