### ISSUE TITLE
403 forbidden

### ISSUE THREAD

**Issue by Alavi-Sadaf** [woocommerce/woocommerce-paypal-payments#1285]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>
![image](https://user-images.githubusercontent.com/104481461/228216638-3f2871d5-9072-475d-b133-e5aff631e657.png)

**Comment by Sirvijver** [comment]
Hello @Alavi-Sadaf 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error, you have shown, seems to be caused by your account details not being correct. I would suggest you to disconnect and onboard the account once again. You might inadvertently change the account details in the connection tab and this causes an access issue now. 
If this does not help you resolve this issue, please open a support thread as mentioned above on the support platform and provide us more details about this issue for us to help you resolve this issue.

Kind regards, 
Joost
