### ISSUE TITLE
Won't Connect Account

### ISSUE THREAD

**Issue by TransMediaFox** [woocommerce/woocommerce-paypal-payments#1288]
### To Reproduce

1. Go to 'Woocomerce PayPal Payments Plugin'
2. Click on 'Active'
3. Window pops up for login or create an account
4. Click on 'login'
5. Fill out biz info that isn't auto-populated from Paypal
6. Says logging in and adding products...
7. Says complete and gives option to go back to woocommerce or set up payout method
8. Click on "Return to Woocomerce"
9. Goes back to plugin page where it says plugin needs actived.
10. Get really mad.

</details>

**Comment by Sirvijver** [comment]
Hello @TransMediaFox 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There are some things you can do to try to get your account onboarded successfully:
1. Take your time. When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.
2. Another plugin can be blocking the onboarding process. You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.

The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input).

If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards,
Joost
