### ISSUE TITLE
Notification to complete seutp showing when plugin deactivated

### ISSUE THREAD

**Issue by avviano** [woocommerce/woocommerce-paypal-payments#1300]
### Describe the Bug

The notification within WordPress to complete the Paypal setup keeps coming back, even though: 

1.) I have closed the notification multiple times and
2.) The plugin is deactivated in Woocommerce settings

This in-your-face notification that cannot be removed other than deinstalling the plugin is a real nuissance. Why does this notification keep coming back? Why is it so obnoxious? Whats the point of making it so persistant? It really feels like a bug. 
 
### To Reproduce

1. Install the plugin
2. Deactivate the plugin (in WooCommerce settings)
3. try to remove notificatoin
4. Notification keeps coming back
5. Blood pressure rises to dangerous levels and causes people to get sick because of it.

**Comment by InpsydeNiklas** [comment]
Hi @avviano 
I apologize for the inconvenience you're experiencing with the persistent notification. While it's possible that this could be a bug, it's more likely related to caching on your end because PayPal Payments does not display any notices when disabled.

To help resolve this issue, please try clearing your website's cache, including any caching plugins and server-side caching, if applicable.
In any case, if the problem persists, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
