### ISSUE TITLE
PayPal activation issue

### ISSUE THREAD

**Issue by AA1855** [woocommerce/woocommerce-paypal-payments#1307]
After logging in and completing the account verification, I am always stuck in a state where I cannot continue to click. I hope to receive a reply in the mailbox as soon as possible.
Image address: https://i.postimg.cc/6QMp4J9v/QQ-20230413230434.png

**Comment by Sirvijver** [comment]
Hello @AA1855 

Once the popup for onboarding your account has opened, the process is handled from the PayPal server side, not the plugin. We have no control over what is displayed and how this is handled. In order to get answers on this, I would advise you to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to take a look and advise you further.

It does look like there is an issue with reCAPTCHA, so you might want to try with another browser or system and see if there might be local security settings avoiding you from completing this process.

If you need more guidance from us, I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report as the team is happy to look into this for you. Thanks!
