### ISSUE TITLE
Paypal buttons constantly loading on checkout page

### ISSUE THREAD

**Issue by treads164** [woocommerce/woocommerce-paypal-payments#1332]
### Describe the Bug

At the checkout page, the paypal buttons are not loading.

### To Reproduce

1. Go to treads164.com
2. Add a random item to cart
3. Proceed to checkout
4. See error of Paypal buttons constantly loading on the checkout page

### Screenshots

Screenshot of constantly loading Paypal buttons
![image](https://user-images.githubusercontent.com/131095334/232643324-518ec6b1-b6bf-4b6f-8465-5620e60df256.png)

### Expected Behavior

The paypal buttons should load to completion and will be able to click through to the Paypal website

### Actual Behavior

Right now, it is in constantly loading mode and is unclickable

### Environment

 - WordPress 6.2 & PHP 7.4
 - WooCommerce Version 7.6.0 
 - Plugin Version 2.0.4
 - Browser Chrome Ver. 112.0.5615.86 (Official Build) (64-bit)

</details>

**Comment by Sirvijver** [comment]
Hello @treads164 

It looks like something is blocking our JavaScript from finalizing the button placement on this page. My first guess would be that another plugin is blocking this action from finalizing, but you can only verify this by doing conflict testing. In order to perform a full conflict, we recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

Because we only use this site for development activities (and not support requests), I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance, as the team is happy to look into this for you. Thanks!
