### ISSUE TITLE
Can't be activated - fatal error linked to woocommerce log

### ISSUE THREAD

**Issue by TomEbeyer** [woocommerce/woocommerce-paypal-payments#1335]
### Describe the Bug

Trying to activate plugin. Fatal error: Declaration of WooCommerce\WooCommerce\Logging\Logger\WooCommerceLogger::emergency($message, array $context = []) must be compatible with Psr\Log\LoggerInterface::emergency(Stringable|string $message, array $context = []): void in /wp-content/plugins/woocommerce-paypal-payments/modules/woocommerce-logging/src/Logger/WooCommerceLogger.php on line 23

### Environment

 - WordPress Version 6.2 
 - WooCommerce Version 7.6
 - Plugin Version 2.0.4 & 2.0.3

Other plugins
- WooCommerce Subscriptions
-  FunnelKit & Automations
- Elementors / Pro

</details>

**Comment by Sirvijver** [comment]
Hello @TomEbeyer 

We have not received this report before, so we would expect this is something that occurs only on your environment and is possibly caused by a plugin conflict. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). 

This thread will be closed, because we only use this site for development activities (and not support requests). I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly with a copy of your WooCommerce system report for more guidance, as the team is happy to look into this for you. Thanks!
