### ISSUE TITLE
payment failed paypal plugin

### ISSUE THREAD

**Issue by TECHNOLOGYSPAREPARTS** [woocommerce/woocommerce-paypal-payments#1347]
payment failed paypal plugin
connection is correct. 
Subscribed webhooks successful. 
Webhook simulation successful. 
however all our orders are receiving this. 

### Describe the Bug
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-SHIPPING_ADDRESS_INVALID PayPalGateway.php:525 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-SHIPPING_ADDRESS_INVALID OrderEndpoint.php:327 Order status changed from Pending payment to Failed.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @TECHNOLOGYSPAREPARTS 

Thank you for reaching out to us, we will give you a response to this request, but must advise you to reach out to our support team via another platform, since we only perform development activities on GitHub. You can reach out to our support team using these instructions:  https://paypal.inpsyde.com/docs/request-support/

The SHIPPING_ADDRESS_INVALID error is often seen when a 3rd party plugin is used that can alter the billing details. You can often find out what plugin this is by performing a full conflict test. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If you open a support thread with us, please don't forget to provide us the system report, so we can take a look and give you a better response. For now we will close this thread.

Kind regards, 
Joost
