### ISSUE TITLE
WooCommerce Checkout Block Support

### ISSUE THREAD

**Issue by captaincourageous** [woocommerce/woocommerce-paypal-payments#1348]
Plugin is not supported by WooCommerce Block Checkout.
WooCommerce has stopped building on their older checkout.

Is this plugin developed by Paypal or Woocommerce? Is it being developed at all? 

It has been 2+ years that block checkout support has been a top priority. 

Others have noted the 'steps' to reproduce and all but simply put: once installing the very clean and user friendly block checkout, WooCommerce gives a message that Paypal Payments is not supported by block checkout. 

As it seems that the block system is the direction of all Wordpress development, I am wondering when we can _realistically_ expect Paypal Payments to be available in the block checkout.

**Comment by Sirvijver** [comment]
Hello @captaincourageous 

Currently, we are working hard to get this feature added to the plugin. The option should become available in the next release, but it might not be an openly advertised option, and you might need to activate the option in the next release(s) before it become available in the settings.
One of the adjustments is being worked via [this thread](https://github.com/woocommerce/woocommerce-paypal-payments/pull/1346) and there are more to follow.
I see that there is already some documentation available for this in the GH wiki: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews#how-to-test-woocommerce-blocks-with-paypal-payments

Please keep an eye out for the next release and review the linked page provide above if you want to start using when it becomes available. If you have any more questions, I would advise you to [open a support request with us via this support tool](https://paypal.inpsyde.com/docs/request-support/), because we don't provide support via GH, but only do our development activities here. This is why I will close this thread for now.

Kind regards, 
Joost
