### ISSUE TITLE
It says it is possible to exclude Pay Later, but the option to hide it isn't there but users can use it.

### ISSUE THREAD

**Issue by itsKingBoa** [woocommerce/woocommerce-paypal-payments#1352]
### Describe the Bug

It says it is possible to exclude Pay Later, but the option to hide it isn't there but users can use it.

**Comment by Sirvijver** [comment]
Hello @itsKingBoa 

Thank you for reaching out to us, even though we do not provide plugin support via GitHub, I will give you a quick response on this and advise you to [open a support thread with our support team if you need further assistance](https://paypal.inpsyde.com/docs/request-support/).

There is only one option in our settings to avoid the Pay Later option to show up. This option can be found in the plugin settings under the tab "Pay Later". Here you will get the options shown for enabling/disabling the Pay Later functionality. The fields will be greyed out if you have "Vaulting" activated in the tab "Standard Payments", so if they show up, and you can't adjust it, you might want to temporarily deactivate vaulting in order to verify the settings in the "Pay Later" tab.

These settings have changed in a previous release, so we do understand this can be a bit confusing.

Please reach out to our support team if you require additional support from us.

Kind regards, 
Joost
