### ISSUE TITLE
Currency issue on Woocommerce paypal payments version 2.0.4

### ISSUE THREAD

**Issue by 22wpexpert** [woocommerce/woocommerce-paypal-payments#1368]
Hi 

Woocommerce paypal payments(2.0.4) showing currency error in console.
"Expected currency from order api call to be USD, got GBP. Please ensure you are passing currency=GBP to the sdk URL".
Screenshot: https://prnt.sc/1BRwU1WGgH1G

This plugin works fine with version 2.0.2.

**Comment by InpsydeNiklas** [comment]
Hi @22wpexpert 
Most likely, this issue is caused by a currency switcher plugin.
Please get in touch with the support team directly [from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a copy of your WooCommerce system report so we can provide further assistance.
Thanks!
