### ISSUE TITLE
No se pudo recuperar el pedido. Puede que no esté admitido este navegador. Por favor, inténtalo de nuevo con un navegador distinto.

### ISSUE THREAD

**Issue by CantuBMG** [woocommerce/woocommerce-paypal-payments#1372]
### To Reproduce

1. try to make a payment with paypal integration
2. once you put all the data and go to finish the payment
3. error pops up : No se pudo recuperar el pedido. Puede que no esté admitido este navegador. Por favor, inténtalo de nuevo con un navegador distinto.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/35573837/946a6c1f-63d9-4fab-968b-

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/35573837/5e2dab62-4a40-40b7-8562-25031ac1344c)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @CantuBMG 
This error could be caused by various potential issues: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors#could-not-retrieve-order
Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
