### ISSUE TITLE
Checkout Page Error in WordPress Website

### ISSUE THREAD

**Issue by sherilicious7844** [woocommerce/woocommerce-paypal-payments#1376]
INVALID_STRING_LENGTH The value of a field is either too short or too long.
INVALID_PARAMETER_SYNTAX The value of a field does not conform to the expect

![Screenshot 2023-05-15 045525](https://github.com/woocommerce/woocommerce-paypal-payments/assets/133659459/e4a0342a-bce7-4d2f-87cd-df6c1af3aad3)
 PayPal Payment Gateway

**Comment by Sirvijver** [comment]
Hello,

Thank you for reaching out to us, however, the GitHub interface is only used by us for development; not for support. Because of this, I will ask you to open a support thread on [another site](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for continued support.

There are some quick hints I can give you on this error:
- It could be that your PayPal account details are not saved correctly, and it could be a solution to disconnect and onboard your PayPal account again via our plugin settings tab "Connection".
- Another possible cause is that a 3rd party plugin is causing issues with our plugin, causing this error. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

See if any of these 2 options help you resolve this issue, and reach out to our support team to open a new thread if you need additional support. For now, we will close this thread.

Kind regards, 
Joost
