### ISSUE TITLE
paypal payment button not displaying at checkout

### ISSUE THREAD

**Issue by saheyi** [woocommerce/woocommerce-paypal-payments#1387]
### Describe the Bug
i add paypal gateway but the paypal button will not appear at checkout it will just keep loading

### To Reproduce

1. Go to '…'checkout
2. Click on '…'pay via paypal
3. Scroll down to …'the button

### Expected Behavior
it should dispaly the payment button

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @saheyi 

we only use GitHub for development activities, and this thread is clearly a support request. Please [open a support thread with our support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) in case you need additional support.

The issue you are facing is most likely caused by a situation where the JavaScript that replaces the WooCommerce with our PayPal smart button is being blocked. We would expect that another plugin is blocking this JavaScript and you can confirm this and find by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

Please open the support ticket if you still require our support.

Kind regards, 
Joost
