### ISSUE TITLE
PayPal Refund not working

### ISSUE THREAD

**Issue by Chucks1860** [woocommerce/woocommerce-paypal-payments#1389]
### Describe the Bug

Refund action does not work

### To Reproduce

1. Go to an order
2. Click on Refund
3. Set the articles to refund
4. Click on "Refund #xx,xx € via PayPal"
5. See error

### Expected Behavior

Expected was a positive response and an automatic refund of the transaction.

### Actual Behavior

We've just tried to refund a PayPal transaction but there was an error message popping up saying "An error occurred while attempting to submit a refund to the relevant payment method's API.".
We've tried again for a few times, always ending up getting that popup message.
After a few attemps it's just not responding at all, neither popup nor other action.
Just the loading animation is showing infinitely.

### Environment

 - WordPress Version 6.2
 - WooCommerce Version 7.7.0
 - Plugin Version 2.0.4
 - Browser Opera GX 98.0.4759.39
 - FooEvents for Woocommerce 1.18.14 & FooEvents Bookings 1.5.23

</details>

**Comment by Sirvijver** [comment]
Hello,

Thank you for reaching out to us, however, we do not provide plugin support via this site and would advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. This support request will be closed.

The issue you raised can be caused by different reasons, and I would advise activating logging and checking the logs for additional details when this fails again (or when you test it again).
One common cause for this issue is that the webhooks are not fully functional, and you might need to resubscribe the webhooks to resolve this issue. You can do this via the 2 buttons that are available within the plugin settings page under the tab "Connection". Here you can find the buttons "Simulate" and "Resubscribe" that can test and possibly correct the webhooks. Please use these buttons and see if that resolves the issue for you.

If this doesn't help resolve the issue, please open a new ticket with our support team, as explained before.

Kind regards, 
Joost
