### ISSUE TITLE
Failed to process the payment. UNPROCESSABLE_ENTITY

### ISSUE THREAD

**Issue by FrankWalle** [woocommerce/woocommerce-paypal-payments#1391]
### Describe the Bug
This is the error the customer gets:
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID

###Error inside the failed orders:
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID PayPalGateway.php:525 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID OrderEndpoint.php:327 

### Actual Behavior
At May 18th. 10:30 everything was ok. 
Now non PayPal payments are going thru the system, so we have to deactivate it at all.
There was no update and no changes of any configuration at all.

### Environment
- WordPress Version 6.2.1
- WooCommerce 7.70
- WooCommerce PayPal Payments 2.04

**Comment by Sirvijver** [comment]
Hello @FrankWalle 

The error DUPLICATE_INVOICE_ID error is a security feature from PayPal which aims to prevent accidental double-payments.

PayPal Payments automatically sets an "invoice prefix" and then sends the WooCommerce order numbers in the pattern "invoice prefix+ordernumber" to PayPal.
So when your prefix is set to "cfbdg-" and your order number is "123", PayPal Payments sends the invoice ID "cfbdg-123" to PayPal.

Now, when you restore a backup from your website, it is possible that the most recent WooCommerce orders do not exist anymore after the restore.
So as soon as WooCommerce attempts to create a new order with the number 123 and the same invoice prefix, PayPal would throw this error to prevent accidental double payments because there is already a payment at PayPal with the same invoice ID.
This feature can be disabled, though we usually recommend keeping it enabled. To disable it, follow these steps:

1. Log in to your Business PayPal account (https://www.paypal.com/businessmanage/preferences/payments)
2. Go to the Payments Preferences section
3. Under the "Block accidental payments:" section, select the option "No, allow multiple payments per invoice ID"

With this feature disabled, PayPal would no longer complain when you submit an invoice number that already exists in the system.


We actually don't use the GitHub site for support request, so if you have any more questions regarding this situation, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We will close this request.

Kind regards, 
Joost
