### ISSUE TITLE
Woocommerce Paypal "Could not retrieve order."

### ISSUE THREAD

**Issue by APapa2023** [woocommerce/woocommerce-paypal-payments#1393]
### Describe the Bug

At the end of my order process in my Woocommerce shop i always get the message 
"Could not retrieve order. This browser may not be supported. Please try again with a different browser." when im trying to pay with paypal. The website is https://herzblattpapier.de/. I used Chrome / Firefox newest Versions. The Woocommerce and Woocommerce payment plugins are updated. The PayPal Account is connected with a running business Paypal Account

Thanks for your support.
### Screenshots

<img width="1181" alt="Bildschirmfoto 2023-05-20 um 20 02 44" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/121669254/b0513a06-5ea1-4989-a0aa-62840f49eca7">

 - WordPress Version 6.2.2
 - WooCommerce Version 7.7.0
 - Plugin Version
 - Browser Chrome / Firefox

The PayPal Account ist connected with a running business Paypal Account

**Comment by Sirvijver** [comment]
Hello @APapa2023 ,

Thank you for reaching out to us, we will give you a response here, but in case you need additional support we advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. The GitHub site is only used by our developers team, not by support.

The error you have encountered is caused when the customer presses the WooCommerce button instead of the PayPal button. In some instances, the customer uses a browser that does not support the JavaScript that replaces the WooCommerce button with the PayPal Smart Button and this will lead to the error you saw. This is why we advise using another browser and try again.

Please consider [reaching out to the plugin support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need further assistance. Thanks!
