### ISSUE TITLE
Bug: MISSING_SHIPPING_ADRESS/ SET_PROVIDED_ADDRESS

### ISSUE THREAD

**Issue by torbenhietel** [woocommerce/woocommerce-paypal-payments#1395]
### Describe the Bug

Bei Bestellungen kommt der im Title beschriebene Fehler. Gibt es Probleme mit DIVI? Wie ist der Bug-Fix?
Bug: MISSING_SHIPPING_ADRESS/ SET_PROVIDED_ADDRESS

### To Reproduce

1. Eingabe der Daten in der Kasse, alle Felder befüllt. 
2. Bezahlen über Paypal
3. Fehler kommt. 

Versionen:
Alles auf dem aktuellen Stand.

**Comment by Sirvijver** [comment]
Hello @torbenhietel 

We would like to help you, but with the provided details, we cannot do much. This issue could indeed be a problem with the DIVI theme, but you would need to test this. There are some other issues that can occur with similar errors.

I would advise you to open a thread with our support team, because on the GitHub site, we only do development and no support activities. This is why we will mark this thread as resolved. 
When you open this support thread, please include the system report and any logs if available. If not logs are available, you might want to activate the logging function in the plugin settings. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
