### ISSUE TITLE
Could not retrieve order. This browser may not be supported. Please try again with a different browser.

### ISSUE THREAD

**Issue by GeorgeGiagkos** [woocommerce/woocommerce-paypal-payments#1400]
### Describe the Bug

Could not retrieve order. This browser may not be supported. Please try again with a different browser

### To Reproduce

when i clicked the button to pay for the order and put my personal paypal' account, then it returns this error. 
I also received a message from my bank account that said: you have been charged... and the price of the order.

### Screenshots

![Image_20230522_132522_620](https://github.com/woocommerce/woocommerce-paypal-payments/assets/97463548/367801b8-d4f1-4ce5-aea6-796775b0872a)

### Expected Behavior

To return that the order has been placed 

### Actual Behavior

Could not retrieve order. This browser may not be supported. Please try again with a different browser.

### Environment

 - WordPress Version - 6.2.2
 - WooCommerce Version - 7.1.0
 - Plugin Version - 2.0.4
 - Google Chrome Version 113.0.5672.126
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @GeorgeGiagkos 

Thank you for reaching out to us, we will give you a response here, but in case you need additional support we advise you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. The GitHub site is only used by our developers team, not by support.

The error you have encountered is caused when the customer presses the WooCommerce button instead of the PayPal button. In some instances, the customer uses a browser that does not support the JavaScript that replaces the WooCommerce button with the PayPal Smart Button and this will lead to the error you saw. This is why we advise using another browser and try again.

Please consider [reaching out to the plugin support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if you need further assistance. Thanks!
