### ISSUE TITLE
I m facing this issue please help

### ISSUE THREAD

**Issue by dannyhelsing** [woocommerce/woocommerce-paypal-payments#1426]
I m facing this particular issue in receiving payments on my woocommerce website through paypal plugin.
Issue-
Order Notes : Could not retrieve order. This browser may not be supported. Please try again with a different browser. PayPalGateway.php:472 Order status changed from Pending payment to Failed

![123456789](https://github.com/woocommerce/woocommerce-paypal-payments/assets/135995369/286bb63c-ba68-49ca-bc25-3dacbb2be1fc)

,Please help me resolve this issue.
![123456789](https://github.com/woocommerce/woocommerce-paypal-payments/assets/135995369/93561960-bb9e-46f5-a5e8-24d9c7f23590)

**Comment by InpsydeNiklas** [comment]
Hi @dannyhelsing, This error most often occurs when the smart buttons did not load on the Checkout page to replace the "Place order" button. This could be caused by various issues such as unsupported browsers or errors on your site: https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Common-errors#could-not-retrieve-order
I suggest [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
