### ISSUE TITLE
I have a problem with the orders because they enter with an error!

### ISSUE THREAD

**Issue by HeavenWeb** [woocommerce/woocommerce-paypal-payments#1434]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version: <html>
<body>

6.2.2
--

</body>
</html>
 - WooCommerce Version
 - Plugin Version: WooCommerce PayPal Payments Versión 2.1.0 
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @HeavenWeb 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Since you did not provide any details, errors or logs, there is not much I can do to help you at this moment, so please open the support request as advised and add more details, so we can help you out straight away when we receive the support thread.

I will close this thread as it is not in the right place for support.

Kind regards, 
Joost
