### ISSUE TITLE
Cannot sign in with my account does not recognize my business is a business already created.

### ISSUE THREAD

**Issue by BarryMcMahonSH** [woocommerce/woocommerce-paypal-payments#1444]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by BarryMcMahonSH** [comment]
When clicking Activate PayPal it pops up a window and asks me to login or create an account then it automatically goes to create despite the fact that i am logged into PayPal on my business account already. So I know I have an account and the right login but PayPal within WooCommerece is not recognizing it.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/63667599/c5a6ad38-5341-4d43-b4b6-8610799e7586)
then...
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/63667599/3313109f-8ba7-4ca4-a92f-3c172e37f60e)
I am logged into payPal on my business account

**Comment by Sirvijver** [comment]
Hello @BarryMcMahonSH 
You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

However, the question you raised, seems to be an issue more related to your account and not the plugin. For this, I would advise you to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review your account and advise how to resolve this. The response you are getting is generated on the backend of PayPal servers, so our plugin does not really affect this message. MTS is the only way to get your account reviews and corrected in order to log into our plugin and get it connected.

Please reach out to the link above, if you believe you require our further assistance/support. This thread will be closed.

Kind regards, 
Joost

**Comment by BarryMcMahonSH** [comment]
Joost,

Thank you. I think you are correct. After several attempts where PayPal gave me a screen that would not populate with my login ID and did not recognize my email, I got lucky and guessed the corporate password over the weekend when the CFO wasn't working.
;) ty!
