### ISSUE TITLE
Woo Commerce Paypal Payments plugin is not working. It just prevents my site from loading.

### ISSUE THREAD

**Issue by Sunil-Learns-Javascript** [woocommerce/woocommerce-paypal-payments#1445]
After updating the plugin, my website could not load at all. It just shows as critical error.

This is the bug that was highlighted to me by my website host.

PHP Fatal error: Uncaught TypeError: Return value of WooCommerce\PayPalCommerce\Button\Assets\SmartButton::intent() must be of the type string, null returned in /home/dfxvceab/live.meanmuscles.com/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php:1434

Btw, this is my website url: https://www.meanmuscles.com.

My site only appears after I deactivate the WooCommerce Paypal Payments plugin.

My website is running on a wordpress platform. Its version is 6.2.2.
I'm currently using Firefox and Chrome browsers to access my wordpress panel.

Hope someone here can help me with this.

Appreciate it!

Thank You!

Regards,
Sunil

```[tasklist]
### Tasks
```

**Comment by Sirvijver** [comment]
Hello @Sunil-Learns-Javascript 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We did however see other people also report this situation and have a bug open for this case. There is also 1 GH thread open for this that we are using for our developers case (in case any development is needed for this case), that you can find [here](https://github.com/woocommerce/woocommerce-paypal-payments/issues/1439).

The merchants that reported this so far (2) have been able to resolve this issue by updating their theme and/or deactivating/activating the smart buttons of our plugin. I would advise you to also do this and update the other GH thread with your findings, since we will mark this one as a duplicate support request and close it.

If you need any specific support from our end, please open a private thread as advised above.

Kind regards, 
Joost

**Comment by Sunil-Learns-Javascript** [comment]
Hi Sirvijver,

Thanks for your suggestions. May I know how do I deactivate the smart buttons if that would help my issue please?

Thank You!

Regards,
Sunil

**Comment by InpsydeNiklas** [comment]
Hi @Sunil-Learns-Javascript,
You can disable the smart buttons from the `Smart Button Locations` setting in the Standard Payments tab from the plugin settings. I recommend removing all selected locations, saving the settings, then setting your locations and saving again.
https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-buttons
These steps at least helped some other users.

If any problems persist, please contact the support team directly with a copy of your WooCommerce system report: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
