### ISSUE TITLE
.

### ISSUE THREAD

**Issue by TIANightTeam** [woocommerce/woocommerce-paypal-payments#1446]

**Comment by Sirvijver** [comment]
Hello @Ectesso-Dev 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Since you have not provided any details on your site setup (for this, we would really need the system report), we cannot really review the problem or test anything. For this reason, I would like to ask you to open a new support thread via the link provided above and include the system report, so we can take a look.

When we have this engagement with requested details, we can take a look. I will close this thread, since we can't do much here with the information we have.

Kind regards, 
Joost
