### ISSUE TITLE
auto migrate_payment_tokens slows down website

### ISSUE THREAD

**Issue by rens23** [woocommerce/woocommerce-paypal-payments#1452]
### Describe the Bug

I updated the paypal payments plugin today. It seems that there is a feature which automatically migrates payment tokens for users.
I have 519000 users who have a meta_key ppcp-vault-token with meta_value a:0:{} . For each of those users a action is created in the database . It seems that this is not a fast process at all. There is no way to stop this since the whole website timesout for me. After about 30 minutes only 3% of the users is scheduled. I now have to crash the plugin by changing the files via ssh. 

Please give me an option to do this manually or filter the users with a blank meta_value first before scheduling them.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by weroh** [comment]
Hey could you do me a favor and check your action scheduler? If it crashes in wp-admin, try going into mysql and see if it's doing this same thing for you. 

We have 40 million records in action scheduler with the hook 'woocommerce_paypal_payments_payment_tokens_migration' and it seems like it's related to this latest update. Our plugin was updated 5 days ago (2023-06-18). It's definitely bogging us down. The rest of the action scheduler items in the table have less than 1000 entries. So this is a massive outlier.

**Comment by weroh** [comment]
@rens23 Really interesting clue. Thank you for sharing. We also have about 600 users and every single one of them has 'ppcp-vault-token' = "a:0:{}"

add_action('woocommerce_paypal_payments_payment_tokens_migration', ....) starts at line 192
/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-vaulting/src/VaultingModule.php

And the related as_schedule_single_action() starts at line 249 


The as_schedule_single_action() call seems to indiscriminately add this schedule hook. Check it out.

First the query...
```
		$customers = new WP_User_Query(
			array(
				'fields'   => 'ID',
				'limit'    => -1,
				'meta_key' => 'ppcp-vault-token',
			)
		);
```

And it creates a scheduler item for each customer with this token without checking if it's empty. This is probably where you want to create some workaround if you're interested. Personally, I'm going to comment this thing out and clear out the DB since none of our customers have tokens.

```
		foreach ( $customers as $id ) {
			/**
			 * Function already exist in WooCommerce
			 *
			 * @psalm-suppress UndefinedFunction
			 */
			as_schedule_single_action(
				$timestamp,
				'woocommerce_paypal_payments_payment_tokens_migration',
				array( 'customer_id' => $id )
			);

			$timestamp += $interval_in_seconds;
		}
```

**Comment by weroh** [comment]
I have a hard time leaving hacks in production. So I had ChatGPT help me write a legit patch real quick. It just checks if the key is empty when unserialized. 

Start at line 242 of /woocommerce-paypal-payments/modules/ppcp-vaulting/src/VaultingModule.php
```
		foreach ( $customers as $id ) {

			// End of Workaround to check if ppcp-vault-token is empty or not
			$customer = new WC_Customer( $id );
			$token    = $customer->get_meta( 'ppcp-vault-token', true );
			$unserialized_token = maybe_unserialize( $token );

			if ( empty( $unserialized_token ) ) {
				continue;
			}
			// End of Workaround

			/**
			 * Function already exist in WooCommerce
			 *
			 * @psalm-suppress UndefinedFunction
			 */
			as_schedule_single_action(
				$timestamp,
				'woocommerce_paypal_payments_payment_tokens_migration',
				array( 'customer_id' => $id )
			);

			$timestamp += $interval_in_seconds;
		}
```

Or if you just want the whole file that I'm using.

Plugin Name: WooCommerce PayPal Payments
Version:     2.1.0

* Use at your own risk. I've carefully examined this code, but I haven't tested this yet.

[VaultingModule.php.txt](https://github.com/woocommerce/woocommerce-paypal-payments/files/11832633/VaultingModule.php.txt) (Rename to VaultingModule.php)

**Comment by rens23** [comment]
Hi @weroh , I also had the issue of millions of scheduled actions which slowed everything down. My solution was to just delete all those scheduled actions manually with mysql. Just like you I commented out the schedule single action . I am not that happy with the solution since I don't know if by not migrating we are missing something.

What I don't understand is why it creates so many actions, I have 500k users why would it create multiple millions of that. I suspect that it the migration function doesn't check if it there is already a migration function running, only if it is already finished. So there are many many processes started which run this function which in turns creates an enormous amount of scheduled actions.

I am surprised not more people are complaining about this.

**Comment by InpsydeNiklas** [comment]
Hi there, thanks for sharing your findings, and apologies for the trouble.
Update 2.1.0 migrates the payment tokens to use the default WooCommerce payment token endpoint instead of the custom endpoint the plugin previously created. This token migration should normally only run once during the plugin upgrade.
If this creates too many scheduled actions (more than you have users), then probably because the migration routine was triggered multiple times, which normally should not happen by itself.
This can be seen from the plugin log files, in case `Logging` was enabled during the upgrade.

> And it creates a scheduler item for each customer with this token without checking if it's empty.

This should normally not be an issue as the key should is only meant to exist for users who have paid via PayPal Payments while the Vaulting feature was enabled. 
It's possible for the `ppcp-vault-token` meta_key to be empty, for example, when saving the payment method was attempted but it failed, or when the buyer at some point deleted the payment token.

> We also have about 600 users and every single one of them has 'ppcp-vault-token' = "a:0:{}"

Was the Vaulting setting maybe enabled while your PayPal account wasn't approved for Reference Transactions? In that case, every PayPal purchase (not ACDC) would result in an empty key.

But in most cases, it would still be desirable to run the token migration for empty keys as a new token is requested directly from PayPal.
This can help, e.g. when the buyer previously saved a payment method, but for some reason, the saved payment method was not communicated with the site (e.g. webhook didn't arrive). In that case, the meta_key would be empty, while there actually is a saved payment method in the Vault.
Running the migration for such users results in the plugin fetching a new token for the buyer to use on the website.

> I am not that happy with the solution since I don't know if by not migrating we are missing something.

Without the token migration, users will not see their saved payment methods from the `My Account > Payment methods` section.
Subscription renewal payments for existing subscriptions should continue to work as usual regardless.
So users only lose the ability to delete the token or select a default one for subscription renewals.

> I am surprised not more people are complaining about this.

So far we are aware of about five reports total where the migration was executed too many times.These certainly won't be the last ones, but if this was more widespread there would be more reports already.
In any case, the team is looking into improving the token migration logic to prevent it from running multiple times.

Is it possible one of you is using some kind of autoscaling WP implementations that spin up new instances depending on the demand?
Thanks!

**Comment by weroh** [comment]
> What I don't understand is why it creates so many actions, I have 500k users why would it create multiple millions of that

@rens23 Yeah that is so weird isn't it? Our site has 1/1000th the user base you do and we have 40 million records. ChatGPT and I wrote a script to delete all of those records. It took 5 hours to delete 10 million records lol. So in case any else comes across this, it is WAY faster to just copy the rest of the table to a new one and then delete the old one.

The copy query

```
INSERT INTO wp_actionscheduler_actions_DEST_TABLE
SELECT * FROM wp_actionscheduler_actions
WHERE hook != 'woocommerce_paypal_payments_payment_tokens_migration';
```

> Is it possible one of you is using some kind of autoscaling WP implementations that spin up new instances depending on the demand?

Almost certainly not us. We're just a WooCommerce store that gets about 6k unique views per day. It is on WPEngine so if there's anything like that happening, then it's happening without my knowledge.

> ...buyer previously saved a payment method, but for some reason, the saved payment method was not communicated with the site (e.g. webhook didn't arrive)...

@InpsydeNiklas Thanks for your super detailed info! Good to know. I'm going to look into whether or not this applies to us. I've been dumped into this crisis last second. There were a bunch of other dudes working on this one earlier and no one else could figure out why the site was crashing so hard. If you need any diagnostic info, details, tests, etc. Please feel free to reach out as this is mutually beneficial and could help us get to another update faster.

**Comment by InpsydeNiklas** [comment]
For one reporter with ~2500 users, the migration process was executed more than 1000 times within a single day, resulting in almost three million scheduled actions. So depending on how long this goes undetected, the numbers may increase significantly. 

It is still not clear to us what would initiate these additional migrations, but there must be some kind of relationship with the upgrade routine getting triggered over and over again. This would also include actions such as resubscribing the webhooks, which could be observed from the plugin log files.

To solve the immediate issue of the migration running more than once, #1461 will add a flag to prevent subsequent runs of the migration.
The migration could then only be called manually with after the plugin triggered it once: `do_action('pcp_migrate_payment_tokens');`

Empty meta_keys would still be migrated for the above reasons (the token exists at PayPal but not in WC). 
It would be interesting for us to learn more about why 500k users have this meta_key, as our only explanation would be that they all performed a PayPal payment while the Vaultign feature was active.

But for us to learn more about your specific setups, we would appreciate it if you could [get in touch with our support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) and a copy of your WooCommerce system report and PayPal Payments log files, if available.
Thanks!

**Comment by InpsydeNiklas** [comment]
Following #1461, the migration will set an option called `ppcp_payment_tokens_migration_initialized` after initialization. This option must be deleted to rerun the migration at a later time.
Empty meta keys will now be skipped by default. To process the migration for empty meta keys as well, this filter must be added before initializing the migration: `add_filter( 'ppcp_skip_payment_tokens_empty_key_migration', '__return_false' );`

We would appreciate it if you could give it a try with [this package](https://drive.google.com/uc?export=download&id=1QZ1Rv_VtVHVU3jwQoyBnl1TH9nTSqaMD) and let us know if this resolves the previously reported issue with too many scheduled actions. Thanks!

**Comment by weroh** [comment]
After approval from the client, we are trying this today. Will report back. Thanks for the hotfix!

**Comment by InpsydeNiklas** [comment]
Thanks! As a heads-up, it appears this version provided above may still migrate empty meta keys, regardless of the filter result. This is being looked into, and will work as described in the next official update. 

But with this fix, we are not seeing any way for the migration to be triggered again once the flag is set. So the number of scheduled actions should be more reasonable.
The individual actions are executed with a five-second delay, so this process running once should not cause any slowdown, even when thousands of users are migrated. However, it may take a while to process half a million users. In a case like those reported by @rens23, waiting for a verified fix to skip empty keys may still be preferable. 

I'd also like to encourage @rens23 to open a [support ticket with the team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) so we can collect more information about your site. This may help us figure out why so many users would have this (empty) meta key, as normally this key should only be present when the buyer performed a PayPal payment while Vaulting is active.

**Comment by rens23** [comment]
@InpsydeNiklas
Apologies for the delay in answering.
We have a bit of a weird setup. Since the new paypal plugin didn't use the subscription function but only the reference transaction for subscriptions we haven't used it yet to process payments. It is enabled but we use the old paypal plugin from woocommerce.
The reason that I updated it was because of a vulnerability warning. I also read the update notes and it seems that subscriptions are now supported via non-reference transactions.
The vaulting is enabled on this paypal plugin but people are paying with the old paypal plugin. Perhaps that is causing issues.

Anyway, thanks for the update!

**Comment by InpsydeNiklas** [comment]
@rens23 Thanks for the feedback.

> I also read the update notes and it seems that subscriptions are now supported via non-reference transactions.

The latest update 2.1.0 includes an [experimental integration for PayPal Subscriptions](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Testing-features-previews) (processing subscription renewal payments without requiring Reference Transactions), but this is in an early stage and only meant for testing, not yet for production use.
The next update in mid-July will improve this experimental feature, and the goal is to release it with the following update in early August officially for everyone.

> The vaulting is enabled on this paypal plugin but people are paying with the old paypal plugin. Perhaps that is causing issues.

Thanks, we'll review the behavior in such cases. But it's still strange because if no payment is taken via PayPal Payments, the regular behavior is that no meta key would be created since this is only relevant for the payment process via Vaulting with PayPal Payments.
In any case, we'll try to let you know when there is a version that skips the empty meta keys.
