### ISSUE TITLE
visa payments for your paypal woocommerce plug in are not working, only mastercard 

### ISSUE THREAD

**Issue by winmyhome** [woocommerce/woocommerce-paypal-payments#1456]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @winmyhome 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

However, I will try to guide you in the right direction regarding the issue you are encountering:
Our plugin does not decide what card types are being accepted, this is done by PayPal. You can find some details on this situation here: https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/
It might be better to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review the situation, since they have access to the backend system of the transactions. When you encounter them, see if you can add a transaction ID, Debug ID or the time/date of the transaction attempt. This way they can help you straight away, and you won't lose any more time.

If they cannot help you with this, please open a support request with us, and we can take another look at your site and the logs. For now, we will close this thread, as we don't handle support requests via GitHub.

Kind regards, 
Joost
