### ISSUE TITLE
error 400

### ISSUE THREAD

**Issue by Baneado028** [woocommerce/woocommerce-paypal-payments#1459]
### Describe the Bug

https://www.paypal.com/sdk/js?client-id=AcxmAyzZqzGZRBnx6ZF3fI0i_eDmSuU2wcbM6_xUYCvHrPbYLXDlPHVvk1bGo0IRrJVkpHNk3_elyrWF&currency=ARS&integration-date=2023-06-02&components=buttons,funding-eligibility&vault=false&commit=true&intent=capture&enable-funding=venmo,paylater net::ERR_ABORTED 400

**Comment by Sirvijver** [comment]
Hello @Baneado028 

The currency you are using is not a PayPal supported currency. On [this page](https://developer.paypal.com/docs/reports/reference/paypal-supported-currencies/) you can find all the currencies that are supported. You can reach out to [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) if you want to discuss any options that are possible when you want to use the PayPal payment method.

If you have any more questions, please open a support request via [this link](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help), because we will close this thread, since we only perform development activities on GitHub.

Kind regards, 
Joost
