### ISSUE TITLE
Automatic Undesirable Refunds

### ISSUE THREAD

**Issue by RonBPalmer** [woocommerce/woocommerce-paypal-payments#1465]
### Describe the Bug
For some reason, not sure if PayPal or WooCommerce, my membership customers are being refunded, some for multiple months. This has never happened before using this new tool. I have a ticket open with WooCommerce but it is probably this tool. I see an option to manage webhooks but no option to selectively remove hooks. I don't want any automatic refunds of any kind ever. We have a business process to follow for that. 

The WooCommerce shopping cart subdomain is m.fixfamilycourts.com. The main site is www.fixfamilycourts.com. We have been in business well over a decade. 

I have no idea what is triggering this. I don't have any kind of refund form activated. We use our general contact form for refunds and process them manually. As far as I can tell, this action is random.

How can I turn off all automatic refunding?

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @RonBPalmer 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I believe this is not a normal "refund" as you describe it, but this might be a reaction of our tool to the situation where a subscription payment via our plugin was not able to vault the payment method on the PayPal server. ​The situation you are encountering is a known issue, let me try to explain what is happening.
​When a subscription is being purchased, there is a standard list of actions that occur:
​1) Payment is being authorized.
​2) Payment method is being vaulted/saved for future renewals.
​3) Payment is captured.
​
Point 2 is performed on the PayPal server and when this doesn't succeed, point 3 changes into "Payment get cancelled/void/refunded" by default. This is done, so that the renewals will always succeed. This issue is caused on the PayPal server, and we have been asking PayPal to get this corrected, but so far this has not been done yet. Since this time, we did create a setting that provides a workaround for this situation when vaulting the payment method fails.
​You can find this on the settings page, under the tab "Standard Payments" and is called "Subscription capture behavior if Vault fails". With this feature, you can choose to:
1. Fail the subscription purchase.
2. Capture the initial payment and set the renewal to manual. 
3. Capture the initial payment and ignore the failure.
​
​This setting should help you capture the initial payment, but the renewals will keep an issue, since the payment method was not vaulted.
​
​If you want to get investigated why the payment method was not saved, you will need to reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport), since the origin of this issue is not caused by the plugin, but on the PayPal server. However, we don't believe they will be able to help much and expect that this will only be resolved when PayPal releases their upcoming feature "Vault-v3", that will most likely resolve the vaulting issue.

If you have any further questions or want us to look closer into this issue, please open a support request via the link provided above. This thread will be closed.

Kind regards, 
Joost
