### ISSUE TITLE
Paymeny Problem

### ISSUE THREAD

**Issue by torlior** [woocommerce/woocommerce-paypal-payments#1467]
### Describe the Bug

The checkout buttons are not shown when we enable both card and paypal checkout

### To Reproduce

1. go to https://boyotag.com/product/test/?swcfpc=1
2. Add to cart and check out.
3. The buttons are not displayed.

### Screenshots

<img width="1314" alt="צילום מסך 2023-06-25 ב-11 37 30" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/58655955/f0ba0ac1-12ba-4d85-b70f-5ef96176ffa2">

### Expected Behavior

show the buttons

### Actual Behavior

buttons are not shown

### Environment

ALL LATEST VESRIONS
 - WordPress Version 
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @torlior 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I would expect (seeing your screenshot) that you are using the Standard Card Processing option (not the Advanced Card Processing). I have recreated the same situation on my testing environment, and I am seeing all the expected buttons on both the PayPal and Standard Card Processing options when I enable a separate payment gateway for the branded PayPal Debit or Credit Card button. I would expect that this feature is maybe getting blocked by another plugin and would advise doing standard [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) to see if any of your plugins or the theme is blocking these buttons.

If this does not help, please open a support thread via the intended interface in order to get our continued support.

Kind regards, 
Joost
