### ISSUE TITLE
Hosted field payment is already in progress

### ISSUE THREAD

**Issue by wrytxmedia** [woocommerce/woocommerce-paypal-payments#1470]
We are having issues with our checkout page where customers are entering the address and then it shows an error “Hosted Fields payment is already in progress'. 
This is with the Paypal plugin.
https://pasteboard.co/yMNkGQyCwBj7.jpg
https://pasteboard.co/GthfDWLj4WYJ.png

My website (Wordpress, plugins, themes) is updated.
WooCommerce PayPal Payments: Version 2.1.0
WordPress 6.2.2
Woocommerce 7.8.0

**Comment by Sirvijver** [comment]
Hello @wrytxmedia 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered is actually a known issue and is already being handled via this thread:
https://github.com/woocommerce/woocommerce-paypal-payments/issues/1011
I would suggest that you follow this thread, since this thread will be closed. If you want us to look closer into your specific situation, please open a support thread as described above.

Kind regards, 
Joost
