### ISSUE TITLE
Failed payments

### ISSUE THREAD

**Issue by artincoins** [woocommerce/woocommerce-paypal-payments#1477]
### Describe the Bug

Customers placing orders through my Woocommerce retail website results frequently in failed payment.  Somewhat recent issue, perhaps first appearing 2 - 3 months ago.

### Error message in admin:

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-CANNOT_MIX_CURRENCIES PayPalGateway.php:573 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-CANNOT_MIX_CURRENCIES OrderEndpoint.php:577 Order status changed from Pending payment to Failed.

### Environment

 - WordPress Version:  Unknown
 - WooCommerce Version:  6.2.2
 - Plugin Version:  2.1.0
 - Browser [e.g. Chrome, Safari] and Version
30+ plugins

### Additional Details

Thank you for your kind assistance / guidance

Michael
Art in Coins
artincoins.com

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hello @artincoins,

Your issue seems to point toward a misconfiguration related to your currency switcher plugin. The problem appears to arise when the currency displayed on your Checkout page doesn't align with the currency selected through the switcher.

To break this down: PayPal's button script is picking up the currency defined by your currency switcher, as it should. However, the Checkout page seems to consistently display prices in `C$` regardless of the chosen currency.
This discrepancy triggers PayPal to return a currency mismatch error. For instance, if PayPal buttons are loaded with `USD` currency, but the Checkout page insists on showing `C$`, PayPal throws an error when clicking the button.

From this perspective, it seems like the PayPal Payments plugin is performing as expected, but the Checkout page isn't reacting to the currency switching.
As the next step, I'd suggest getting in touch with the support team for your currency switcher plugin. They should be best placed to guide you on how to ensure a smooth currency changeover on the Checkout page.

For any queries specifically regarding PayPal Payments, the support team is always ready to help. You can reach out to them directly [here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help). They'd be happy to provide further guidance.

**Comment by artincoins** [comment]
Warmest greetings from Montreal Niklas and thank you for the
exceptionally fast response and detailed analysis.

I believe the currency switcher is causing other issues in the admin so
your feedback is dovetailing nicely with the other problems I have
encountered recently.  We will definitely communicate this to the plugin
dev team and hopefully get it sorted out quickly.

Almost Friday, have a most enjoyable and healthy weekend ahead,

Michael
Art in Coins
