### ISSUE TITLE
Uncaught Error - Class 'PayPalGateway' not found

### ISSUE THREAD

**Issue by luke-key2creative** [woocommerce/woocommerce-paypal-payments#1484]
We got a fatal error email from Wordpress. Details are below.

Website is adhdwa.org
When seeking help with this issue, you may be asked for some of the following information:
WordPress version 6.2.2
Active theme: ADHDWA Theme (version 1.0.0) Current plugin: WooCommerce PayPal Payments (version 2.1.0) PHP version 7.4.33

Error Details (I have removed the private data fro the start of the below urls)
=============
An error of type E_ERROR was caused in line 52 of the file /wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php. Error message: Uncaught Error: Class 'WooCommerce\PayPalCommerce\WcGateway\Gateway\PayPalGateway' not found in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:52
Stack trace:
#0 /wp-content/plugins/woocommerce-paypal-payments/bootstrap.php(67): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->run(Object(WooCommerce\PayPalCommerce\Vendor\Dhii\Container\CachingContainer))
#1 /wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(75): {closure}
#2 /wp-content/plugins/woocommerce-paypal-payments/woocommerce-paypal-payments.php(90): WooCommerce\PayPalCommerce\init()
#3 /wp-includes/class-wp-hook.php(308): WooCommerce\PayPalCommerce\{closure}('')
#4 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)

**Comment by Sirvijver** [comment]
Hello @luke-key2creative 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). If you require our help in further checking this conflict, or you have other questions, please raise a new support request via the link provided above.

Kind regards, 
Joost
