### ISSUE TITLE
paypal button does not appear

### ISSUE THREAD

**Issue by anapacheco19** [woocommerce/woocommerce-paypal-payments#1488]
### Describe the Bug
the paypal button does not appear on my web page.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @anapacheco19 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You have not provided enough information in order for us to give a proper response. In the case where our button does not show up, we usually advise performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

There could also be an issue with the checkout page / page builder, so in that case you 
should test another checkout page that only contains the short code [woocommerce_checkout] to see if it shows the buttons and your current checkout page is using incorrect short codes. 

If you are using Elementor Pro, you might have an issue caused by our last update, and you need to use this package in order to correct this issue: https://drive.google.com/uc?export=download&id=1bJXF41hA_HQAMgR-KqVmR3iUfQT2ao_7


If you require additional support, please open a new support request via the provided link above.

Kind regards, 
Joost
