### ISSUE TITLE
Separate Card Button from PayPal gateway doesn't work. If I enable it, all checkout button of PayPal disappered.

### ISSUE THREAD

**Issue by digitaldesignerchemical** [woocommerce/woocommerce-paypal-payments#1494]
[](url)
<img width="607" alt="Screenshot 2023-07-07 alle 10 25 54" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/89586872/34ed125b-817c-4920-973d-9a2e6fd259a7">

**Comment by Sirvijver** [comment]
Hello @digitaldesignerchemical 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This is not a common behavior, so I would expect that this is caused by another plugin. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
.

If this does not help you isolate the cause of the issue and need additional support, please open a support thread via the link provide above. This thread will now be closed.

Kind regards, 
Joost
