### ISSUE TITLE
Issue 1. Can't activate PayPal in 3 - Issue 2. Hosted Fields payment is already in progress

### ISSUE THREAD

**Issue by AdelmoI** [woocommerce/woocommerce-paypal-payments#1495]

**Comment by InpsydeNiklas** [comment]
Hi @AdelmoI 
Following update 2.1.0, the Vaulting setting is only visible when the connected merchant is enabled for Reference Transactions.
If Pay Later cannot be enabled, this suggests that Vaulting was enabled before the update.
To disable it, you can either clear the plugin settings from the Connection tab or downgrade to version 2.0.5, disable Vaulting, then update again.

Regarding the `Hosted Fields payment is already in progress` message, this is unrelated to any potential payment failures and does not negatively impact the payment processing. This message may be visible when the Advanced Card Processing card fields were re-rendered before the form submission, e.g. due to an AJAX reload while being visible.

I'm not sure why the button preview alignment looks bad in your screenshots, though.

Please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. Thanks!
