### ISSUE TITLE
Lorsque je lancement un paiement ya un echec et on me demande de ressayer et l'operation se reproduit. Comment regler le problème svp

### ISSUE THREAD

**Issue by Abdala-source** [woocommerce/woocommerce-paypal-payments#1497]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Abdala-source 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The amount of details you have provided regarding this situation is insufficient for us to provide you with a correct response. We would need to know what you are doing, what you are seeing, and what the exact error is you get. Next to that, we would ask you to provide the system report and possibly the logs that this event generated (make sure you have logging activated in the plugin settings).

If this is related to onboarding your PayPal account to the plugin, there are some things you can do to try to get your account onboarded successfully:
- Take your time. When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.
- Another plugin can be blocking the onboarding process. You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.
The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input).

I will close this thread, so you can open a support thread via the provide link above.

Kind regards, 
Joost
