### ISSUE TITLE
payment problem paypal

### ISSUE THREAD

**Issue by abubakaradeel** [woocommerce/woocommerce-paypal-payments#1498]
I have added the PayPal method in WooCommerce but on the user side it is showing an error that (something went wrong)  plz help me

**Comment by Sirvijver** [comment]
Hello @abubakaradeel 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

In order to really help you out with this, we would need more information from your end, but this type of situation is usually best investigated by doing conflict testing. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you find the issue, and you require additional support, please open a support thread as described above. Be sure to add the system report and possibly the logs when you do. We will close this thread.

Kind regards, 
Joost
