### ISSUE TITLE
Can't update product images

### ISSUE THREAD

**Issue by omprakash6054** [woocommerce/woocommerce-paypal-payments#1517]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @omprakash6054 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The problem you raise here, is most likely not caused by our plugin. We do not have any effect on the images (that we know of). If you believe we do, then please open a thread via the link provided above and provide a bit more details why you think our plugin is causing this, and please also include the system report and any logs available for us to look at.

Kind regards, 
Joost
