### ISSUE TITLE
Buttom paypal payment bug

### ISSUE THREAD

**Issue by agenciavisual** [woocommerce/woocommerce-paypal-payments#1599]
### Describe the Bug

I have detected a glitch in the WooCommerce plugin for PayPal on WordPress, where the button to proceed with payment through this platform appears in the mini cart on the homepage but not on the checkout page.

### To Reproduce

1. Go to the checkout page to pay for the product.
2. Click on Paypal
3. Scroll down to see that the payment completion button is not there.

### Screenshots
<img width="1568" alt="Captura de pantalla 2023-08-16 a las 9 08 57" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/142382976/b36aaacb-f14e-4799-a457-08b70e8f64a3">
<img width="551" alt="Captura de pantalla 2023-08-16 a las 9 08 26" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/142382976/719c0809-f24c-479a-a8a8-f79636977d82">
<img width="492" alt="Captura de pantalla 2023-08-16 a las 9 06 30" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/142382976/d1013eba-417b-4565-bf48-dcd4f808a044">

### Expected Behavior
The button to make the payment with PayPal should appear on all pages and options previously configured in the plugin.

### Actual Behavior

The button only appears when you expand the cart on the homepage.

### Environment

 - WordPress Version 6.3
 - WooCommerce Version 8.0.2
 - Plugin Version 2.2.0
 - Browser [e.g. Chrome, Safari] and Version. Chrome 115.0.5790.170
 - Any other plugins installed. woocommerce multilingual & multicurrency, wooSwatches, woocommerce product stock alert

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @agenciavisual 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Since you did not provide us with your system report, we cannot review this issue on your website. Because of this, I cannot really verify and respond to this issue report. Please open a case with our support team and include the system report there, so we can take a look at this and see if we can help you out with this situation. We will close this thread for now.

Kind regards, 
Joost
