### ISSUE TITLE
Paypal button is not showing in the checkout page

### ISSUE THREAD

**Issue by alijundi** [woocommerce/woocommerce-paypal-payments#1606]
It is only showing in the minicart version. I am pretty sure I have setup everything correctly!

I am using woocommerce with Enfold Theme. I have no errors in the console of the browser!

**Comment by SydeKrystian** [comment]
Hello @alijundi 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This looks like a conflict with another plugin. These type of errors we often see when our plugin uses the same resource library as another plugin, but they are using different versions. You can find out what plugin this conflict is caused by, by performing a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/). If you require our help in further checking this conflict, or you have other questions, please raise a new support request via the link provided above.

Kind regards,

Krystian
