### ISSUE TITLE
Bug with PayPal payments

### ISSUE THREAD

**Issue by Lsn06** [woocommerce/woocommerce-paypal-payments#1610]
### Describe the Bug

We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again. Je n'arrive pas à associer mon compte j'ai cette erreur qui apparait, si vous avez une idée pour résoudre le soucis 
Merci

**Comment by Sirvijver** [comment]
Hello @Lsn06 

You have reached out to GitHub with a support request. We only provide support request via other platforms, so I would advise you to reach out to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you seem to be experiencing is not related to any issue with the plugin, but is something that needs to be adjusted to your account. This adjustment can be requested via this [link](https://woocommerce.com/document/woocommerce-paypal-payments/#sign-up-for-advanced-card-payments), you can also do it by onboarding the plugin while selecting the advanced features, or you can reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to review and adjust/advise.

However, you are saying that you could not complete the onboarding process... if you got some sort of error during/after the onboarding process, the issue might be different, but we would need to see the error you are seeing in order to advise you better.

Please see if any of these options work out for you. If you still have issues, please open a support request as explained above. We will close this GitHub thread now.

Kind regards,
Joost
