### ISSUE TITLE
Orders are being placed with no customer information

### ISSUE THREAD

**Issue by Fuzzy514** [woocommerce/woocommerce-paypal-payments#1611]
I have been getting orders and there is no customer information. No address to ship to and no billing address. 

![Screen Shot 2023-08-20 at 5 25 56 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/142753709/a984a5e9-c679-44a6-9d2a-63c2333d821d)

 - WordPress Version ?
 - WooCommerce Version 8.0.2

**Comment by Sirvijver** [comment]
Hello @Fuzzy514 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I believe this issue is related to a known issue that occurs for our current version 2.2.0, and we have already got a package available that should resolve this problem. You can [download it here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.2.1-rc1) and overwrite the current plugin by installing it manually.
If that does not resolve the issue, please open a support request as described above and we can take a closer look. The package is based on the current version 2.2.0, and it will also be included in our upcoming release 2.2.1.

Regards,
Joost

**Comment by Fuzzy514** [comment]
I have no idea how to do that. I’m not a programmer. Are there any videos that could walk me through it? Best Regards,Margaret ConnorLife is short. Use the good soap. On Aug 21, 2023, at 2:46 AM, Joost van de Vijver ***@***.***> wrote:﻿
Closed #1611 as completed.

**Comment by Sirvijver** [comment]
Hello @Fuzzy514 

No programming required ;-) You simply download the linked zip file. Then you go to Plugins, then you click "Add New" in the top of this page, then click "Upload Plugin", select the file you just downloaded "Choose File" and then click on "Install Now".

This will start the installation process and it should replace the current version of our plugin and correct the behavior you are experiencing. If you don't feel comfortable doing this, you might want to wait for the official release that should occur this week.

Kind regards, 
Joost
