### ISSUE TITLE
eCheck payments being processed despite 'Require instant payment' being checked

### ISSUE THREAD

**Issue by doug-6sense** [woocommerce/woocommerce-paypal-payments#1612]
### Describe the Bug

We have 'Require instant payment' checked in the WooCommerce > Settings > Payments > PayPal - Manage tab to prevent which the mouse over says prevents PayPal from using eChecks. We are however still receiving legitimate customer orders where the payment method used is PayPal eChecks.

### To Reproduce

We can't reproduce the error as it requires a legitimate order to be placed that utilises the eCheck payment method.

### Screenshots
<img width="799" alt="Screen Shot 2023-08-22 at 9 14 04 am" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/25813400/f3667e61-c82b-4868-a30c-6bd9330f2107">

<img width="288" alt="Screen Shot 2023-08-22 at 9 03 47 am" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/25813400/193034af-79d4-4e5d-bbcf-25b9fcd44f83">

### Expected Behavior

We expect no orders to be allowed to be paid via PayPal eCheck

### Actual Behavior

Orders with an eCheck payment method are being allowed to be placed

### Environment

 - WordPress Version: 6.2.2
 - WooCommerce Version: 7.9.0
 - Plugin Version: 2.2.0
 - Browser [e.g. Chrome, Safari] and Version: Chrome 115.0.5790.170

### Additional Details

We've always had this box ticked in the PayPal plugin and had not encountered this issue until approximately a month a go.

<details><summary>System status</summary>

Normal
  
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @doug-6sense 

Thank you for reaching out. We actually have a fix for this in place for our next release 2.2.1. Currently, you can download the beta for this release [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.2.1-rc1/woocommerce-paypal-payments.zip). The official release should be made available this week.
The GitHub Pull request can be found here: https://github.com/woocommerce/woocommerce-paypal-payments/pull/1489

I will close this thread now, since we assume this issue should be resolved with our next release. If you are still encountering the same issue while using this release, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
