### ISSUE TITLE
Your Paypal is not workin

### ISSUE THREAD

**Issue by napnide** [woocommerce/woocommerce-paypal-payments#1623]
### Describe the Bug
The Paypal button stopped working on my webpage. I tried to disable and enable the plugin again, uninstall and re install, and lots of more, nothing helps.
Now it asks me, to connect myPAYPAL and it does not do anything, when I am pressing the "connect paypal" button.
Ive tried Google Chrome, Ive tried Internet Edge, I have tried clearing cache and cookies.

And now I made this stupid account, just so I can submit this bug.
All this hassle,
Thank you.

Kind regards,
Nap

**Comment by Sirvijver** [comment]
Hello @napnide 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Yesterday, there were some outages on the PayPal server, so that could have caused issues with our plugin. You might want to try again and see this could have been the cause of the problem.

If the situation did not improve, please reach out to our support team via the link provided above, and we will take a look.

Kind regards, 
Joost
