### ISSUE TITLE
Paypal payment not supported in woocommerce subscription

### ISSUE THREAD

**Issue by joseph25076** [woocommerce/woocommerce-paypal-payments#1633]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @joseph25076 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We believe subscriptions are supported by our plugin, but you need [Reference Transactions](https://woocommerce.com/document/paypal-reference-transactions/) to be activated on your account in order to use PayPal for paying for such an order. Please read this document for more details on this.

We will now close this support request.

Kind regards, 
Joost
