### ISSUE TITLE
Paypal payment

### ISSUE THREAD

**Issue by joseph25076** [woocommerce/woocommerce-paypal-payments#1634]
Not supported in woocommerce subscription

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/56116019/dd96112d-8c49-4aa7-8db0-9d5d7515f08b)

**Comment by Sirvijver** [comment]
Hello @joseph25076 


You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This situation is caused by the "vaulting" function not being activated in the plugin settings page. This is nowadays a separate functon for PayPal and Advanced Card Processing, so you might have to activate it for both in case you also want to use Advanced Card Processing. 
It could be that vaulting is not available, since you can't use this without having [Reference Transactions activated on your account](https://woocommerce.com/document/paypal-reference-transactions/). If you don't have Reference Transactions activate, you should read the linked document that also explains how to activate these for your account.

If you have further questions, please reach out to us via the instructions provided above. This thread will be closed.

Kind regards, 
Joost
