### ISSUE TITLE
Standard card button doesn't work

### ISSUE THREAD

**Issue by digitaldesignerchemical** [woocommerce/woocommerce-paypal-payments#1640]
Hello,

I have a problem with the card button of PayPal that doesn't work. 

When I fill all the card details, the process can not be complete. 

Waiting your news,

Francesca Piccinno

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @digitaldesignerchemical 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

In order to help you out, we would need to know more details about the situation or be able to test this ourselves. What error do you get? You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

We will mark this thread as resolved and advise you to open a support thread as informed above, if the conflict testing does not show you what is causing this problem.

Kind regards, 
Joost
