### ISSUE TITLE
Pressing payment button fails after PayPal pop-up

### ISSUE THREAD

**Issue by HarlemSquirrel** [woocommerce/woocommerce-paypal-payments#1642]
### Describe the Bug

Clicking the PayPal button on a product page opens the PayPal  pop-up which closes itself and then a generic error message is displayed: "Something went wrong. Please try again or choose another payment source."

### To Reproduce

1. Go to [product page](https://randrchartersandsailschool.net/product/asa101/)
2. Fill out required fields
3. Scroll down to PayPal button and click it

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/6445815/d73c598d-2451-4489-9d8c-c660109e8f49)

### Actual Behavior

Should be prompted to continue payment with PayPal

### Environment

 - WordPress Version 6.3.1
 - WooCommerce Version 8.0.2
 - Plugin Version 2.2.2 
 - Browser Chrome and Firefox

All plugins
Akismet Anti-Spam: Spam Protection: by Automattic - Anti Spam Team – 5.2
WordPress.com Editing Toolkit: by Automattic – 3.76818
Gutenberg: by Gutenberg Team – 16.5.0
Jetpack: by Automattic – 12.5-beta
Layout Grid: by Automattic – 1.8.4
Page Optimize: by Automattic – 0.5.4
WooCommerce Payments: by Automattic – 6.3.2
WooCommerce PayPal Payments: by WooCommerce – 2.2.2
WooCommerce Shipping & Tax: by WooCommerce – 2.3.3
WooCommerce: by Automattic – 8.0.2

### Additional Details

Error logs 
[wc-pp.log](https://github.com/woocommerce/woocommerce-paypal-payments/files/12469700/wc-pp.log)
<details><summary>System status</summary>

  ```
Server Info: nginx
PHP Version: 8.0.30
PHP Post Max Size: 2 GB
PHP Time Limit: 1200
PHP Max Input Vars: 6144
cURL Version: 8.0.1
OpenSSL/1.1.1n

### Inactive Plugins (4) ###

Classic Editor: by WordPress Contributors – 1.6.3
Crowdsignal Forms: by Automattic – 1.7.0
Crowdsignal Polls & Ratings: by Automattic
Inc. – 3.0.11

Fullwidth Page Templates: by Brainstorm Force – 1.1.1

### Dropin Plugins (2) ###

advanced-cache.php: advanced-cache.php
object-cache.php: Memcached

### Theme ###

Name: Zoologist
Version: 1.0.42
Author URL: https://automattic.com/
Child Theme: ✔
Parent Theme Name: Blockbase
Parent Theme Version: 3.1.14
Parent Theme Author URL: https://automattic.com/
WooCommerce Support: ❌ Not declared

### Templates ###

Overrides: /wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/error.php
/wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/notice.php
/wordpress/plugins/woocommerce/8.0.2/packages/woocommerce-blocks/templates/notices/success.php
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @HarlemSquirrel 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

It looks like you are using a custom checkout page (blocks?) and this could cause this issue possibly. What I would suggest trying, is to create a 2nd checkout page, where you only add the short code [woocommerce_checkout] and you preview this page, while you have a product in your cart. If that works, then you know the issue is with the setup of your current checkout page, and you need to get that adjusted.

Please open a new support thread via the instructions above if you need our continued support.

Kind regards, 
Joost

**Comment by HarlemSquirrel** [comment]
@Sirvijver I reached out to support team. I wanted to also share here what I've found so far. It looks like an automatic update after Aug 8th migrated our checkout and cart pages to the new [Cart and Checkout blocks](https://woocommerce.com/document/cart-checkout-blocks-support-status/). which is not compatible with WooCommerce PayPal Payments.
