### ISSUE TITLE
marchent account payment fail

### ISSUE THREAD

**Issue by tonystark247** [woocommerce/woocommerce-paypal-payments#1659]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @tonystark247 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Since you have not provided any details on the problem, there is not much we can do to help you at this point. I would advise you to open the support ticket as advised above and add the errors you are encountering, the system report, logs and any screenshot you have available that could help us identify the problem.

For now we will close this thread.

Kind regards, 
Joost
