### ISSUE TITLE
ERREUR API TOKEN PAYPAL 

### ISSUE THREAD

**Issue by quetedunevie** [woocommerce/woocommerce-paypal-payments#1672]
Bonjour, 
Je reçois un message d'erreur sur mon site Wordpress, concernant paypal : 

"authentification api error not create token paypal" 
Je remarque qu'à ce moment là les Subscribed webhooks se déconnectent. 

Voici le screen 
<img width="1403" alt="Capture d’écran 2023-09-06 à 16 03 22" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/144252875/32e1023b-c723-42a0-bcf0-078bc29daf05">
<img width="1329" alt="Capture d’écran 2023-09-06 à 16 15 03" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/144252875/9054378c-aaa0-4642-a75c-3aa4314144fd">
<img width="1226" alt="Capture d’écran 2023-09-06 à 16 15 10" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/144252875/960e6a2d-e3ad-40fe-86ae-682f19ef7940">
<img width="752" alt="Capture d’écran 2023-09-06 à 16 15 17" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/144252875/47c8c377-0268-4846-9fec-e803280c8a3b">

merci infiniment de votre aide.
samia.

**Comment by InpsydeNiklas** [comment]
Hi @quetedunevie 
There may be an issue with the API credentials. I suggest disconnecting your account and reconnecting it using the [onboarding wizard](https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account) (`Activate PayPal` button). This should automatically insert the correct API credentials.

The 403 API error from the PayPal dashboard can be ignored. The plugin checks the PayPal API to understand if your merchant account is enabled for Reference Transactions, which is required to use the [Vaulting feature](https://woocommerce.com/document/woocommerce-paypal-payments/#vaulting-saving-a-payment-method). A bug (that was fixed for the next update in #1646) resulted in this endpoint being called too frequently, causing your PayPal API log to potentially be flooded with these 403 errors. But these are unrelated to any potential connection issues with the plugin.

I hope disconnecting and reconnecting helps. Otherwise, you can contact our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for additional guidance.
We will close this GitHub issue for now. However, our support team is available to assist you with any remaining questions. Thank you for your understanding!
