### ISSUE TITLE
Could not retrieve order.

### ISSUE THREAD

**Issue by infogc** [woocommerce/woocommerce-paypal-payments#1692]
### Describe the Bug

Every customer's order ends up failing with this note: Could not retrieve order. Maybe it was already completed or this browser is not supported. Please check your email or try again with a different browser."

### To Reproduce

It just takes a client to order selecting PayPal for payment

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/117646003/e1842097-db98-4735-8201-a61cf85d9f0a)

### Environment

 - WordPress Version
 - WooCommerce Version 8.1.0
 - Plugin WooCommerce PayPal Payments - Version 2.2.2
 - Browser 
 The problem depends on client that purchases from our shop, so we think that the browser that they use might be involved
 We are using Chrome 117.0.5938.62 
 Other plugins installed
 - Customer Reviews for WooCommerce - Version  5.34.0

**Comment by Sirvijver** [comment]
Hello @infogc 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you have encountered is a known issue, that occurs when you try to pay for an order with PayPal, without using the generic PayPal button. When you click the button to pay, you are most likely clicking on the default WooCommerce "Order Now" button.
This issue is often occurring by the theme or a 3rd party plugin, blocking the JavaScript that is required to replace the WooCommerce with the PayPal button. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If this does not help you resolve the issue, please open a support ticket as advised above, so we can try to help you out further. This ticket will be closed.

Kind regards, 
Joost
