### ISSUE TITLE
Paypal button single page product issue

### ISSUE THREAD

**Issue by vichardo** [woocommerce/woocommerce-paypal-payments#1705]
### Describe the Bug

**The paypal button is not loading on the page product.**

### To Reproduce

1. Go to ['…'](https://www.terre-d-eveil.fr/produit/leveil-du-ventre/)
2. Click on '…' Paypal button
3. Scroll down to …'
4. See error => nothing is loading

### Screenshots

<img width="1320" alt="Capture d’écran 2023-09-18 à 22 04 02" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/145394785/b29332da-8fd0-4ec9-8c9e-baccdb5148e2">

### Expected Behavior

The button load and we can pay directly through paypal

### Actual Behavior

The paypal window never load

### Environment

 - WordPress Version - 6.3.1
 - WooCommerce Version 8.1.1
 - Plugin Version 
 - Browser [e.g. Chrome, Safari] and Version Firefox 117.0.1
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

However, I believe your issue is related to this thread: 
https://github.com/woocommerce/woocommerce-paypal-payments/pull/1655
This issue should be resolved with our next release (version 2.3.0) and can already be tested with the beta version / release candidate that is available [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.3.0-rc1/woocommerce-paypal-payments.zip).

Please see if this helps and open a new support thread if needed, since this GitHub thread will be closed now.

Kind regards, 
Joost
