### ISSUE TITLE
conflict its and give fetal error  

### ISSUE THREAD

**Issue by binarydata123** [woocommerce/woocommerce-paypal-payments#1706]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @binarydata123 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Since you did not provide any details, I cannot give you any hints. Please open a support thread via the provided link for us to help you out further.

Kind regards, 
Joost
