### ISSUE TITLE
Bug entre WooCommerce PayPal Payments et Acowebs Woocommerce Dynamic Pricing

### ISSUE THREAD

**Issue by liloune89** [woocommerce/woocommerce-paypal-payments#1713]
Bonjour,
j'ai un bug pour payer avec paypal lorsque j'ai un coupon de réduction venant de "Dynamic Pricing" sur la page du paiement "checkout".

L'erreur qui s'affiche : "Désolé, il semblerait que le code promo « discount » soit invalide - il vient d’être retiré de votre commande."
Dans les logs du navigateur j'ai une erreur "create_order_error" 
`{
    "buttonCorrelationID": "...",
    "buttonSessionID": "...",
    "clientID": "...",
    "env": "production",
    "err": "<unknown error: [object Object]>",
    "referer": "www.paypal.com",
    "sdkCorrelationID": "...",
    "sessionID": "...",
    "timestamp": "1695219717506",
    "token": null
}`

et dans wordpress 
`2023-09-20T14:34:05+00:00 DEBUG Loaded onbording URL from cache: sandbox-ppcp
2023-09-20T14:34:05+00:00 DEBUG Loaded onbording URL from cache: sandbox-express_checkout
2023-09-20T14:34:05+00:00 DEBUG GET https://api.paypal.com/v1/notifications/webhooks
Response Debug ID: ...
Response: Array
(
    [code] => 200
    [message] => OK
)
`
Si je paie avec un autre moyen de paiement la même commande, je n'ai aucun soucis.
J'ai fais quelques recherches et visiblement c'est la somme négative du coupon qui pose problème.
Est-ce que quelqu'un aurait une idée ?

Merci

**Comment by Sirvijver** [comment]
Hello @liloune89 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue could be related to a known issue, where some plugins apply a discount as a negative item in the order, instead of applying it as a discount, but with the information we have, we are not able to confirm or deny this. For this reason, I would like to ask you to open a private engagement with us, as described above, so we can look into the system report, full logs and other details that might be required (that we would not like to share here via a public forum).

I will close this thread and wait for you to open a new thread on the support system, so we can take a closer look.

Kind regards, 
Joost

**Comment by liloune89** [comment]
Bonjour Joost, comment puis-je faire cela ?
Merci de votre aide.

**Comment by Sirvijver** [comment]
Bonjour @liloune89,

Nous vous prions d'ouvrir un échange privé avec nous en utilisant ce lien : https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
N'oubliez pas d'inclure le rapport système et éventuellement les journaux de notre extension si disponibles. Vous les trouverez ici :

WooCommerce > État > Journaux > sélectionnez "woocommerce-paypal-payments..." dans la liste déroulante et cliquez sur "Afficher".
Si aucun journal n'est disponible ici, il se peut que vous deviez activer la fonction "Journalisation" dans les paramètres de l'extension ici :
WooCommerce > Paramètres > Paiements > PayPal > Connexion > "Journalisation".
Cordialement,
Joost

===========================

Hello @liloune89 

Please open a private engagement with us via this link: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Don't forget to add the system report and possibly the logs from our plugin if available.  These can be found here:  
	- WooCommerce > Status > Logs > select "woocommerce-paypal-payments..." in the dropdown and click on view.  
If there are no logs available here, you might need to enable the "Logging" function in the plugin settings here:  
- WooCommerce > Settings > Payments > PayPal > Connection > “Logging”.  

Kind regards, 
Joost

**Comment by liloune89** [comment]
merci, c'est fait ;-)
