### ISSUE TITLE
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation.

### ISSUE THREAD

**Issue by AnesKaricBa** [woocommerce/woocommerce-paypal-payments#1716]
Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-COMPLIANCE_VIOLATION

I am trying to test a payment gateway by PayPal Sandbox. Everything is set fine. Business account for receiving payment and personal for testing and paying. I am receiving this error above on everycheckout!!! I cannot find a solution 3 hours yet... Please any ideas? Thank you!

**Comment by SydeKrystian** [comment]
Hello @AnesKaricBa 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

I would like to clarify that the "COMPLIANCE_VIOLATION" error is not a technical issue stemming from the PayPal Payments plugin itself. This error is connected to the PayPal merchant account rather than the plugin's functionality.
It's crucial to understand that only [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) can effectively address and assist with resolving this error. They have the expertise to investigate the specifics of your merchant account and provide the appropriate guidance to overcome this issue.

We'll be closing this GitHub issue for now. Thank you for your understanding!

Kind regards,
Krystian
