### ISSUE TITLE
Problemas al agregar mas de 2 productos al carrito 

### ISSUE THREAD

**Issue by 182103** [woocommerce/woocommerce-paypal-payments#1721]
### El plugin no me permite agrear mas de dos productos al carrito, si agrego uno, cuando intento agregar el segundo me borra el primer producto que se habia agregado 

1. Go to '…'  tienda en linea 
2. Click on '…' cualquier producto 
3. Scroll down to …' agregar un segundo producto 
4. See error al momento de tratar de cargar un segundo producto 

### Screenshots 
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/145757278/fd4d4b48-8795-46db-9385-cf2f34e8f03d)

### Environment

 - WordPress Version  6.3.1
 - WooCommerce Version 2.2.2
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version  crome 
 - Any other plugins installed  PHP 7.3.1

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by 182103** [comment]
Especificamente estoy utilizando este plugins WooCommerce PayPal Payments cuando lo desactivo me deja agregar mas de 2 productos pero obviamente me quita la opcion de pagar con PayPal y tarjetas credito/debito

**Comment by Sirvijver** [comment]
Hello @182103 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I did take a look at your site, and it seems this issue is only occurring when you add more than 1 variable product. The simple products get added to the cart without any issue.
We did encounter very similar issues after the last releases, and I think we have already a fix available for this problem. You can test the fix with the latest release candidate (beta / rc2) that is available [here](https://github.com/woocommerce/woocommerce-paypal-payments/releases/download/2.3.0-rc2/woocommerce-paypal-payments.zip). 

If that beta package does not resolve this issue, please open a support ticket as described above. Please be sure to test this package on a [staging site](https://wordpress.org/plugins/wp-staging/), so you don't affect your live site.

Kind regards, 
Joost
