### ISSUE TITLE
Pay Now & Pay Later buttons not working on version 2.1.0 and above

### ISSUE THREAD

**Issue by rajsidhux** [woocommerce/woocommerce-paypal-payments#1722]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by HelpAdude** [comment]
yeah venmo disappeared for me too.

**Comment by rajsidhux** [comment]
Does anyone know why this is happening?

**Comment by Sirvijver** [comment]
Hello @rajsidhux and @HelpAdude 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The Pay Later & Venmo payment option can only be blocked by our plugin. This can be done in the settings tab "Standard Payments" with the option "Disable Alternative Payment Methods". However, this will only send the request to the PayPal server to not show the payment method within the iFrame that they control. In the end it is the PayPal server side that decides what is being shown or not. It might be better to get in contact with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them why these options are not being shown (if the mentioned setting does not block these payment methods).

You can also test with a sandbox account to see if that does show the payment method in order to verify this is an account issue and not a settings issue with the plugin.

If you still require support, please open a support ticket as mentioned above.

Kind regards, 
Joost
