### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'WC_Subscriptions_Product' not found in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:545

### ISSUE THREAD

**Issue by jaynchou** [woocommerce/woocommerce-paypal-payments#1732]
PHP Fatal error:  Uncaught Error: Class 'WC_Subscriptions_Product' not found in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:545

**Comment by jaynchou** [comment]
PHP Fatal error:  Uncaught Error: Class 'WC_Subscriptions_Product' not found in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php:545
Stack trace:
#0 /usr/local/lighthouse/softwares/wordpress/wp-includes/class-wp-hook.php(312): WooCommerce\PayPalCommerce\Subscription\SubscriptionModule->WooCommerce\PayPalCommerce\Subscription\{closure}()
#1 /usr/local/lighthouse/softwares/wordpress/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters()
#2 /usr/local/lighthouse/softwares/wordpress/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-product-data.php(568): do_action()
#4 /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce/includes/class-wc-ajax.php(2425): WC_Meta_Box_Product_Data::save_variations()
#5 /usr/local/lighthouse/softwares/wordpress/wp-includes/class-wp-hook.php(310): WC_AJAX::save_varia in /usr/local/lighthouse/softwares/wordpress/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-subscription/src/SubscriptionModule.php on line 545

**Comment by jaynchou** [comment]
this error cause me not able to edit and save my products variants

**Comment by InpsydeNiklas** [comment]
Hi @jaynchou, thanks for reporting the issue and apologies for the trouble.
Could you please give it a try with this [2.3.1-rc1 version](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.3.1-rc1) and let us know how this works for you? Thank you!

**Comment by InpsydeNiklas** [comment]
Hi @jaynchou, this issue was just addressed in the latest [update 2.3.1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.3.1). So I will close this issue.
If you continue to encounter any problems after updating, I suggest reaching out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thank you!

**Comment by jaynchou** [comment]
thank you I downgrade to 2.3.1-rc1 version and it works. but the 2.3.1 is not working

**Comment by Sirvijver** [comment]
Hello @jaynchou 

If that is the case, you might be experiencing another issue, because so far, we have only received positive responses on our fix. 
Firstly, I would advise you to see if there is no caching situation present that nullifies our solution. After that, I would ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance, since we don't do investigations via GitHub; only development items are raised here.

Kind regards, 
Joost
