### ISSUE TITLE
Venmo payment link at checkout Not Working Mobile Phone

### ISSUE THREAD

**Issue by avgolf** [woocommerce/woocommerce-paypal-payments#1737]
### Describe the Bug

The Venmo payment link at checkout does not work from a mobile phone (using advanced card processing plugin). It opens to a link (https://history.paypal.com/smart/checkout/venmo/popup?.... page) which immediately closes. Then I get an error message: Something went wrong. Please try again or choose another payment source. Please help!

To Reproduce, using a mobile phone (I tested from both android and iphone):

1. Go to https://www.avalongolf.co/
2. Add a product to the cart (ex. https://www.avalongolf.co/product/players-golf-jogger-light-gray/)
3. Go to Checkout area: https://www.avalongolf.co/checkout/
4. Fill out billing details - go to page 2 of checkout
5. Select Venmo payment option (it will attempt to redirect to: https://history.paypal.com/smart/checkout/venmo/popup?.... page
and then will give you the message: Something went wrong. Please try again or choose another payment source. 

Screen capture of error message:
![venmo-error](https://github.com/woocommerce/woocommerce-paypal-payments/assets/146346376/1647139e-22b4-41a1-b977-9483c7e28c2a)

Please help!

**Comment by Sirvijver** [comment]
Hello @avgolf 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I did take a look at your site and attempted the same purchase as you described. I did not encounter this issue, and the order seems to be shown with the Venmo payment method included:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/c61d8fb5-a941-4202-a1d0-79d31700ce71)

Also, the error you saw, was not displayed on my phone. This error is sometimes shown when other plugins are affecting the order creation/payment, so you might want to do some [conflict testing](https://docs.woocommerce.com/document/how-to-test-for-conflicts/) with other plugins deactivated to see what might be causing this situation for you.

If you require additional help from our end, please open a support request as described above, since this thread will be closed.

Kind regards, 
Joost
