### ISSUE TITLE
Error simplification frontend 

### ISSUE THREAD

**Issue by natko1** [woocommerce/woocommerce-paypal-payments#1739]
I think this error should be made more user friendly for customers.

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYMENT_DENIED CreditCardGateway.php:410 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-PAYMENT_DENIED OrderEndpoint.php:332 Order status changed from Pending payment to Failed.

**Comment by Sirvijver** [comment]
Hello @natko1 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue is most likely caused by a bank or PayPal denying the transaction and need to be investigated by PayPal Merchant Technical Support. ​We have no access to the backend logging of PayPal, so cannot see why this transaction was denied. Please contact [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) to get this investigated.
​
​There is not much we can do for this instance, but do let us know if you have any technical questions concerning our plugin.

Kind regards, 
Joost
