### ISSUE TITLE
The translations of PayPal buttons and backend settings do not work in Firefox

### ISSUE THREAD

**Issue by CppClown** [woocommerce/woocommerce-paypal-payments#1743]
### Describe the Bug

The translation of the PayPal buttons does not work properly. The button labeling is correct with the latest versions of Google Chrome and Microsoft Edge. Unfortunately this doesn't work with Mozilla Firefox (version 118.0.1).

Furthermore, “WooCommerce PayPal Payments” is the only plugin that shows the settings in the WordPress backend in English, even though German ("Deutsch") is selected as the system language.

### To Reproduce

1. Open a German website (that uses the plugin) in Google Chrome and/or Microsoft Edge.
2. Add a product to your shopping cart and proceed to checkout.
3. At the checkout you will see that the PayPal buttons have the German labeling, as expected:

![Chrome](https://github.com/woocommerce/woocommerce-paypal-payments/assets/128615365/d729eddd-2dc2-4736-8b00-7654287f1aad)

4. Open a German website (that uses the plugin) in Mozilla Firefox
5. Make sure you have set Firefox's language settings to German everywhere. (In the settings, search for “lang” or “Sprach” and set everything to “Deutsch” or “German”.)
6. Add a product to your shopping cart and proceed to checkout.
7. At the checkout you will see that the PayPal buttons have English labels, although the German language is set:

![Firefox](https://github.com/woocommerce/woocommerce-paypal-payments/assets/128615365/8ffa478a-d285-4db8-8a46-cfbdb5b3a56b)

### Expected Behavior

The plugin should use the language set in WordPress for the PayPal buttons and the backend settings. If it is a website for German customers, then the PayPal buttons should also have a German label - regardless of the browser.

### Actual Behavior

In Firefox the PayPal buttons are always displayed in English. Likewise the plugin settings in the WordPress backend.

### Environment

 - WordPress Version: 6.3.1
 - WooCommerce Version: 8.1.1
 - Plugin Version: 2.3.1
 - Browser and Version:
     - Mozilla Firefox 118.0.1
     - Google Chrome 117.0.5938.132
     - Microsoft Edge 117.0.2045.47

**Comment by InpsydeNiklas** [comment]
Hi @CppClown, the button translations currently are [handled by PayPal](https://woo.com/document/woocommerce-paypal-payments/#faq-translating-paypal-payments). The language in the Firefox browser must be configured with "German (Germany)" instead of "German" for PayPal to detect the locale correctly. 
That being said, #1098 adds a language selector for you to override the automatic language detection:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/d87bd57a-5eb5-43a2-a7fb-ec4683950ff9)
This will be included in the next update.
