### ISSUE TITLE
paypal wont intergate 

### ISSUE THREAD

**Issue by JoelFelsenstein** [woocommerce/woocommerce-paypal-payments#1745]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @JoelFelsenstein 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please provide more details when you open this support ticket, because we can't advise you with the amount of details you have provided here. Closing this thread.

Kind regards, 
Joost
