### ISSUE TITLE
Problème depuis MAJ 2.1.2

### ISSUE THREAD

**Issue by victoiredavril** [woocommerce/woocommerce-paypal-payments#1762]
Bonjour,
depuis la MAJ de 2.1.0 je rencontre de nombreux problème.
Avec la version 2.1.1 lorsqu'un client passe commande je n'ai aucune information sur le client (adresse nom tel ect).
Depuis, plusieurs MAJ ont été installés, cependant sur chacunes d'elles je rencontre un autre problème : Lorsqu'un client met plusieurs produits dans leur panier, les précédents produits ce supprime ou le panier se vide complètement.

Je suis dans l'obligation de désactiver votre plugin sinon ces deux problèmes interviennent. 
Merci de prendre en charge ma demande de sav
cordialement
L'equipe victoire d'avril

**Comment by Sirvijver** [comment]
Hello @victoiredavril 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue is a known issue from our 2.2.0 release, but should have been resolved with the release after that. In our current release 2.3.1, this issue should not occur. If you still encounter this issue, I advise you to first perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

If that does not help identify the cause of the issue, please open a private thread with our support team as explained above.

Kind regards, 
Joost
