### ISSUE TITLE
Woocommerce Payments plugin causes problem after upgrade

### ISSUE THREAD

**Issue by WimRoskam** [woocommerce/woocommerce-paypal-payments#1763]
### Describe the Bug

I can't enter correct prices with 2 decimals in the product variations fields of my woocommerce website.

### To Reproduce

1. Go to Products > Variations > Product variation
2. Click on Regular Price
3. Enter value e.g. 90,10
4. Save changes
5. Goto to the same field: instead of 90,10 you will see 9010.

### Environment
All plugins are up to date.
This behaviour started after the latest upgrade of Woocommerce Payments plugin. Yesterday all worked normal.
After de-activating the plugin I could enter correct values.
My website works with WPML multilanguage.

**Comment by SydeKrystian** [comment]
Hello @WimRoskam 

It seems that the issue is related to the Woocommerce Payments plugin rather than the PayPal Payments plugin.

To best address this issue, I recommend reaching out directly to Woocommerce's support. You can create a ticket with them using the following link: https://woocommerce.com/my-account/create-a-ticket/

They will be better positioned to assist you with this particular problem.

Kind Regards,
Krystian
