### ISSUE TITLE
Could not fetch the order tracking information

### ISSUE THREAD

**Issue by MLBEMCR** [woocommerce/woocommerce-paypal-payments#1773]
2023-10-16T11:59:19+00:00 CRITICAL Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not fetch the order tracking information. in /home/customer/www/dtfireworkstore.co.uk/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php:569
Stack trace:
#0 /home/customer/www/dtfireworkstore.co.uk/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php(338): WooCommerce\PayPalCommerce\OrderTracking\Endpoint\OrderTrackingEndpoint->throw_runtime_exception(Array, 'fetch')
#1 /home/customer/www/dtfireworkstore.co.uk/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/MetaBoxRenderer.php(99): WooCommerce\PayPalCommerce\OrderTracking\Endpoint\OrderTrackingEndpoint->list_tracking_information(6861)
#2 /home/customer/www/dtfireworkstore.co.uk/public_html/wp-admin/includes/template.php(1443): WooCommerce\PayPalCommerce\OrderTracking\MetaBoxRenderer->render(Ob in /home/customer/www/dtfireworkstore.co.uk/public_html/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/Endpoint/OrderTrackingEndpoint.php on line 569

**Comment by Sirvijver** [comment]
Hello @MLBEMCR 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The old shipment tracking functionality was opt-in and required you to manually enable it from the Connection tab. This setting was removed because in the latest version, updated Package Tracking functionality is automatically enabled by default. The new PayPal Package Tracking metabox automatically appears on all your PayPal orders (by default is below the order data but can be moved around) similar to how it worked before.
There is nothing to configure to get it enabled and the integration now supports more plugins for automatic tracking data submission than before (with support for more plugins being added): https://woocommerce.com/document/woocommerce-paypal-payments/#package-tracking.

Please take a look at this and open a support request, as explained above, if you require any additional support.

Kind regards, 
Joost

**Comment by MLBEMCR** [comment]
Hi Joost, 

Thanks for your reply. 

In my view making this an automatic feauture is a misstep.  We are a Click & Collect only store and so do not add tracking to our orders. I have submitted a support request through Woocommerce, however is there a way you know of to turn the order tracking function off so this error isn't triggered again?

Cheers, 

Myles.
