### ISSUE TITLE
Hosted Fields Payments already in progress

### ISSUE THREAD

**Issue by nrocklein** [woocommerce/woocommerce-paypal-payments#1782]
### Describe the Bug

User receives "Hosted Fields Payments already in progress".   This confuses clients, causing duplicate ordering or leaving the site thinking by hitting back button.

### To Reproduce

1. Go to '…'Checkout page
2. Click on '…'Place order
3. Scroll down to …'See top of page and delay

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/61713327/fc453ec6-9624-4b56-bf70-4d57c8a7642f)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/61713327/0369843e-5292-409f-a929-e252577db6e1)

### Expected Behavior

  No red error message.  Just the spinning wheel is fine

### Actual Behavior

  red error message appears at top of screen and then spinning wheel shows

### Environment

 - WordPress Version [WordPress 6.3.1
 - WooCommerce Version Version 8.2.1
 - Plugin Version Version 2.3.1
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @nrocklein 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The message "Hosted Fields payment is already in progress." may briefly appear after submitting a card payment after the card fields were re-rendered, e.g. due to an AJAX reload.
So you can trigger it by visiting the Checkout page, selecting the Advanced Card Processing gateway, changing any form field that results in an AJAX reload (e.g. change postcode), and confirming a payment.
This message will briefly appear at the top of the Checkout page, but the payment will process correctly. We understand this message can be confusing, but there is currently not much we can do about it without introducing more issues.

You can find more details about the problem in this GitHub issue comment: https://github.com/woocommerce/woocommerce-paypal-payments/issues/1011#issuecomment-1610070171
PayPal is working on a fix, but we can't estimate when it will be available, as it is up to PayPal to provide the required fix. We hope it won't take much longer, though.
The only way to potentially work around this message is by using an older plugin version, like [version 1.9.5](https://downloads.wordpress.org/plugin/woocommerce-paypal-payments.1.9.5.zip). But this has drawbacks, and we generally recommend using the latest version for the best possible compatibility and security.

Please follow the linked GitHub issue for updates or open a support thread as advised above.

Kind regards, 
Joost

**Comment by titibleh** [comment]
Hello @Sirvijver,

There is the same issue with a blank theme (Hello Theme) and only Woocommerce + Paypal plugins v.1.9.5 activate. So please Paypal team, go back to work and fix this critical issue. We want to use your Advanced Card Processing gateway but we cannot because many people leave the Order page when they see the error message "Hosted Fields Payments already in progress".

Thanks!

**Comment by Sirvijver** [comment]
Hello @titibleh and @nrocklein 

Yes, you are right, the revert does not seem to resolve is (sorry, this was a solution I took from an older response). This issue can only be fixed by implementing PayPal's new card fields, which will happen within the scope of Vault v3 development. This feature will be released soon, but I can't give you an exact date.

Kind regards, 
Joost
