### ISSUE TITLE
Updating plugin or resubscribe webhook events

### ISSUE THREAD

**Issue by qunn** [woocommerce/woocommerce-paypal-payments#1798]
### Foreach loop without condition

Example, in your paypal account, you have a several webhooks, for your wordpress shop, mayb AmoCRM or any CRM anyone services. After updating plugin or resubscribe webhooks in settings, your method requesting webhook list and pass this list, to deleting method by foreach loop, because loop doesn't have conditions, your/my webhooks for any services is deleted. It's sad.

### Environment

 - Plugin v2.3.1

### Solution
Maybe this, for example, solve this problem. Adding condition for ignore delete() method, if webhook url not for this domain.

```
wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-webhooks/src/WebhookRegistrar.php:119

foreach ( $webhooks as $webhook ) {
      try {
         if (isset( $webhook->url ) and strpos( $webhook->url, home_url ( '/' )) === false) continue; // <--- skip, not our domain
	      $this->endpoint->delete( $webhook );
      } catch ( RuntimeException $deletion_error ) {
	      $this->logger->error( "Failed to delete webhook {$webhook->id()}: {$deletion_error->getMessage()}" );
      }
}
```

**Comment by InpsydeNiklas** [comment]
Hi @qunn, it is not recommended to reuse the same REST application for multiple purposes. PayPal Payments clears the entire webhook subscription as this is needed to e.g. clear old webhook subscriptions from a staging site on a different domain. If the plugin skipped subscriptions from other domains, then it wouldn't be possible to remove the old subscription without reconnecting or navigating to the PayPal dashboard.
I recommend creating separate REST applications for each of your integrations. If you need more guidance, please [get in touch with the support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!

**Comment by qunn** [comment]
You right, but Paypal have specific work between Applications and sometimes need have another events for other actions, example disputes.

May be you can add hook/filter on this action, anything, for can possible overwrite manualy event list or modify response with event list? You have a ppcp_request_args hook, may be analogic

**Comment by InpsydeNiklas** [comment]
> You right, but Paypal have specific work between Applications and sometimes need have another events for other actions, example disputes.

Normally, all PayPal functionality should also work across different REST Apps, so that you could safely utilize one app per integration. 
In any case, removing [this action](https://github.com/woocommerce/woocommerce-paypal-payments/blob/2910d22f0bc184ab0ef1dbb68ab8de41870abd39/modules/ppcp-webhooks/src/WebhookModule.php#L148-L161) would prevent the webhook resubscription when upgrading the plugin. But this would need to be changed in the package that's being installed, so it's not a solution that allows automatic updates.
It requires a little more profound understanding of the [modular plugin design](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Modular-plugin-architecture), but it is possible to [add a custom module](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#adding-modules-and-accessing-the-plugin-container) to override existing ones. So, even without hooks/filters, it would be possible to modify the plugin from an external plugin and e.g. remove an action. Though admittedly, it is more complex than using a regular hook. The team will investigate the opportunity to add more hooks, but we must ask for your understanding that something like this most likely won't be included in the plugin in the short term.
