### ISSUE TITLE
Refunds cannot be issued in Woo order dashboard

### ISSUE THREAD

**Issue by wideglidemike** [woocommerce/woocommerce-paypal-payments#1800]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @wideglidemike 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

You did not provide any specific error for this issue, but I would suggest you try the following 2 options:
- Test the webhooks - Under the "Connection" tab in the settings page, you will find 2 buttons "Simulate" and "Resubscribe" that will help you test and possibly correct the webhooks. This could identify and correct a refund issue.
- You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If none of this helps, we suggest you open a support request as instructed above, since we will close this thread.

Kind regards, 
Joost

**Comment by wideglidemike** [comment]
Thank you! Sent from my iPhoneOn Oct 30, 2023, at 6:29 AM, Joost van de Vijver ***@***.***> wrote:﻿
Hello @wideglidemike
You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to reach out to the support team directly for more guidance.
You did not provide any specific error for this issue, but I would suggest you try the following 2 options:

Test the webhooks - Under the "Connection" tab in the settings page, you will find 2 buttons "Simulate" and "Resubscribe" that will help you test and possibly correct the webhooks. This could identify and correct a refund issue.
You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the default theme Storefront and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: How to test for conflicts.

If none of this helps, we suggest you open a support request as instructed above, since we will close this thread.
Kind regards,
Joost
