### ISSUE TITLE
PayPal Payments is almost ready. To get started, connect your account. Broken

### ISSUE THREAD

**Issue by thowden** [woocommerce/woocommerce-paypal-payments#1802]
### Cannot complete: 
"PayPal Payments is almost ready. To get started, [connect your account]
(https://shop.recovertoy.com/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-connection)."

Your error message:

We could not properly connect to PayPal. Try reloading the page. [Error] Unknown error while connecting to PayPal. Status code: 0. /www/wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/PartnerReferrals.php:101

### To Reproduce

1. Go to Paypal Payments
2. Click on Connect your account
3. Rinse and repeat 10 times for same non-result.

 - WordPress Version - All latest - new site being built
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version - Chrome & Firefox
 - Any other plugins installed - If it is not compatible then it is really broken. 
 - Hosting with FlyWheel
 - PHP 8.1

Feedback please. 

cheers
Tony

**Comment by Sirvijver** [comment]
Hello @thowden 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering sometimes occurs and can there are some things you can try to get your account onboarded successfully:

- Take your time. When you go too quickly through the onboarding process, sometimes background process do not finalize and this can cause the process to fail to onboard your account. Try to take your time at every step of the process (wait 5 seconds before pressing to the next page) and see if that gets you a better outcome.  
- Another plugin can be blocking the onboarding process. You can try to onboard your account, while you have all other plugins (except WooCommerce and PayPal Payments) deactivated.  

The last resort, would be to onboard your account manually. This is our least favorite option, because it can cause certain features to not work. You can find instructions for this process [here](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input). However, we do always suggest trying using the [onboarding wizard](https://woocommerce.com/document/woocommerce-paypal-payments/#connect-paypal-account), because this avoids 


If you require additional support, please reach out to our support team as mentioned above. We will close this ticket now.

Kind regards, 
Joost
