### ISSUE TITLE
WooCommerce PayPal Payments. says "Something went wrong. Please try again or choose another payment source."

### ISSUE THREAD

**Issue by Dharmasuri** [woocommerce/woocommerce-paypal-payments#1839]
### Describe the Bug
Woocomerce using "WooCommerce PayPal Payments" all set up seems fine but at point of purchase says "Something went wrong. Please try again or choose another payment source."
help!!!

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Dharmasuri 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The error you mentioned can be caused by anything, so the first thing I would advise you to do, is to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

If this does not help, please open a support ticket as advised above, because this thread will be closed.

Kind regards, 
Joost
