### ISSUE TITLE
We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again.

### ISSUE THREAD

**Issue by AdeelMushtaq** [woocommerce/woocommerce-paypal-payments#1842]
We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again.

**Comment by Sirvijver** [comment]
Hello @AdeelMushtaq 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

There are many possible reasons for this to happen, but the most common reason would be that another plugin is blocking the webhooks that are required in order to get the communication working between the plugin and the PayPal server. You may want to try deactivating all other plugins (except WooCommerce and PayPal Payments) and then connecting your account again to the plugin. If that works, you might also want to test the webhooks after you re-activate all the other plugins. You can do this in the settings of our plugin, in the bottom of the "Connection" tab. There you will find 2 buttons: "Simulate" and "Resubscribe" that you can use to test and possibly correct the webhooks.

If this does not help you resolve the issue, please open a support thread as described above. This thread will be closed.

Kind regards, 
Joost
