### ISSUE TITLE
Paypal Notification on home page

### ISSUE THREAD

**Issue by Godsplan** [woocommerce/woocommerce-paypal-payments#1845]
### Describe the Bug

I freshly installed woo commerce and the "HEIM" theme.
Then installing plugins and configure everything.
I installed Paypal for WooC. 
After activating following message appears on the home page:

In the configurator or block wiz I can not see it and in the PayPal settings I can't delete it.

### To Reproduce

If I deactivate PayPal, it disappears.
If activate Paypal, it comes again

### Screenshots

<img width="1510" alt="Bildschirmfoto 2023-11-16 um 21 52 59" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/1547802/c75be09c-8681-4c1a-9dd3-0b4ff0433db3">

### Expected Behavior

Don't want to have that message on the home page or at all.

### Environment

 - WordPress Version: 6.4.1
 - WooCommerce Version, 8.3
 - Plugin Version, 2.4.1
 - Browser [e.g. Chrome, Safari] and Version: Safari
 - Any other plugins installed: No

**Comment by Sirvijver** [comment]
Hello @Godsplan 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This text looks to be the Pay Later Messaging, but it should not appear there. I would think this is caused by a plugin or theme conflict, so you can verify this by performing a full conflict test. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

However, the first thing to check (and possibly try) is to see under the "Pay Later" tab in the plugin setting, if you have the Pay Later Messaging active. If yes, try deactivating it and see if that did the trick:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/88686f78-00bb-442e-b2b3-60351c3af0ab)

If this does not help you resolve the issue, please open a support ticket, as this ticket will be closed.

Kind regards, 
Joost
