### ISSUE TITLE
Cart + Checkout Issues

### ISSUE THREAD

**Issue by Jonnyb0113** [woocommerce/woocommerce-paypal-payments#1846]
### Describe the Bug

If you add an item to your cart and click the cart too fast, it will sometimes take you to an empty cart. 

We have also received complaints from clients saying that the cart wont clear and or that duplicates are being added to their cart upon refresh.

We can't expect people to wait momentarily before clicking on the cart or going to checkout after an addition but if they wait a moment and not press it instantaneously it works fine. Every page on the bottom left corner says "waiting for paypal" and that arises suspicion that this plug in may be the issue. 

Before using this plug in we used another payal plug in that worked perfectly and we did not receive these errors or complaints. 

The sole purpose of us switching to this one was because it offers a better percentage than the alternative if clients checkout using it. 

### To Reproduce

1. Go to https://strictlysinks.store
2. Click on kitchen > kitchen sinks
3. Scroll down to …' any product. 
4. add an item to cart and quickly press the link to view cart or the cart icon
5. See error " your cart is empty"

### Environment

 - WordPress Version 7.4
 - WooCommerce Version 8.3.0
 - Plugin Version 2.4.1
 - Browser [e.g. Chrome, Safari] Version 119.0.6045.123 (Official Build) (arm64)
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @Jonnyb0113 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

What you are describing is not so much behavior that is caused by our plugin, but is the way WooCommerce functions. If you don't leave time to add a product to your cart, it can indeed end up in the cart being empty and then suddenly showing up after you refresh the cart. However, this has got nothing to do with the PayPal Payments plugin. Next to that, I think this is how WooCommerce is intended to function, but if you want you could engage WooCommerce support to have this discussion with them, since we will not be able to change anything about this behavior.

If you have any further questions, please open a thread on our support interface as described above. This thread will be closed.

Kind regards, 
Joost

**Comment by Jonnyb0113** [comment]
> ### Describe the Bug
> If you add an item to your cart and click the cart too fast, it will sometimes take you to an empty cart.
> 
> We have also received complaints from clients saying that the cart wont clear and or that duplicates are being added to their cart upon refresh.
> 
> We can't expect people to wait momentarily before clicking on the cart or going to checkout after an addition but if they wait a moment and not press it instantaneously it works fine. Every page on the bottom left corner says "waiting for paypal" and that arises suspicion that this plug in may be the issue.
> 
> Before using this plug in we used another payal plug in that worked perfectly and we did not receive these errors or complaints.
> 
> The sole purpose of us switching to this one was because it offers a better percentage than the alternative if clients checkout using it.
> 
> ### To Reproduce
> 1. Go to https://strictlysinks.store
> 2. Click on kitchen > kitchen sinks
> 3. Scroll down to …' any product.
> 4. add an item to cart and quickly press the link to view cart or the cart icon
> 5. See error " your cart is empty"
> 
> ### Screenshots
> ### Expected Behavior
> ### Actual Behavior
> ### Environment
> * WordPress Version 7.4
> * WooCommerce Version 8.3.0
> * Plugin Version 2.4.1
> * Browser [e.g. Chrome, Safari] Version 119.0.6045.123 (Official Build) (arm64)
> * Any other plugins installed
> 
> ### Additional Details
> System status

We have only noticed this behavior after this plug-in was activated. I will try with woo-commerce. Thank you.
