### ISSUE TITLE
The AMEX svg appears to be cropped

### ISSUE THREAD

**Issue by ryanr14** [woocommerce/woocommerce-paypal-payments#185]
### Describe the bug
The Amex svg shows as cropped in the assets folder and thus appears like something is wrong with the styling at checkout.

### To reproduce
Look in the assets/images folder, the SVG is not complete.

**Screenshots**
<img width="564" alt="Markup%202021-06-23%20at%2013 13 27" src="https://user-images.githubusercontent.com/867748/123149097-ecb80880-d42e-11eb-9861-723299a4d752.png">
<img width="1170" alt="Screen%20Shot%202021-06-23%20at%201 22 08%20PM" src="https://user-images.githubusercontent.com/867748/123149101-ecb80880-d42e-11eb-91ad-1ced714d7b93.png">

### Expected behavior
You'd normally see a full-width image. :)

**Comment by InpsydeNiklas** [comment]
Hi @ryanr14,
The AMEX icon has a different format than the other icons, but the file is actually complete.
However, since it indeed _appears_ to be cropped, we are looking at alternate icon options and further improvements towards the icons.
In the meantime, you can change it yourself as the icon is located in the plugin files:
`/woocommerce-paypal-payments/modules/ppcp-wc-gateway/assets/images/amex.svg`
Kind regards,
Niklas
