### ISSUE TITLE
Paypal Wordpress

### ISSUE THREAD

**Issue by tiggerbn** [woocommerce/woocommerce-paypal-payments#1882]
![998](https://github.com/woocommerce/woocommerce-paypal-payments/assets/152693091/2bfeba80-3306-4f76-801b-44d6f2db8f7b)
![999](https://github.com/woocommerce/woocommerce-paypal-payments/assets/152693091/779846f3-921e-4680-a94d-d642b79b2ab9)
![020304](https://github.com/woocommerce/woocommerce-paypal-payments/assets/152693091/709b8fc4-1bf6-42d0-b0ec-80cad9d0ff64)

[SystemStatusReport_megaiptvexpress.com_2023-12-04T10-28-57.txt](https://github.com/woocommerce/woocommerce-paypal-payments/files/13544810/SystemStatusReport_megaiptvexpress.com_2023-12-04T10-28-57.txt)
Hi,
 I have a connection problem with my Paypal pro account, my API identifiers are correct, however payment is not offered even though it is active

**Comment by Sirvijver** [comment]
Hello @tiggerbn 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

In order to activate these 2 options, you need to perform an action on the PayPal account. This action is described in our documentation [here for Apple Pay](https://woo.com/document/woocommerce-paypal-payments/#apple-pay) and [here for Google Pay](https://woo.com/document/woocommerce-paypal-payments/#google-pay). Please go through this and open a support ticket as described above, if you still require additional support.

For now, we will close this thread.

Kind regards, 
Joost

**Comment by tiggerbn** [comment]
This is the PayPal payment itself which is not offered, I have no payment method that appears even though PayPal is active. Paypal's technical service has just confirmed to me that my account has no problems.
