### ISSUE TITLE
Paypal woo commerce error - failed orders

### ISSUE THREAD

**Issue by PurelySocial** [woocommerce/woocommerce-paypal-payments#1886]
Hello. 

Our PayPal plugin seems to be not working

we have multiple uncompleted / failed orders with 553 status message.

They where told they had an error with their browser.

The message is 'could not retrieve order" Maybe it was already completed to this browser is not supported. Please check your email or try again with a different browser. Payapl gateway.php:553 Order statues changed from pending payment to failed.

Everything in the wordpress system is up to date.

Thanks
Sarah

**Comment by Sirvijver** [comment]
Hello @PurelySocial 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are reporting is/was often caused by a 3rd party plugin or the theme, not allowing our plugin to replace the WooCommerce "Place Order" button with the generic PayPal Button. When a customer used the WooCommerce button, the payment via PayPal can never succeed. This is a built-in security of the plugin and, until the last release, could not be avoided.

With our [last release, version 2.4.2](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.4.2), this should not be the case any longer and the payment method should work, even when you use the WooCommerce "Place Order" button.
You can also try to find out what plugin or theme is causing this issue, by doing conflict testing as [described here](https://docs.woocommerce.com/document/how-to-test-for-conflicts/).

Please make sure you have updated the plugin and test the situation again. If you are still encountering similar issues, please open a support thread as advised in the top of this response. 

Kind regards, 
Joost
