### ISSUE TITLE
Adresse de livraison shipping_city

### ISSUE THREAD

**Issue by Jrdebug44** [woocommerce/woocommerce-paypal-payments#1887]
![2023_12_05_10_49_15_votre_commande_Site_Jérôme_Richard](https://github.com/woocommerce/woocommerce-paypal-payments/assets/152967137/bf8a44ec-0dbb-4830-8e28-e39d23ea5613)

### Describe the Bug
Si l'adresse de livraison est différente de l'adresse de facturation,
alors le contrôle sur le champ ville (shipping_city) est erroné. 

En effet,  
SI je renseigne un nom de ville (texte), ALORS un message d'erreur bloquant apparaît : "VILLE DE LIVRAISON N’EST PAS UN CODE POSTAL VALIDE".
SI je renseigne une valeur numérique, ALORS ça passe.

Or dans mon paramétrage, le champ shipping_city est de type "Text".

BUG BLOQUANT car mes utilisateurs ne peuvent pas renseigner la ville de livraison. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment
 - WordPress Version : 6.4.1
 - WooCommerce Version : 8.3.1
 - "WooCommerce PayPal Payments" Plugin Version : 2.4.2
 - Browser [e.g. Chrome, Safari] and Version : Chrome 
 - Any other plugins installed

**Comment by Sirvijver** [comment]
Hello @Jrdebug44 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Without the full system report, logs or order notes, it is hard to give you any response on this matter. Firstly, I would ask you if this only happens when you use our payment method for paying for the order, or if this also happens with other payment methods. Then, if it is only our plug, I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this all still doesn't help you to isolate what is causing this, you should probably open a support thread with our team as advised above.

Kind regards, 
Joost
