### ISSUE TITLE
Cargué 2 medios de pago (PayPal y Mercado Pago) y me dice que no hay medios de pago disponibles

### ISSUE THREAD

**Issue by SantiBuda** [woocommerce/woocommerce-paypal-payments#1890]
Instalé WooCommerce para armar una tienda online en https://cursos.semillasdebuenestar.com y en la parte de pagos agregué 2 opciones, PayPal y MercadoPago, pero por algún motivo no funcionan, no aparecen. En la página de checkout no hay nada.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153039355/609da25d-0749-4d45-b2e7-35abb7c6281f)
Alguien sabe como arreglarlo?

**Comment by Sirvijver** [comment]
Hello @SantiBuda 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

As is documented [here](https://woo.com/document/woocommerce-paypal-payments/#woocommerce-blocks), the current version of our plugin does not yet support the PayPal Block Checkout gateway with smart buttons. Currently, you can only use the express checkout buttons in the checkout page (the ones that show in the top, under Quick payment). We are still working hard on getting the smart buttons to work, but they are not available at this moment.

If you want the standard buttons to work, you will need to use the default short code checkout page instead of the blocks option. We will close this thread. If you have any further questions or want to raise any issue, please open a support thread as advised above.

Kind regards, 
Joost
