### ISSUE TITLE
paypal payment fail

### ISSUE THREAD

**Issue by mak78032** [woocommerce/woocommerce-paypal-payments#1892]
### Describe the Bug

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID PayPalGateway.php:620 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID OrderEndpoint.php:335 Order status changed from Pending payment to Failed.

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @mak78032,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We have received a [similar case](https://wordpress.org/support/topic/failed-to-process-the-payment-13) in our .org support forum, so I would advise taking a look at [this thread](https://wordpress.org/support/topic/failed-to-process-the-payment-13) and see if you still need support after this. If you still require support from us after this, please open a new support thread as advised above, because we will close this thread.

Kind regards, 
Joost
