### ISSUE TITLE
Payment Gateway isen't show in configuration

### ISSUE THREAD

**Issue by alanrgon** [woocommerce/woocommerce-paypal-payments#1896]
The MercadoPago payment gateway is not listed in payment configuration. This occurred today

**Comment by Sirvijver** [comment]
Hello @alanrgon,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have taken a look on the official list, but I don't believe MercadoPago is one of the included Alternative Payment Methods that is provided by PayPal. You can find this list [here](https://developer.paypal.com/docs/checkout/payment-methods/).
We did have the idea that MercadoPago, used to be on this list, so it could be that this was change. Because of this, you might want to reach out to [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) to verify this situation.

I also just checked our plugin for the Alternative Payment Methods and I do see it in the list:
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/78153894/c074d993-0f32-4fb7-b25a-06ab2a2d79e6)
So this is something I will review with PayPal and see if they might have removed it, and we have not cleared it in our plugin. [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/) should be able to answer this for you. If you need our continued support, please create a support ticket as described above. You can refer to this GH thread, but I will close this for now.

Kind regards, 
Joost
