### ISSUE TITLE
Paypal Payment Unique Issue Encounter

### ISSUE THREAD

**Issue by inkkowinkko** [woocommerce/woocommerce-paypal-payments#1898]
Dear Paypal Support Team and Community,

I hope this email finds you well. I am writing to bring to your attention an ongoing issue that I have been experiencing with the integration of Paypal Payment on my online store, "winkko.store". I apologize in advance for the length of this email, but I believe it is necessary to provide a comprehensive explanation of the problem.

To give you a better understanding of the situation, let me briefly explain the setup. Recently, I integrated Paypal Payment with Woocommerce through WordPress, utilizing my personal Paypal account. Initially, everything appeared to be functioning smoothly, and I was optimistic about the seamless payment process that Paypal would provide to my customers.

However, when I attempted to place an order for myself as a test, I was met with perplexing and inconsistent error messages that have since plagued my store's checkout process. The error messages are as follows:

**_"Your card was declined, please contact your bank issuer and try a new card."
"This card can be used for Payments, please try a different card."
"We weren't able to add this card, please check all the information entered correctly and try again or try a different card."
These error messages have been persistently displayed, rendering the payment process on my store completely non-functional. Despite my best efforts to troubleshoot and resolve the issue, the problem remains unresolved._**

**In an attempt to rectify the situation, I have taken several steps. Firstly, I reset the store and theme to their default settings, hoping that this would eliminate any potential conflicts or configuration issues. Unfortunately, this did not yield the desired results. The error messages continued to appear, preventing any successful transactions.**

Additionally, I have meticulously reviewed and re-entered all relevant payment information, ensuring that everything is accurate and up-to-date. However, this has not resolved the issue either. I find myself at a loss as to what could be causing the problem.

As you can imagine, this issue is causing significant disruption to my business operations. It not only affects the customer experience, but it also undermines the trust and credibility of my store. Furthermore, the inability to process payments has resulted in a substantial loss of potential revenue. I tried almost twenty of the card, and none of them works.

I am reaching out to you with a sense of urgency, as I am in dire need of your assistance to resolve this matter promptly. Any guidance, advice, or support you can offer would be greatly appreciated. I am more than willing to collaborate closely with your team to identify and address the root cause of the problem.

Please let me know if there are any specific details, logs, or steps you require from my end to facilitate the investigation and resolution of this matter. I am committed to working hand-in-hand with you to find a solution and restore the smooth functioning of Paypal Payment on my store. 

Thank you for taking the time to review this email, and I sincerely hope for a swift resolution to this issue. I look forward to your prompt response and the opportunity to rectify this situation as soon as possible.

Yours sincerely,
INKKO Winkko
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153341302/f2068a49-b792-4c3f-8d0f-2f5d85f13980)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/153341302/a4672c93-b278-423b-8929-ca5a3ede48dd)

**Comment by Sirvijver** [comment]
Hello @inkkowinkko,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing is related to the Standard Card Processing payment method, which is not controlled by our plugin, but only triggered/activated by it. Our plugin does manage 1 card payment method, but that is only the Advanced Card Processing one. The Standard Card Processing is managed by PayPal from the server, so in order to get this reviewed, I would advise you to initially reach out to [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and ask them to investigate the transaction attempts. The errors you mentioned are all server side errors, so our plugin (if you were to use Advanced Card Processing) would not be able to do much to improve this situation. You need to get PayPal/MTS to review these attempts and let you know why this is occurring, so you can possibly improve this situation.

From our side, we can only advise you to try out the Advanced Card Processing payment method, this is the replacement for the method you are currently using and should be more secure and user-friendly. We did not get your system report, so could not take a look at the site or know where it is located (for checking the [availability of the Advanced Card Processing method](https://developer.paypal.com/docs/checkout/advanced/currency-availability-advanced-cards/)).

Please start by checking the current situation with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) and open a support thread as advised above if they can't help you and if you want to try the advanced card payment option, and you need help with that.

For now, we will close this GitHub thread.
Kind regards, 
Joost
