### ISSUE TITLE
Renewal order duplicated

### ISSUE THREAD

**Issue by androidominus** [woocommerce/woocommerce-paypal-payments#1906]
### Describe the Bug
Hello, 
we are experiencing a proliferation of duplicate renewal orders (even 3 or 4 for the same order).
It seems that the PaymentSaleCompleted webhook is invoked many times, even days apart, within the same renewal period with the same data.

We notice these duplications because the transaction id field is the same between the different orders that are created and on the paypal dashboard we have only received one payment.

### To Reproduce

Invoke PaymentSaleCompleted webhook with same data multiple times.

### Expected Behavior

No new renewal order created if order already exists with same paypal transaction id.

### Actual Behavior

New renewal order created any time webhook is fired.

### Environment

 - WordPress Version 6.4.2
 - WooCommerce Version 8.3.1
 - Plugin Version 2.4.2 
 - Woo Subscriptions 5.7.0
 -  WooCommerce PayPal Payments - Enable PayPal Subscriptions

**Comment by Sirvijver** [comment]
Hello @androidominus 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are encountering could be caused by the webhooks not getting properly received by our webhook and attempting the renewal again. So the first thing I would advise you to check is if the webhooks are functioning correctly. You can do this by going to the "Connection" settings tab and using the "Simulate" button that can be found in the bottom of this page. If the outcome is not positive, you can use the "Resubscribe" option and test again to see if that improved the situation. If that also does not help, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behaviour persists.

If none of this helps you further, please open a support thread as advise above in this response.

Kind regards, 
Joost
