### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by luminaspages** [woocommerce/woocommerce-paypal-payments#1934]
Paypal and vemno is not showing as an option at check out screen.

**Comment by InpsydeNiklas** [comment]
Hi @luminaspages, please ensure the PayPal buttons are enabled on your Checkout page from the Standard Payments settings tab: https://woo.com/document/woocommerce-paypal-payments/#paypal-buttons

But for any questions regarding the plugin setup, I recommend contacting the support team directly because this GitHub repository is not meant for support questions: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
