### ISSUE TITLE
PayPal Failing to Connect to Woocommerce Website

### ISSUE THREAD

**Issue by pleijsalon** [woocommerce/woocommerce-paypal-payments#1935]
### PayPal is not connecting to our websites Woocommerce Store using the PayPal for Woocommerce App. After clicking the manage button to connect the site to PayPal the pop up appears, we are permitted to enter our login credentials and upon successfully doing so receive a notice of congratulations indicating our site is now connected however, upon closing this window a notice is present at the top of the webpage advising, PayPal Payments is almost ready. Some features, such as credit card processing, will not be available. To fix this, please try again, Repeated attempts produce the same result. Removing and restoring the plugin does not resolve the issue.

 - WordPress Version - 6.4.2
 - WooCommerce Version - 8,4,0
 - Plugin Version - 2.4.2
 - Browser [e.g. Chrome, Safari] and Version - MS Edge

 Neither Woocommerce or Wordpress are reporting any problems with our instances. 

 We have attempted to rollback Woocoommerce and Woocommerce PayPal Payments to prior versions when we weren't experiencing this issue but this has failed to resolve the issue. 

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/155326637/08445267-570a-4e59-9e70-39b225a46af2)

**Comment by InpsydeNiklas** [comment]
Hi @pleijsalon, this message can have various causes but usually, it can happen when e.g. a security plugin is blocking the connection to PayPal. 
If all else fails you can also manually connect your API credentials: https://woo.com/document/woocommerce-paypal-payments/#manual-credential-input

But for any questions regarding the plugin setup, I recommend contacting the support team directly because this GitHub repository is not meant for support questions: https://woo.com/document/woocommerce-paypal-payments/#get-help
Thanks!
