### ISSUE TITLE
Button Paypal Later not visible on the final page for pay and other page products

### ISSUE THREAD

**Issue by ghost** [woocommerce/woocommerce-paypal-payments#1940]
### Describe the Bug
Since update (December 2023, the button PayLater not show on the page for pay, all is ok with Paypal but button not be visible, after that all was ok since update the button is not view.

### Expected Behavior
Before december 2023, all was ok, the button PayLater was view and people can chose for pay.

### Actual Behavior
Since update (December 2023, the button PayLater not show on the page for pay, all is ok with Paypal but button not be visible, after that all was ok since update the button is not view.

### Environment
 - Plugin Version WooCommerce PayPal Payments  2.4.3
 

### Additional Details

<details><summary>System status</summary>

</details>

**Comment by NicolasErnult** [comment]
![Screenshot_20231122_092914](https://github.com/woocommerce/woocommerce-paypal-payments/assets/87170879/9369eae0-ccc9-485b-a96d-894058965ac2)

Capture on my website the 22.11.2023 all was ok with the button PayLater Paypal. since update of plugin nothing....

**Comment by Sirvijver** [comment]
Hello @NicolasErnult 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This is a very strange situation, since the Pay Later option is controlled by PayPal and simply displayed in the iFrame if the page is eligible for it. In this case, you are eligible for it, since it is already shown in another page (product/cart). It could be that there is an issue with the checkout page, so you might want to try a completely clean checkout page and see if that changes the situation. You can do this by creating a new page on and only adding the short code [woocommerce_checkout].
If that doesn't show improvement, you might want to check with [PayPal Merchant Technical Support](https://www.paypal-techsupport.com/s/contactsupport) if there is any issue with your account (since they handle this option to be shown or not.

Did you switch back to an earlier version, and it did show up when you reverted to an older version? Please add this to the support ticket you need to open in case you require more support from us, since we will close this thread in GitHub. If you need more support from us, please open a support thread as explained in the top of this response.

Kind regards, 
Joost

**Comment by ghost** [comment]
I already see with Paypal Technical and all is ok
The page of checkout, i create a new and the same error.
For back to old version i try it but i don't find anything (back old version of woocommerce, paypal etc... the same bug

**Comment by jlavnv** [comment]
I'm also stuck in the same situation as you. The Pay Later button no longer appears.

**Comment by ghost** [comment]
the same and with the new version of Woocommerce, the bug is always here....
