### ISSUE TITLE
Deprecation Warnings 'Using ${var} in strings is deprecated'

### ISSUE THREAD

**Issue by SpottedPaint** [woocommerce/woocommerce-paypal-payments#1942]
In the smart button file woocommerce-paypal-payments/modules/ppcp-button/src/Assets/SmartButton.php
there are a number of instances where you do something like "button_{$context}_${style}"
this causes deprecation warnings in PHP 8.3.1 I think those started in PHP 8.2
Deprecated: Using ${var} in strings is deprecated, use {$var} instead

It might appear in other places as well but it seems to be that SmartButton file where it appears for me.
I'm swapping it for something like this "button_".$context."_".$style you might want to handle it in a different way.
This is happening in the latest version available at the moment 2.4.3

I have debug true set on in my local development site wp-config.php to catch my own errors
define('WP_DEBUG', true);
define('WP_DEBUG_DISPLAY', true);
error_reporting(-1);
ini_set('display_errors',1);

**Comment by Sirvijver** [comment]
Hello @SpottedPaint 

This should be address in our next release. Details can be found here: https://github.com/woocommerce/woocommerce-paypal-payments/pull/1939.

I will mark this thread as resolved, but don't hesitate to reach out to us if you have any issues with our plugin. However, it might be more suitable to open an engagement with our support team, since we utilize GitHub mainly for development activities. For support requests, we would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Kind regards, 
Joost
