### ISSUE TITLE
New update on woocommerce has issue

### ISSUE THREAD

**Issue by sileska** [woocommerce/woocommerce-paypal-payments#1960]
after doing the update on woocommerce this morning, the cart does not work

it gives this error

Forbidden
You don't have permission to access this resource.

Apache Server at cccccc.com Port 443

**Comment by Sirvijver** [comment]
Hello @sileska 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue has not been reported by anyone else, and the error sounds like there is an access issue with the Apache server you are using. Did you revert to an older release that did not encounter this issue? If you believe this is a problem with our plugin, please open a support thread as advise above, because without any further details (like system report and logs), we cannot do much. This GitHub thread will now be closed.

Kind regards, 
Joost
