### ISSUE TITLE
Paypal checkout not accept coupon with "free shipping" with minimum order

### ISSUE THREAD

**Issue by daricpt** [woocommerce/woocommerce-paypal-payments#1973]
Hi

When user use the Paypal checkout feature, Paypal show message not accept coupon.
Specifics cupon with "free shipping" with minimum order and remove coupon

Environment
WordPress Version = 6.4.2
WooCommerce Version =7.5.1
Plugin Version = 2.4.2
Browser [e.g. Chrome, Safari] and Version = UNKNOWN

**Comment by Sirvijver** [comment]
Hello @daricpt 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you reported has not been reported before, so we would expect this might be related to another plugin active on your site. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
 Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help, please open a support thread as advise above, since this GitHub thread will be closed.

Kind regards, 
Joost
