### ISSUE TITLE
WordPress caught an error with WooCommerce PayPal Payments.

### ISSUE THREAD

**Issue by FourNaturals** [woocommerce/woocommerce-paypal-payments#1974]
### Describe the Bug

WordPress caught an error with WooCommerce PayPal Payments and they emailed me to notify the host the plugin about the technical issue. The error was caught on this page of my website: https://fournaturalshair.com/wp-admin/admin-ajax.php

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

1. Go to this webpage: https://fournaturalshair.com/wp-admin/admin-ajax.php
2. You'll see there's nothing there but a Zero. This is the issue Wordpress alerted me to. However the plug in doesn't have an error in the menu on my dashboard
3. 
### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @FourNaturals 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The link you provide us to look at is to the backend of your site, so that is not something we can check/access.
The issue sounds like it is probably related to a plugin conflict, so I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you to improve/resolve the situation, please open a support request as advised above. We will now close this thread.

Kind regards, 
Joost
