### ISSUE TITLE
Payment Options not showing on Cart

### ISSUE THREAD

**Issue by trockdesign** [woocommerce/woocommerce-paypal-payments#1976]
All was working. 1st PayPal payment was accepted. No settings have been changed.

Buyers click either PayPal or Venmo to process payment and are then sent back to WP cart to finish checkout. In the cart there is nothing in the "Payments" section (see screenshot) and when you click Place Order it says "No payment method provided." Which is not correct because the user has already approved the payment through Venmo or PayPal. 

Please advise.
<img width="1266" alt="Screenshot 2024-01-20 at 11 02 58 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/157241877/74b1d447-c766-471b-b367-78564b40a0cf">
<img width="1276" alt="Screenshot 2024-01-20 at 11 01 46 AM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/157241877/f00307ef-c067-4086-88f0-856bf0c4d579">

**Comment by lloydud** [comment]
Have also updated the version to 2.5.0 on a previously working checkout but on selecting PayPal as payment option the buttons do not appear. 

Therefore have rolled by to previous version to fix the issue. Ironic really as the PayPal rep is calling the customer cajoling them into updating the plugin.

Hope for a fix soon.

Kind Regards

**Comment by Sirvijver** [comment]
Hello @trockdesign 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The situation, as you describe is, sounds like how it should be functioning. When you have entered your payment details in the product or cart page, you will be only forwarded to the checkout page, in order to verify your details. Here you will not require any PayPal buttons, you only need to press the "Place Order" button.
When you don't have entered the payment details in a previous screen, the payment options should show only in the top of this checkout screen, but in this case, this should not occur.

If this is not a correct statement, and you require more support, please open a support request as advised above. This GitHub thread will be closed.

Kind regards, 
Joost
