### ISSUE TITLE
Payment Options not available on manually created order.

### ISSUE THREAD

**Issue by PrimeAuto1** [woocommerce/woocommerce-paypal-payments#1983]
### Describe the Bug

Customer payment page accessed through a manually created order does not populate Paypal as a checkout option.
### To Reproduce
Worked yesterday before the newest version of paypal payments

### Screenshots

https://i.imgur.com/mpcRc1n.png
https://i.imgur.com/qB3nnx6.png

### Expected Behavior

Paypal/Advanced credit card options should be available.

### Environment

Woocommerce Version 8.5.1
 - WordPress Version 6.4.2
Edge and Brave have the same behaviour.
 - Multi Currency pluging

**Comment by Sirvijver** [comment]
Hello @PrimeAuto1 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have checked the described situation with our plugin version 2.4.3 and 2.5.0 and did not encounter the same situation you have. Can you try to reproduce the situation with only WooCommerce and PayPal Payments activated on your site and see if that shows you the same outcome?

If you believe this is an issue caused by our plugin, please open a support ticket with our support team as described above. This GitHub thread will be closed.

Kind regards, 
Joost
