### ISSUE TITLE
API credentials must be entered to save the settings.

### ISSUE THREAD

**Issue by Kris-84** [woocommerce/woocommerce-paypal-payments#1988]
The plugin suddenly stopped working and I only have the information API credentials must be entered to save the settings.
but there is no field where I can plow it?

WordPress and Woocommerce wersion newest.
![Zrzut ekranu 2024-01-25 114208](https://github.com/woocommerce/woocommerce-paypal-payments/assets/65968730/5aa94869-d801-458e-9caa-78c0ef5cd354)

**Comment by Sirvijver** [comment]
Hello @Kris-84,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The screenshot you showed us, clearly show that only the first 2 of 4 fields are populated. The payment method only works if all 4 fields are populated. You might want to disconnect (save) and onboard your account again in order to resolve this. If this does not help, you could also enter these last 2 fields manually by following [these instructions](https://woo.com/document/woocommerce-paypal-payments/#manual-credential-input). However, the onboarding wizard would always be our advised/preferred option (since it registers some items in the background).

This problem could have been caused by an accidental change, or we have seen this to happen to some merchants when the plugin was updated. We can't be sure how this is caused, but it has never seen to be happening often.

If this does not help you resolve the issue, or it keeps on happening, please open a support ticket with us as advised above. For now, this GitHub thread will be closed.

Kind regards, 
Joost
