### ISSUE TITLE
After upgrading from 1.9.5 to 2.5.1 there are no payment buttons on the checkout page.

### ISSUE THREAD

**Issue by lloydud** [woocommerce/woocommerce-paypal-payments#1990]
After upgrading from 1.9.5 to 2.5.1 there are no payment buttons on the checkout page. Therefore have rolled back to version 1.9.5.

<img width="639" alt="ppal-1" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/16607462/caae30ad-99d5-4a58-9ad6-64b6a56a4e8f">

On inspecting the code where the buttons usually get injected:
<img width="483" alt="ppal2" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/16607462/379845fa-ddd3-4c40-a132-e81f2a48f0e3">

Hope your able to help.

Regards

**Comment by Sirvijver** [comment]
Hello @lloydud 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

In order to help you with this issue, we would need to get more details, like the system report, but for now we can only advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)
.

If this does not help, please open a support ticket as described above, because this GitHub thread will be closed.

Kind regards, 
Joost
