### ISSUE TITLE
Paypal Advanced Card processing not working on front end

### ISSUE THREAD

**Issue by BoulayMarketing** [woocommerce/woocommerce-paypal-payments#2000]
### Describe the Bug

We want to use paypal for customers to be able to enter their credit card in the checkout to purchase products. 
Although everything in the backend is connected and set up correctly. The option is not showing in the checkout. 

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/41753539/6d62de57-2f88-4c8f-a6bc-30eac480aa76)
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/41753539/42e041bd-125b-4050-bd77-58a581204ff4)

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version 
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by tlarsh3** [comment]
@BoulayMarketing i had a similar issue on my site, but mine is caused by how the javascript caching plugins handled the checkout page. Autooptimize and wp rocket would not allow the advanced credit card fields to display. So if you have a caching/minifying plugin installed start with deactivating that, clearing cache and seeing if it begins to show up. 

I will say these last few Paypal plugin updates have been atrocious to the point sales stopped funneling in on our websites.

**Comment by InpsydeNiklas** [comment]
Hi @BoulayMarketing, as mentioned in #1462, the Advanced Card Processing gateway does not yet support the new Checkout block. For now, it requires either the Classic Checkout block or the `[woocommerce_checkout]` shortcode to appear. 

While this is not a cache issue, we still recommend excluding the PayPal scripts from the cache or script minify: https://woo.com/document/woocommerce-paypal-payments/#faq-paypal-smart-buttons-not-loading
If you need additional assistance with the setup or encounter any problems, I recommend [contacting the support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
