### ISSUE TITLE
Paypal transaction doesn't contain any details about specific positions. Just a total.

### ISSUE THREAD

**Issue by buddy-kilo** [woocommerce/woocommerce-paypal-payments#2011]
Many times I have noticed that Paypal transaction doesn't contain any details about positions. Just a total. 

![Screenshot 2024-02-01 at 17 19 34 - blured](https://github.com/woocommerce/woocommerce-paypal-payments/assets/124056745/c256ec08-358c-412d-8794-889926cfd71d)

<img width="1107" alt="Screenshot 2024-02-01 at 17 38 41" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/124056745/0e225ab1-098a-4a0d-a187-8353e0e859e0">

**Comment by buddy-kilo** [comment]
Also noticed this note:

<img width="317" alt="Screenshot 2024-02-01 at 17 48 21" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/124056745/409daccd-6214-4663-b6f7-3d43be29b108">

**Comment by InpsydeNiklas** [comment]
Hi @buddy-kilo, in the PayPal Payments settings Connection tab, you can change the `Subtotal Mismatch Behavior` setting to `Add another line item` to preserve the product details when there is a mismatch. Mismatches can happen because WooCommerce and PayPal calculate taxes differently and PayPal would reject payments if the totals don't match.
More details can be found here: https://woo.com/document/woocommerce-paypal-payments/#integration-configuration
If you need additional guidance, I recommend [contacting the support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
