### ISSUE TITLE
Shipping not being charged

### ISSUE THREAD

**Issue by leohenning** [woocommerce/woocommerce-paypal-payments#2022]
### Describe the Bug

We are having issues with direct card payments. The transaction ID we are getting in woocommerce is wrong and when we do find the payment the shipping is not included however, the invoice to the client shows shipping.

### To Reproduce

customer orders on the website with direct card payments and has a shipping charge.

### Screenshots

![Screenshot 2024-02-09 at 9 48 30 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4871423/fdfb477b-81ba-410e-82bc-aa032ce6b5e6)
![Screenshot 2024-02-09 at 9 50 28 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4871423/5e18aaf7-3698-4a6c-805e-44897176e16a)
[Transaction details - PayPal.pdf](https://github.com/woocommerce/woocommerce-paypal-payments/files/14223111/Transaction.details.-.PayPal.pdf)
![Screenshot 2024-02-09 at 9 47 46 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4871423/4e13bb7f-a13f-4ceb-94d2-9a623f6e3ea0)

### Expected Behavior

we expect it to charge shipping.
we expect the transaction number to exist

### Actual Behavior

It does not charge for shipping

### Environment

WooCommerce version: |   | 8.5.2
WooCommerce REST API package: |   | 8.5.2 /
WooCommerce Blocks package: |   | 11.8.0-dev /
Action Scheduler package: |   | 3.7.1 /
Log directory writable: |   | /
WordPress version: |   | 6.4.3

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by leohenning** [comment]
![Screenshot 2024-02-09 at 9 57 04 AM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/4871423/ca80fc6c-bc08-455b-8f45-9e905b0e1bb6)

you can see shipping is not added in the transaction. that matches the order. and the transaction ID is different it is [5GX5934472138320C](https://www.paypal.com/activity/payment/5GX5934472138320C?scid=Szg3ODZWSldWSlhHVTE3MDc0MTUxMTM2Mjk=)

**Comment by leohenning** [comment]
Here is the response from PayPal
Hi Leo,

Thank you for contacting Merchant Technical Support.

I am sorry to hear of the troubles with these direct card payments. For the example provided, 5NF87303PS0779720 is a token ID that was used to setup the completed payment 5GX5934472138320C. When searching in your account, you would use 5GX5934472138320C. In reviewing our technical logs, there was no separate shipping amount sent to our system for processing so please reach out to WooCommerce as to why they display the token ID and to why they don't separate out the shipping amount to us at the time of processing. Thank you for your patience and I hope you have a great weekend!

Sincerely,

Jeremy
Global Technical Support
PayPal, Inc.

**Comment by Sirvijver** [comment]
Hello @leohenning 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This is a strange situation that we have not seen before. It is very strange that the PayPal Transaction ID's are mixed. I would expect there is an element on your site that is causing this issue, otherwise we would have seen this issue occur more often. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you isolate the cause of this issue, please open a private engagement with us as explained above, because this GitHub thread will be closed.

Kind regards, 
Joost

**Comment by leohenning** [comment]
I have reached out and have gotten no response. A full conflict test is not
possible in a production environment. I have reached out to the support
team and have not gotten a response. How do I see my support request? How
do I open a private engagement? I don't see it described above.

Leo
