### ISSUE TITLE
Credit card fields at checkout are blanked out and unable to be filled in. 

### ISSUE THREAD

**Issue by ProjectNovaGG** [woocommerce/woocommerce-paypal-payments#2023]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by ProjectNovaGG** [comment]
Sorry didn't notice fields above. 

It's taking place at the time of checkout on my website @ https://lone.design/checkout/
On the right you'll see the pay with paypal and just above will be the fields for credit card info.
![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/69168906/5b605d0b-7f66-4fbe-b6fe-862f1b4adb4d)

**Comment by Sirvijver** [comment]
Hello @ProjectNovaGG 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This looks like a theme issue, but we cannot verify this, since your website requires a login in order to get to the checkout page. I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this does not help you isolate the cause for this issue, please open a private support ticket with us as explained above, since this GitHub thread will be closed.

Kind regards, 
Joost
