### ISSUE TITLE
"Place Order" Button disappears when Paypal Debit/Credit option selected

### ISSUE THREAD

**Issue by aidancurry** [woocommerce/woocommerce-paypal-payments#2028]
### Describe the Bug

When using the "Paypal Credit/Debit" option to checkout on our website the "Place Order" button disappears.

We currently have 3-4 payment processors and all of them display a "place order" button. However, when you select "Credit/Debit Paypal" this button disappears. This is blocking users from checking out with this payment method. However, I did figure out a workaround where you can enter your cursor into the card number section and hit enter to bypass needing to click the button.

### To Reproduce

1) Go to: https://hotspotrf.com/shop/
2) Add item to cart
3) Go to checkout.
4) Select "Debit/Credit (Paypal)"

You will notice that the button disappears.

### Screenshots
<img width="570" alt="Screenshot 2024-02-13 at 4 09 30 PM" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/82642054/1a930436-8bdd-4eb4-a909-1635134f8fc4">

### Expected Behavior

The button should not disappear.

### Actual Behavior

The Place Order button disappears.

### Environment

 - WordPress Version: 6.4.3
 - WooCommerce Version: 8.5.1
 - Plugin Version: "WooCommerce PayPal Payments": Version 2.4.3
 - Browser [e.g. Chrome, Safari] and Version: Chrome 
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @aidancurry 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have had a look at the checkout page and see indeed that the Advanced Card Processing payment button is not being displayed as expected. Most o the time this happens, it is caused by the theme or additional CSS. For this reason, I think you should start by replacing your current theme with the [default theme Storefront](https://wordpress.org/themes/storefront/) 

If that doesn't show an improvement, you may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.
 Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If this all does not show any improvement or show you what the cause is of this issue, please open a support ticket as explained above. This GH thread will be closed.

Kind regards, 
Joost
