### ISSUE TITLE
IDEAL payment over PayPal not received but payed

### ISSUE THREAD

**Issue by vanteckel** [woocommerce/woocommerce-paypal-payments#2030]
### Describe the Bug

A customer payed in the shop with IDEAL over PayPal. The payment gone off his account but we haven't received an order, an email or a payment. 

### Environment

 - WordPress Version: 6.4.3
 - WooCommerce Version: 8.5.2
 - Plugin Version WooCommerce Paypal Payments: 2.5.3
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @vanteckel 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

iDEAL and other [alternative payment methods](https://woocommerce.com/document/woocommerce-paypal-payments/#alternative-payment-methods) are "push payments" that debit the customer's bank account immediately upon transaction authorization. 
Once the payment is completed, the buyer should be redirected to the order-received page, and the payment should be captured automatically. If no order was created in WooCommerce and the payment wasn't captured, it may be due to improperly registered or received webhooks or the buyer not completing the checkout process correctly.
Some users have reported issues with mobile payments made through banking apps, but we haven't been able to confirm this. When testing with a PayPal sandbox account, alternative payment methods usually work as expected, but this doesn't simulate the flow through a banking app. It may be helpful to ask the customer how they completed the payment (e.g., using a banking app on a phone or via a web browser).

Just so you know, if the plugin doesn't capture the payment within three hours, PayPal typically issues an automatic refund, which should appear in the buyer's account within a few days, as SEPA transactions usually take a day to process.
We recommend that you [verify the webhook registration](https://woocommerce.com/document/woocommerce-paypal-payments/#webhook-status) to ensure that APM payments can process correctly. Beyond this, you can enable [WooCommerce order creation via webhooks with this filter](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#webhook-order-creation). If the buyer doesn't return to the Checkout after the payment, the order may be created and captured after the webhook is received.

Alternatively, any [alternative payment method can be disabled](https://woocommerce.com/document/woocommerce-paypal-payments/#disable-APMs), e.g. via the Disable Alternative Payment Methods setting in the Standard Payments tab.

If this did not answer your question, please open a support thread as advised above. This thread will be closed.

Kind regards, 
Joost
