### ISSUE TITLE
Refund not working

### ISSUE THREAD

**Issue by FelixLuckyPastor** [woocommerce/woocommerce-paypal-payments#2036]
### Describe the Bug

After a shop transaction is completed and payment received via Paypal, I need to refund part of the payed amount. I re-set the order to 'Payment open' and enter an amount to refund. I get two options, 'refund manually' and 'Refund via Paypal'. Choosing the latter, and confirming, I get the error msg:
Es ist ein Fehler aufgetreten während versucht wurde eine Erstattung an die API des entsprechenden Zahlungswegs zu übermitteln.
(An error occurred while trying to submit a refund to the API of the corresponding payment method.)

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @FelixLuckyPastor 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue can occur by some different causes with our plugin, but can simply be avoided by performing the refund via the PayPal website, when you click on the Transaction ID. I have seen in the past that this failure occurred when I change the PayPal ID on my test environment, but it could be that other aspects can also cause this problem, like a previous change of the order details. 
Another possible cause would be that there is something blocking the webhooks that are related to the refunds. You can test the webhooks, by going to the tab "Connection" in the settings page and using the "Simulate" & "Resubscribe" options, so see if they are fully functional. If there is an issue with the webhooks, you might want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

Please see if any of these options can help you correct this behavior and open a new thread if you still have any more questions for us, because this thread will be closed.

Kind regards, 
Joost
