### ISSUE TITLE
Proceed to PayPal text

### ISSUE THREAD

**Issue by miniMAC** [woocommerce/woocommerce-paypal-payments#2055]
### Describe the Bug

Impossible in options, to change the text in checkout page "Proceed to PayPal"

### To Reproduce

1. go with a product to checkout
2. select paypal method

### Screenshots

![Screenshot 2024-02-24 alle 21 41 44](https://github.com/woocommerce/woocommerce-paypal-payments/assets/1235741/43af1173-2ad1-4ad2-9124-a4e0c75f90c1)

### Expected Behavior

I'm expected an option to chage the text

### Environment

 - WordPress 6.4.3
 - WooCommerce 8.6.1
 - Plugin 2.5.3

**Comment by Sirvijver** [comment]
Hello @miniMAC 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This option "Proceed to PayPal" is a backup option that is shown when the defautl smartbuttons are not possible to be shown. You can try to display the default PayPal buttons, by deactivating the current theme and using f.e. [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

This button text cannot be adjusted, so there is no option to do this on this backup version. The only option you have to adjust the text of the button, is the drop-down options for the smart buttons you have under the setting "Button Label".

If you have any more questions, please open a private engagement via the link provide above, because this thread will be closed.

Kind regards, 
Joost

**Comment by Sirvijver** [comment]
Hello @miniMAC,

sorry, it seems there a way to change the "Proceed to PayPal" text on the button in the block checkout. It can be changed via translation files or [with a filter](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-checkout-smart-buttons) but there is no UI in the plugin to do this. 

This example filter would change it to the "Place order" string from the WooCommerce plugin:
//Change the button label - defaults to "Proceed to PayPal"
add_filter('woocommerce_paypal_payments_place_order_button_text', function() {
    return __( 'Place order', 'woocommerce' );

Hopefully this helps you get the outcome you are looking for.

Kind regards, 
Joost

**Comment by miniMAC** [comment]
Many thanks!
