### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by Lerie82** [woocommerce/woocommerce-paypal-payments#2056]
Fatal error: Uncaught TypeError: WooCommerce\PayPalCommerce\ApiClient\Entity\Address::__construct(): Argument #1 ($country_code) must be of type string, bool given, called in C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-api-client\src\Factory\AddressFactory.php on line 41 and defined in C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-api-client\src\Entity\Address.php:69 Stack trace: #0 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-api-client\src\Factory\AddressFactory.php(41): WooCommerce\PayPalCommerce\ApiClient\Entity\Address->__construct(false, '', '', '', '', '') #1 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-api-client\src\Factory\PayerFactory.php(111): WooCommerce\PayPalCommerce\ApiClient\Factory\AddressFactory->from_wc_customer(Object(WC_Customer), 'billing') #2 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-button\src\Assets\SmartButton.php(1233): WooCommerce\PayPalCommerce\ApiClient\Factory\PayerFactory->from_customer(Object(WC_Customer)) #3 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-button\src\Assets\SmartButton.php(1069): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->payerData() #4 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-blocks\src\PayPalPaymentMethod.php(212): WooCommerce\PayPalCommerce\Button\Assets\SmartButton->script_data() #5 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\Payments\PaymentMethodRegistry.php(62): WooCommerce\PayPalCommerce\Blocks\PayPalPaymentMethod->get_payment_method_data() #6 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\Payments\Api.php(92): Automattic\WooCommerce\Blocks\Payments\PaymentMethodRegistry->get_all_registered_script_data() #7 C:\xampp\htdocs\scaryclothes.com\wp-includes\class-wp-hook.php(324): Automattic\WooCommerce\Blocks\Payments\Api->add_payment_method_script_data('') #8 C:\xampp\htdocs\scaryclothes.com\wp-includes\class-wp-hook.php(348): WP_Hook->apply_filters('', Array) #9 C:\xampp\htdocs\scaryclothes.com\wp-includes\plugin.php(517): WP_Hook->do_action(Array) #10 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\BlockTypes\Checkout.php(375): do_action('woocommerce_blo...') #11 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\BlockTypes\AbstractBlock.php(415): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_data(Array) #12 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\BlockTypes\Checkout.php(126): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->enqueue_assets(Array, '\n<div class="wp...', Object(WP_Block)) #13 C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce\src\Blocks\BlockTypes\AbstractBlock.php(95): Automattic\WooCommerce\Blocks\BlockTypes\Checkout->enqueue_assets(Array, '\n<div class="wp...', Object(WP_Block)) #14 C:\xampp\htdocs\scaryclothes.com\wp-includes\class-wp-block.php(258): Automattic\WooCommerce\Blocks\BlockTypes\AbstractBlock->render_callback(Array, '\n<div class="wp...', Object(WP_Block)) #15 C:\xampp\htdocs\scaryclothes.com\wp-includes\blocks.php(1484): WP_Block->render() #16 C:\xampp\htdocs\scaryclothes.com\wp-includes\blocks.php(1522): render_block(Array) #17 C:\xampp\htdocs\scaryclothes.com\wp-includes\class-wp-hook.php(324): do_blocks('<!-- wp:woocomm...') #18 C:\xampp\htdocs\scaryclothes.com\wp-includes\plugin.php(205): WP_Hook->apply_filters('<!-- wp:woocomm...', Array) #19 C:\xampp\htdocs\scaryclothes.com\wp-includes\post-template.php(256): apply_filters('the_content', '<!-- wp:woocomm...') #20 C:\xampp\htdocs\scaryclothes.com\wp-content\themes\amberd-online-store\template-parts\content\woocommerce-content.php(6): the_content() #21 C:\xampp\htdocs\scaryclothes.com\wp-includes\template.php(792): require('C:\\xampp\\htdocs...') #22 C:\xampp\htdocs\scaryclothes.com\wp-includes\template.php(725): load_template('C:\\xampp\\htdocs...', false, Array) #23 C:\xampp\htdocs\scaryclothes.com\wp-includes\general-template.php(206): locate_template(Array, true, false, Array) #24 C:\xampp\htdocs\scaryclothes.com\wp-content\themes\amberd-online-store\page.php(8): get_template_part('template-parts/...') #25 C:\xampp\htdocs\scaryclothes.com\wp-includes\template-loader.php(106): include('C:\\xampp\\htdocs...') #26 C:\xampp\htdocs\scaryclothes.com\wp-blog-header.php(19): require_once('C:\\xampp\\htdocs...') #27 C:\xampp\htdocs\scaryclothes.com\index.php(17): require('C:\\xampp\\htdocs...') #28 {main} thrown in C:\xampp\htdocs\scaryclothes.com\wp-content\plugins\woocommerce-paypal-payments\modules\ppcp-api-client\src\Entity\Address.php on line 69

**Comment by Sirvijver** [comment]
Hello @Lerie82 ,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This seems to be a conflict that is causing our checkout validation to interpret the country field incorrectly. I would expect that another plugin on your site might be causing this issue, so I would advise you to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/).

In order to do this, you will need to be able to reproduce the issue, but you did not provide this or any other details when opening this thread. If you require additional support, I advise you to open a support request as explained above. This thread will now be closed.

Kind regards, 
Joost
