### ISSUE TITLE
29 Feb 2024, upgrading the Plugin and got Critical Error, dead of WP Critical Error screen.

### ISSUE THREAD

**Issue by UnionCameraLtd** [woocommerce/woocommerce-paypal-payments#2065]
### To Reproduce

1. Go to 'Dashboard'  and "Plugins"
2. Click on 'Update for the Plugin'
3.Critical Error page...

### Screenshots

No need. Everybody see that before...

### Actual Behavior

Just tried to update the Plugin and got error.

### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.6.1 
 - Plugin Version 2.5.3 
 - Browser Any
Google Site Kit, OceanWP and its stuff, Bring Web Master, Yoast SEO, etc.... (Hard to generate a list in short)

### Additional Details

<details><summary>System status</summary>

  ```

  ```

</details>

**Comment by Sirvijver** [comment]
Hello @UnionCameraLtd 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We have not received any similar reports from other merchants, so we would expect this issue to be caused by some custom code or specific plugin present on your site. You may want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists. Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

First thing you should do, is to revert your live site, so this can function with the previous setup. Then create a [staging site](https://wordpress.org/plugins/wp-staging/) and see if you can install the new version of our plugin, when all other plugins (except WooCommerce and PayPal Payments) are deactivated.

If this does not help you find the cause for this problem, please open a support thread as advised above, as this thread will be now closed.

Kind regards, 
Joost
