### ISSUE TITLE
paypal the custom callback only has the order ID, but woocommerce uses it here $custom = json_decode( $raw_custom );

### ISSUE THREAD

**Issue by huyufan** [woocommerce/woocommerce-paypal-payments#2066]
- WordPress 6.4.2
 - WooCommerce 8.5.1
 - WooCommerce PayPal Payments  2.5.4

### Additional Details

ipn setting http://example.com/?wc-api=WC_Gateway_Paypal

Custom returns an int type. Why is json_decode used? How to solve it?  this  get_paypal_order() 

  ```
$order = ! empty( $posted['custom'] ) ? $this->get_paypal_order( $posted['custom'] ) : false;
protected function  get_paypal_order( $raw_custom ) {
		// We have the data in the correct format, so get the order.
		$custom = json_decode( $raw_custom );
		if ( $custom && is_object( $custom ) ) {
			$order_id  = $custom->order_id;
			$order_key = $custom->order_key;
		} else {
			// Nothing was found.
			WC_Gateway_Paypal::log( 'Order ID and key were not found in "custom".', 'error' );
			return false;
		}

		$order = wc_get_order( $order_id );

		if ( ! $order ) {
			// We have an invalid $order_id, probably because invoice_prefix has changed.
			$order_id = wc_get_order_id_by_order_key( $order_key );
			$order    = wc_get_order( $order_id );
		}

		if ( ! $order || ! hash_equals( $order->get_order_key(), $order_key ) ) {
			WC_Gateway_Paypal::log( 'Order Keys do not match.', 'error' );
			return false;
		}

		return $order;
	}
  ```
</details>

```[tasklist]
### Tasks
```

**Comment by huyufan** [comment]
Can you help me explain the reasons behind it? I have set up a callback notification in PayPal's IPN, and in the IPN's history, the parameters are as follows. IPN Message is
```
notify_version=3.9&custom=5153&payer_status

\plugins\woocommerce\includes\gateways\paypal\includesclass-wc-gateway-paypal-ipn-handler.php  code is

if ( $custom && is_object( $custom ) ) {
  		$order_id  = $custom->order_id;
  		$order_key = $custom->order_key;
  	} 

custom is int  why use is_object() ？
```

**Comment by huyufan** [comment]
custom  The free-form text field entered by the merchant during checkout. but The callback record processing process for this field is different between payment and ipn. Why is one int and the other json?

**Comment by InpsydeNiklas** [comment]
Hi @huyufan, the code you referenced is from the PayPal Standard integration, which is part of the WooCommerce plugin and unrelated to the PayPal Payments plugin. For questions about WooCommerce or PayPal Standard, you can reach the [Woo support team here](https://woo.com/my-account/contact-support/).
PayPal Payments [relies on webhook instead of PayPal IPN](https://woo.com/document/woocommerce-paypal-payments/#webhook-status). If you need any assistance setting up PayPal Payments, I recommend that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) for additional guidance. Thank you!
