### ISSUE TITLE
Unable to change colors

### ISSUE THREAD

**Issue by Flykod** [woocommerce/woocommerce-paypal-payments#2110]
### To Reproduce

1. Go to '/wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway&ppcp-tab=ppcp-pay-later'
2. Click on 'Product Page > Text Color | Cart > Text Color | Checkout > Text Color '
3. Select any option (other than the first "Black / Blue logo") and try to save;  Only "Black / Blue logo" remains saved (perhaps because it is the first option);

### Expected Behavior

What is expected is that when selecting one of the options, it will be saved. My website has a dark background, so I need a light color.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @DwebDigital 

We are aware of this problem. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by Flykod** [comment]
Hello SydeKrystian,

Thanks for the clarifications.
I clicked the "Submit a bug" button inside the plugin's configuration page, which brought me to GitHub.

Perhaps an improvement would be to redirect the link to the appropriate location instead of GitHub.

Thank you again!

**Comment by InpsydeNiklas** [comment]
Hi @DwebDigital, thanks for the issue report and apologies for the mixup. This issue is indeed a bug in the 2.6.0 release, and you have done everything right. This problem has been addressed in the [linked PR](https://github.com/woocommerce/woocommerce-paypal-payments/pull/2107), which will be part of the next update.
As a workaround, you could either disable the new messaging configurator with [this code snippet](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-pay-later-messaging-configurator-in-260) to bring back the legacy configuration (text color setting should save correctly then), or downgrade to 2.5.4 and save your preferred text color, or contact our support team as mentioned above to get a plugin version with the fixed messaging configurator. I hope this helps!

**Comment by Flykod** [comment]
Hello InpsydeNiklas,

Thanks for the snippet, I'll use it until the new version comes out.
By the way, it's a great job from all of you, congratulations!
