### ISSUE TITLE
Security header is not valid

### ISSUE THREAD

**Issue by tomcoady** [woocommerce/woocommerce-paypal-payments#2121]
### Describe the Bug
 Whenever I attempt to initiate a refund I see the same error message: Security header is not valid

### To Reproduce

1. Go to order page
2. Scroll to refund link
3. click on refund 

### Screenshots

Not helpful as they only show the same message

### Expected Behavior

Using stripe I am presented with the list of items and boxes to enter refund amounts
### Actual Behavior

Only error message
### Environment

 - WordPress Version 6.4.3
 - WooCommerce Version 8.7.0
 - Plugin Version 2.6.0 https://woocommerce.com/products/woocommerce-paypal-payments/
 - Browser Safari Version 17.4.1 (19618.1.15.11.14)
 - Any other plugins installed

### Additional Details

I searched for this error code in PayPal help and community forums but found no mention of similar

**Comment by Sirvijver** [comment]
Hello @tomcoady,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We have already had a look in our support archive, but we did not have any similar error notifications in there, so there is no way I can give you a response purely on this error notification. In order to help you, we would need more details like a system report and logs after attempting the refund. The best way to continue is to get you to open a support request as described above, because we will close this request.

Kind regards, 
Joost
