### ISSUE TITLE
Payment Gateway not working

### ISSUE THREAD

**Issue by amit9827** [woocommerce/woocommerce-paypal-payments#2128]
### Describe the Bug

Failed to process the payment. Please try again or contact the shop admin. [INVALID_REQUEST] Request is not well-formed, syntactically incorrect, or violates schema. https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_PARAMETER_SYNTAX https://developer.paypal.com/docs/api/orders/v2/#error-INVALID_STRING_LENGTH

### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @amit9827,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

We sometimes see this error when product attributes (name, description, etc) contains text/characters that can be interpreted differently and cause longer strings when being sent to the PayPal Server. When text and an emoji like this 😉 in the first 127 characters are sent to PayPal, then the API responds with INVALID_STRING_LENGTH because the emoji would make the string longer than the maximum. We have put some fixes in place for this in the past, but it seems there are certain 3rd party plugins that can still cause this error to be triggered.

You may also want to perform a full conflict test to rule out eventual issues with the theme or a different plugin. We recommend temporarily activating the [default theme Storefront](https://wordpress.org/themes/storefront/) and disabling all other plugins except for WooCommerce and PayPal Payments to see if the behavior persists.

Here's a guide that explains the steps in more detail: [How to test for conflicts](https://woocommerce.com/document/how-to-test-for-conflicts/)

If none of this guides you to the cause/solution of this issue, please open a support request as advised before.

Kind regards, 
Joost
