### ISSUE TITLE
No es posible procesar el pago 

### ISSUE THREAD

**Issue by okarcreativo** [woocommerce/woocommerce-paypal-payments#2133]
### Describe the Bug

Al darle click al pagar con paypal  sale este mensaje
"No es posible procesar el pago con su cuenta de PayPal en este momento. Regrese al sitio web del comercio e intente utilizar otra forma de pago"

### Reproducir

<H2>CASO 1 </H2>
1. Go to 'https://kandalsacademia.com/courses/ropa-interior/  "click' en comprar ahora"
2. colocar correo como invitado o resgistrarse  "click en realizar pedido"
3. mensaje de error "Tenemos problemas técnicos en este momento. Inténtelo de nuevo más tarde. "'

<H2>CASO </H2>
1. Go to 'https://kandalsacademia.com/producto/keychains/ 'click'  'PAYPAL " or  click 'pay later' 
 2. resgistrarse con cuenta paypal  "pagar con paypal" 'Telefono o correo electronico' 
3. mensaje de error "No es posible procesar el pago con su cuenta de PayPal en este momento. Regrese al sitio web del comercio e intente utilizar otra forma de pago. "'

### Screenshots
![keychains](https://github.com/woocommerce/woocommerce-paypal-payments/assets/84940314/a9c183a9-d5a0-4079-b9d0-8a6bb4a9c0f6)
![ropa-interior](https://github.com/woocommerce/woocommerce-paypal-payments/assets/84940314/e6d48dac-7193-40c7-889a-287eac6ab7b2)

### Environment

 - WordPress Version [versión 6.4.3.
 - WooCommerce Versión 8.7.0
 - WooCommerce PayPal Payments version Versión 2.6.0 
 - Browser [e.g. Chrome, Edge, Fire fox] and Version
 - Any other plugins installed
LearnPress  Versión 4.2.6.4 
eduma Version 5.4.5 
WooCommerce Add-On for LearnPress Version: 4.1.4

 -

### Additional Details

<details><summary>System status</summary>

  ```
  <!--Si corresponde, pegue el estado del sistema aquí. Asegúrese de redactar o eliminar cualquier información de identificación. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @okarcreativo,

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue is related to the PayPal account and is not something that is caused by the plugin. However, I did encounter this myself before, and usually you can correct this behavior, by logging into the [PayPal account](developer.paypal.com](https://developer.paypal.com/) and logging out of this account. Simply being logged out of the account, should correct this behavior.

If this still does not help you resolve this issue, please open a support request as described above, since this thread will be closed.

Kind regards, 
Joost
