### ISSUE TITLE
Pay in 4 message showing on WooCommerce Category page

### ISSUE THREAD

**Issue by itsnidhu** [woocommerce/woocommerce-paypal-payments#2143]
### Describe the Bug
I am seeing the Pay in 4 message on all category page that has subcategory. Please see attached. 

<img width="654" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/29530213/9be28712-ef86-404f-b406-14771e9d5143">

### To Reproduce

1. Go to '[…](https://vibrant-interiors.com.au/)' website
2. Click on Decorative Cushions category and/or Fashion category. Note both have sub-category and only these categories are showing "Pay in 4 interest-free payments message.  Bone Inlay has no sub-category and believe that reason I am not seeing the Pay in 4 message display. 
3. The message is showing even after the Shop check box is disabled in WooCommerce > Settings > Payment > Pay later tab. See pic attached of my settings.

<img width="260" alt="image" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/29530213/f652fb1b-05c8-4f9d-b705-0cb16c668c05">

### Expected Behavior

The expected behavior should be the banner to not display on categories page as it is not making sense to show 4 installment payments for the first product on the category page.

### Environment

 - WordPress Version: 6.4.3
 - WooCommerce Version : 8.7.0
 - Theme : Kalles Wordpress theme purchased from themeforest 
  - Browser [e.g. Chrome, Safari]: showing on all browsers and mobile.

Please suggest the solution at earliest. The website is live and would like to fix the issue.

**Comment by InpsydeNiklas** [comment]
Hi @itsnidhu, in version 2.6.0, some sites may not have reflected the changes in the messaging configurator after saving. They should be visible after manually reloading the page, though. That said, this issue was addressed in the latest 2.6.1 update. 
If any issues or questions remain after updating to this version, please consider [contacting our support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
