### ISSUE TITLE
"Pay later" Banner cannot be hidden

### ISSUE THREAD

**Issue by LittleLounge** [woocommerce/woocommerce-paypal-payments#2151]
Hello,

We want to switch off the "Pay Later" banner in some parts of our store. For example, it should not be visible in the shopping cart. But every time we deactivate and save the checkboxes in the WooCommerce settings, they are checked again.

<img width="1211" alt="Bildschirmfoto 2024-04-10 um 10 42 58" src="https://github.com/woocommerce/woocommerce-paypal-payments/assets/166599988/665794ba-7734-482e-8c99-a73b84069a02">

**Comment by InpsydeNiklas** [comment]
Hi @LittleLounge , in version 2.6.0, some sites may not have reflected the changes in the messaging configurator after saving. They should be visible after manually reloading the page, though. That said, this issue was addressed in the latest 2.6.1 update. 
If any issues or questions remain after updating to this version, please consider [contacting our support team directly](https://woo.com/document/woocommerce-paypal-payments/#get-help). Thank you!
