### ISSUE TITLE
KLARNA SOFORT ist still  available 

### ISSUE THREAD

**Issue by Konradattelematika** [woocommerce/woocommerce-paypal-payments#2160]
Describe the Bug
When using the PayPal plugin in WooCommerce, users are still able to select "Klarna Sofort" as a payment method on the checkout page, even though PayPal has deprecated this method and it should not be available.

To Reproduce
Navigate to the checkout page in the WooCommerce store.
Proceed to the payment section.
Observe that "Klarna Sofort" is available as a payment method.
Screenshots
N/A

Expected Behavior
"Klarna Sofort" should not be displayed as a payment method option on the checkout page, as it has been deprecated by PayPal.

Actual Behavior
"Klarna Sofort" is displayed as a payment method option on the checkout page, even though it should not be available.

Environment
WordPress Version: 6.5.2
WooCommerce Version: [Insert WooCommerce Version]
Plugin Version: [Insert PayPal Plugin Version]
Browser: [e.g., Chrome version X.X.X]
Other Plugins Installed: [List any other plugins installed]
Additional Details
The issue persists despite PayPal's deprecation of the "Klarna Sofort" payment method. This poses a problem for users and may lead to confusion during checkout.

<details><summary>System status</summary>

**Comment by InpsydeNiklas** [comment]
Hi @Konradattelematika, this is expected behavior as the PayPal Payments plugin doesn't directly control which payment methods are provided. The last plugin update only removed all references to Sofort (settings/icons), but it will only fully disappear once PayPal removed it:
https://securepayments.paypal.com/ca/cshelp/article/sofort-deprecation-help1145

> Sofort is being deprecated by Klarna as a payment method this year. Sofort will no longer be available through PayPal as of **April 18, 2024**.

> **When do these changes take effect?**
Sofort for merchants:
Effective **April 18, 2024**, Sofort will be suspended as a payment method through your PayPal integration for all merchants. This also applies to Partners, who should also stop offering Sofort to their merchants. PayPal's [Alternative Payment Methods Agreement](https://www.paypal.com/legalhub/apm-tnc) (accessible via the [PayPal Legal Hub](https://www.paypal.com/legalhub)) will also be updated on May 28, 2024, to remove Sofort from the list of available payment methods offered as part of PayPal's APM functionality.
No extensions beyond April 18, 2024, will be provided.

> **Am I impacted by the deprecation if I am an existing merchant who already accepts Sofort?**
Yes, existing merchants who already accept Sofort will not be able to continue processing Sofort payments after April 18, 2024. We recommend that you start migrating to the alternative options listed above to ensure the least interruption to your business.


You don't need to take any action, as the payment method will disappear automatically when the time has come.
