### ISSUE TITLE
onboarding wizard not working

### ISSUE THREAD

**Issue by linnetgonzalez** [woocommerce/woocommerce-paypal-payments#2218]
onboarding wizard for woocommerce paypal plugin is not working it shows the following error:
"We could not complete the onboarding process. Some features, such as card processing, will not be available. To fix this, please try again."
ive tried deleting the plugin and reinstalling and it doesnt help.

**Comment by SydeKrystian** [comment]
Hello @linnetgonzalez 
﻿
Thanks for reaching out to us, we're here to help.

Occasionally, the onboarding wizard might encounter issues. This can be due to interference from certain plugins during the connection process. If you're facing challenges connecting your PayPal account, a proven solution is to input your credentials manually. For a step-by-step guide on this manual method, you can refer to this tutorial: [https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input)  
  
Let us know if the issue persists after using this method, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
