### ISSUE TITLE
PayPal payment gets an error: Duplicate payment

### ISSUE THREAD

**Issue by wannawebdesign** [woocommerce/woocommerce-paypal-payments#2242]
### Describe the Bug

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The transaction has been refused because the Invoice ID already exists. Please create a new order or reach out to the store owner. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID PayPalGateway.php:707 [UNPROCESSABLE_ENTITY]

### To Reproduce

On the HSATV.ca website we could not purchase any items (trail passes). If we tried to use express payment or go all the way through the shopping cart (1) select item from products, then enter date for pass validation and Add to cart. (2) fill out all of the contact information and click "proceed to Paypal"... sign in to Paypal. Select payment. Paypal would return back to the checkout page but nothing would happen. So you select the Paypal button or proceed to Paypal again and then you get an error. The following is the error in the order: 

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The transaction has been refused because the Invoice ID already exists. Please create a new order or reach out to the store owner. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID PayPalGateway.php:707 [UNPROCESSABLE_ENTITY] The transaction has been refused because the Invoice ID already exists. Please create a new order or reach out to the store owner. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID OrderEndpoint.php:346 Order status changed from Pending payment to Failed.

### Environment

 - WordPress Version 6.5.3
 - WooCommerce Version 8.8.3
 - Plugin Paypal Payments version 2.7.0

 - Browser Chrome, Safari latest version mobile and desktop
 - Any other plugins installed
 -  - Plugin Advanced Product Fields for WooCommerce 1.6.7

### Additional Details

**THIS WAS WORKING BEFORE THE NEWEST UPDATES TO THE ABOVE PLUGINS!**

I found a work-around for this: I went into my client's PayPal account and selected 'Allow duplicate payments'. Payments are now working... but there is definitely a problem with the latest version of the plugin Woocommerce Paypal Payments. 
I was trying to find where I could download the previous version of the plugin but I couldn't find it. I couldn't use a backup of the website because I would lose the history of the orders.

**Comment by SydeKrystian** [comment]
Hello @wannawebdesign 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

The error DUPLICATE_INVOICE_ID error is a security feature from PayPal that aims to prevent accidental double payments.

PayPal Payments automatically sets an “invoice prefix” and then sends the WooCommerce order numbers in the pattern “invoice prefix+ordernumber” to PayPal. So when your prefix is set to “cfbdg-” and your order number is “123”, PayPal Payments sends the invoice ID “cfbdg-123” to PayPal.

Under certain circumstances, for example, when you restore a backup from your website, it is possible that the most recent WooCommerce orders do not exist anymore after the restore.

So as soon as WooCommerce attempts to create a new order with the number 123 and the same invoice prefix, PayPal throws this error to prevent accidental double payments because there is already a payment at PayPal with the same invoice ID.

This feature can be disabled, though we usually recommend keeping it enabled. To disable it, follow these steps:
Log in to your Business PayPal account (https://www.paypal.com/businessmanage/preferences/payments)
Go to the Payments Preferences section

Under the “Block accidental payments:” section, select the option “No, allow multiple payments per invoice ID“

With this feature disabled, PayPal would no longer complain when you submit an invoice number that already exists in the system.

But instead of disabling this feature, it would be better to figure out the true cause for this error. A buyer during the normal checkout process should normally not encounter this error. 

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. Additionally, it would be beneficial if you could provide a more detailed description of the problem, as the information shared here is a bit ambiguous.  

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
