### ISSUE TITLE
Remove Pay Later Messaging - Settings not saving #2

### ISSUE THREAD

**Issue by Cypherous** [woocommerce/woocommerce-paypal-payments#2243]
### Describe the Bug

As per https://github.com/woocommerce/woocommerce-paypal-payments/issues/2115 this issue still persists, there was a claim that it was fixed in 2.6.2 but it still exists in 2.7.0

### To Reproduce

    Go to Woocommerce / Payments / Payment methods / PayPal
    Click on "Pay Later" tab
    Scroll down to "Personalize your messages"
    Untick Product Page and Store
    Save changes

### Expected Behavior

Settings are saved and the pay later text is removed

### Actual Behavior

Option does not save and pay later text is not removed from the product page

### Environment

 - WordPress Version: 6.5.3
 - WooCommerce Version: 8.9.0
 - Plugin Version: 2.7.0
 - Browser [e.g. Chrome, Safari] and Version: Firefox 126
 - Any other plugins installed: just the stock ones and Product Input Fields for WooCommerce and Abandoned Cart Lite for WooCommerce

</details>

**Comment by Sirvijver** [comment]
Hello @Cypherous 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

I have tested this situation on my own test environment with the latest release, but was able to save these settings and did not encounter the issue you described. Can you try the same with all other plugins deactivated to see if this is not caused by a plugin conflict. If you keep on encountering this issue, please open a support ticket as described above. 

Kind regards, 
Joost

**Comment by Cypherous** [comment]
Except for one small issue @Sirvijver 

Downloading and installing the older version of the plugin works perfectly with all the existing plugins

So, you can continue to blame the stock plugins i have or, you can accept that your plugin still has issues and resolve them

**Comment by Sirvijver** [comment]
Hello @Cypherous 

Yes, it could have been caused by a change in our plugin, but that doesn't mean it occurs for anyone else. This is why we need to exclude any effect other plugins can have on the behavior. Without testing and isolating the cause of such an issue, there is not much we can do.

In any case, this forum is only used by us for development activities, not for support activities. That is why it was closed; this does not mean we will not investigate this, we just need to use the correct platform in order to do so.

Kind regards, 
Joost
