### ISSUE TITLE
[2.7.1] The arrow of the express button doesn't display the dropdown menu (3161)

### ISSUE THREAD

**Issue by a-danae** [woocommerce/woocommerce-paypal-payments#2254]
### Describe the Bug

The dropdown menu for the express button for selecting saved PayPal accounts is not displayed. There's an error in the browser console.

### To Reproduce

1. Enable vaulting at `wp-admin/admin.php?page=wc-settings&tab=checkout&section=ppcp-gateway`
2. As a shopper, place an order using a PayPal account
3. As a shopper, go to a single product page
4. On the PayPal express button, click on the arrow at the right
5. Notice that nothing happens
6. Open the browser console
7. Notice there's an error logged there

### Screenshots

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/41606954/292f0651-7295-45c3-b908-2c7ce2f8754a)

### Expected Behavior

Clicking on the arrow must display a dropdown menu. This is the behavior in 2.7.0

![image](https://github.com/woocommerce/woocommerce-paypal-payments/assets/41606954/bfd3811a-332c-463b-99c0-40d33ac85b31)

### Actual Behavior

No dropdown error is displayed. There's an error in the browser console.

**Comment by InpsydeNiklas** [comment]
@a-danae  this issue is being mitigated in #2255 (merged already), at least when the shipping callback is disabled. For the scenarios where the shipping-callback is active, we will need to wait for PayPal's feedback as it appears to be an issue on their end.
So for me, this the change in the PR is good enough to close this issue for now.
