### ISSUE TITLE
Fatal Error - Shipstation -Uncaught InvalidArgumentException

### ISSUE THREAD

**Issue by oliclarke** [woocommerce/woocommerce-paypal-payments#2287]
Shipstation is giving the error as below on all orders, even  those that are not using Paypal
 
WooCommerce version: 8.9.1
WooCommerce - ShipStation Integration |   | by WooCommerce – 4.4.3

IntegrationError: WooCommerce encountered an error and responded with StatusCode InternalServerError. Content: {"code":"internal_server_error","message":"<p>There has been a critical error on this website.<\/p><p><a href=\"https:\/\/wordpress.org\/documentation\/article\/faq-troubleshooting\/\">Learn more about troubleshooting WordPress.<\/a><\/p>","data":{"status":500,"error":{"type":1,"message":"Uncaught InvalidArgumentException: PayPal order ID not found in meta. in \/home\/storm\/sites\/mvwl[ooCommerce - ShipStation Integration](https://woocommerce.com/products/shipstation-integration/)	 	by WooCommerce – 4.4.3

**Comment by Sirvijver** [comment]
Hello @oliclarke 

You have reached out to open GitHub forum with a support request. We utilize GitHub mainly for development activities, so I would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

This issue was already reported via our support interfaces (wp.org and WooCommerce support page) and we have a bug open for this. You can revert to version 2.7.0 as a temporary workaround, and we would expect that this issue will be resolved with our next release (2.7.2) that we expect to be released around the 10th of June.

As we don't do support via GitHub, you might want to track the .org thread that is open for this [here](https://wordpress.org/support/topic/2-7-1-crashes-woocommerce/), because this GH thread will be closed now.

Kind regards, 
Joost

**Comment by Sirvijver** [comment]
Hello @oliclarke 

Our developers have been working yesterday on this issue and already have a temporary fix available for this problem.
If you want, you can download the package via [this link](https://drive.google.com/file/d/1CHf5wqMj_tw9cTD5dHBzFNX8DAScnlwc/view?usp=sharing), or you can wait for the next release where it should also be included.

If you choose to use the linked package, we will be happy to hear back from you with any positive or negative experiences.

Kind regards, 
Joost
