### ISSUE TITLE
Causes error message on the WOOCOMMERCE SHIPPING AND TAX plugin

### ISSUE THREAD

**Issue by puredesigngroup** [woocommerce/woocommerce-paypal-payments#2332]
### Describe the Bug

when trying to either purchase a shipping label on the new order page or looking at a previous order you get this error message and the shipping label/tracking number are not available. the page loads and you can see there is a label on the order but then the page shows this error message and the label details disappaer. 

Failed to retrieve shipping label refund status: <p>There has been a critical error on this website.</p><p><a href="https://wordpress.org/documentation/article/faq-troubleshooting/">Learn more about troubleshooting WordPress.</a></p>

### To Reproduce

1. go to a new order
2. purchase shipping label
3. when you hit purchase it buys the label but then it shows error message and no details for the label/tracking
4. See error: FAILED TO RETREIVE SHIPPING LABEL
5. i turned off all plugins except woo and woo shipping and tax and then turned each one back on until figuring out that its the woocommerce paypal payments plugin that is causing the issue. when this plugin is deactivated the error message goes away and the shipping label/tracking is shown and can be reprinted. turn the plugin back on and the error message appears. 

### Screenshots

![Screenshot 2024-06-03 at 4 01 39 PM](https://github.com/woocommerce/woocommerce-paypal-payments/assets/7095274/616e9ba2-658d-46ea-a67b-f50002e01466)

### Expected Behavior

shipipng label pluigin should work 

### Actual Behavior

shipping label plugin doesn't work

### Environment

 - WordPress Version 6.5.4
 - WooCommerce Version 8.9.3
 - Plugin Version 2.7.1
 - Any other plugins installed: lots of other plugins. specifically its effecting the woocommerce shipping and tax 2.6.0

**Comment by SydeKrystian** [comment]
Hello @puredesigngroup 

Please update the plugin to the[ recent version 2.8.0](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.0), this issue is already patched. If the problem persists after the update we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
