### ISSUE TITLE
PayPal Package Tracking Fatal error

### ISSUE THREAD

**Issue by Dgaozhen** [woocommerce/woocommerce-paypal-payments#2366]
### Describe the Bug

PayPal Package Tracking Fatal error

Unpaid orders and refunded orders can both enter the editing interface, while paid and completed orders will encounter errors when entering the editing interface

Fatal error: Uncaught WooCommerce\PayPalCommerce\ApiClient\Exception\RuntimeException: Could not retrieve order. 

in wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php:484 Stack trace: #0 
wp-content/plugins/woocommerce-paypal-payments/api/order-functions.php(48): 

WooCommerce\PayPalCommerce\ApiClient\Endpoint\OrderEndpoint->order() #1 

wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-order-tracking/src/MetaBoxRenderer.php(96): 

WooCommerce\PayPalCommerce\Api\ppcp_get_paypal_order() #2 

wp-admin/includes/template.php(1456): WooCommerce\PayPalCommerce\OrderTracking\MetaBoxRenderer->render() #3 

wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(492): do_meta_boxes() #47

wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(405): Automattic\Woo in 

wp-content/plugins/woocommerce-paypal-payments/modules/ppcp-api-client/src/Endpoint/OrderEndpoint.php on line 484

How to solve this problem

**Comment by InpsydeNiklas** [comment]
Hi @Dgaozhen, this issue was resolved in the latest [2.8.1-rc1](https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.8.1-rc1) pre-release version. Please give it a try and let us know if any issues persist for you. 
In that case, please get in touch with our support team directly from here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Because this issue duplicated #2364, so I will close it.
Thank you!
