### ISSUE TITLE
Pay Later Messaging not shown on Product, Cart and Checkout pages.

### ISSUE THREAD

**Issue by pingram3541** [woocommerce/woocommerce-paypal-payments#2440]
### Describe the Bug

Pay Later Messaging not shown on Product, Cart and Checkout pages. On the back end, changing Pay Later Messaging options does not save, for example ticking WooCommerce Block and saving then refreshing the page it is not ticked.

In the product and cart pages there is no mention of PayPal or Pay Later text/est. pricing only the checkout page reveal the PayPal radio button and when selected only provides 3 buttons, no Pay Later text, just a Pay Later button only.

The documentation and back end admin area show examples of what it should like with suggested Pay Later text but that is never rendered on the front end. Additionally when inspecting the html there are no PayPal containers where we would expect to see the PayLater text/options.

The browser console does not show any events or errors.

The plugin is up to date, currently v2.8.1

### To Reproduce

1. View any product page, no PayPal pay later text or button
2. Add to Cart, the visit cart, no PayPal pay later text or button
3. Go to Checkout, no PayPal pay later text only a Pay Later button is shown
4. In admin, Pay Later options do no save to database.

### Screenshots

I could show you a screen shot that doesn't show any Pay Later stuff but not sure if that would help.

### Expected Behavior

Pay Later messaging to be shown on product, cart and checkout pages and back end to save settings.

### Actual Behavior

Nothing is shown.

### Environment

 - WordPress Version - 6.6
 - WooCommerce Version - 9.1.2
 - Plugin Version - 2.8.1
 - Browser [e.g. Chrome, Safari] and Version - Chrome (latest)
 - Any other plugins installed - WooCommerce, WooPayments

### Additional Details
N/A

**Comment by SydeKrystian** [comment]
Hello @pingram3541,

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

Additionally, it is important to note that the issue you are encountering should not be occurring in the current version (2.8.2) of the plugin. Please ensure that your plugin is updated to this latest version as it may resolve your problem.

When you contact our support team, please include a copy of your [WooCommerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 
We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by pingram3541** [comment]
Hi Thanks Krystian, your help with this matter is greatly appreciated however I am concerned you are prematurely closing this ticket when it indeed is a problem that requires a code correction.

The plugin literally links "bug report" to this Git repo. The issue is clearly a bug, not being able to save a setting otherwise offered as an option to be set. Additionally not showing any of the Pay Later options on the front end is also not related to improper set up on the client side, it just stopped rendering on all sites that this plugin is installed.

Here are several tickets with the same bug described.

https://github.com/woocommerce/woocommerce-paypal-payments/issues/2488
https://github.com/woocommerce/woocommerce-paypal-payments/issues/2479
https://github.com/woocommerce/woocommerce-paypal-payments/issues/2356
https://github.com/woocommerce/woocommerce-paypal-payments/issues/2261

Please advise thank you.

-Phil

**Comment by pingram3541** [comment]
> For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

I should add also that we did indeed create a ticket using the method you mention and did not receive any response.

**Comment by SydeKrystian** [comment]
Hello @pingram3541 

> I should add also that we did indeed create a ticket using the method you mention and did not receive any response.

Could you please provide your PCP ticket number so I can check if it has been initiated on our support board?

> Hi Thanks Krystian, your help with this matter is greatly appreciated however I am concerned you are prematurely closing this ticket when it indeed is a problem that requires a code correction.

We don't handle these issues through GitHub tickets because this platform is mainly for reporting typical development problems. The issue you're encountering is indeed a plugin error, but we group such problems on our support board, where it's easier to communicate with users. For this reason, we're moving them to a private support board.

Kind regards,
Krystian

**Comment by pingram3541** [comment]
Hi Krystian,

I have logged in to our WooCommerce account at woocommerce.com where we placed the ticket and I cannot locate a PCP ticket number let alone any area for viewing tickets.

> The issue you're encountering is indeed a plugin error

No. There is no error. The advertised Pay Later Messaging front end features don't render at all and the advertised Pay Later Messaging feature settings on the back end don't save, but the plugin produces no visible errors.

Advertised functionality is not working and it is not isolated to just my client websites across the board. This deserves attention or people will loose interest in using this plugin.

**Comment by SydeKrystian** [comment]
Hello @pingram3541 

> I have logged in to our WooCommerce account at woocommerce.com where we placed the ticket and I cannot locate a PCP ticket number let alone any area for viewing tickets.


The key issue here is that you contacted WooCommerce instead of reaching out to us directly. Please use this link to get the right support: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help

> Advertised functionality is not working and it is not isolated to just my client websites across the board. This deserves attention or people will loose interest in using this plugin.

For us to analyze this type of problem, we'll need a system report. Please contact our support team through the provided link so we can assist you further. 

> Pay Later Messaging not shown on Product, Cart and Checkout pages. On the back end, changing Pay Later Messaging options does not save, for example ticking WooCommerce Block and saving then refreshing the page it is not ticked.

We are aware of the issues with saving Pay Later settings and are addressing this in our upcoming update.

In the meantime, you can use a workaround by disabling the new Pay Later messaging configurator and reverting to the legacy settings. You can restore the legacy configuration by adding the following code snippet:

`add_filter( 'woocommerce.feature-flags.woocommerce_paypal_payments.paylater_configurator_enabled', '__return_false' );
`
This should help resolve the issue until the update is released.

Thank you for understanding and looking forward to your response.

Kind regards,
Krystian

**Comment by pingram3541** [comment]
Hi Krystian, thanks for providing a filter to revert back to the legacy Pay Later options but unfortunately when adding this filter to our functions.php it still does not appear to render any Pay Later options in the product, cart or checkout pages nor any Pay Later est. pricing/terms like it used to, the only Pay Later option available is the generic yellow Pay later button on the checkout page.

**Comment by subfighter3** [comment]
Confirming that the snippet provided does not work at all. The new Pay Later messaging configurator still shows

**Comment by SydeKrystian** [comment]
Hello @pingram3541 & @subfighter3 

The snippet should work if it is added to the functions.php file. Could you confirm how you implemented it? Did you use the Code Snippets plugin or another method?

You can also give a try with this plugin, it works fine on my end: https://drive.google.com/uc?id=1PyvIWsxPcbZpRU1SQZ-_bxsbR42uL2ny

In version 3.0.0, we will fully implement the new UI. The legacy messaging configuration will no longer be available, and it will only work via the Messaging Configurator.

Kind regards,
Krystian

**Comment by subfighter3** [comment]
Hi @SydeKrystian thanks for your answer.

I tried adding the snippet straight in the functions.php with no success while your plugin works as expected. It's weird because it just contains the same snippet, probably as you said it's just matter of loading priorities.

Reverting to the old pay later messaging interface was just a test for me, because I experienced an issue of the message not showing in the single product page of composite products, while in any other product type it works. Sadly the pay later message still not showing even disabling the new configurator interface. I reached out the PayPal Payments dev team for support, looks like a bug and they are investigating.

Thanks for the help, I will keep using the new configurator since the old one will be soon deprecated.

**Comment by SydeKrystian** [comment]
Hello @subfighter3 

If I'm not mistaken, I assume from your profile and name that you reported this issue with composite products today. We will try to fix it in the coming days and will update you soon.

Glad the plugin work at least 👍 

Kind regards,
Krystian

**Comment by subfighter3** [comment]
Yes @SydeKrystian it's me! I think I replied to your email a few hours ago. Thanks a lot for taking care of the issue.

Have a good day!

**Comment by subfighter3** [comment]
Hey @SydeKrystian perhaps do you have any update about this?

**Comment by SydeKrystian** [comment]
Hello @subfighter3 

Could you please reach out to us via email, ideally by replying to our last message in that conversation?

I’m not fully familiar with the context here without seeing the previous communication, so I’m not sure which issue you’re referring to.

Looking forward to your reply so we can assist you further.

Kind Regards,
Krystian

**Comment by subfighter3** [comment]
Thanks for your reply. Just replied to your email from the Woo Support.
Cheers
