### ISSUE TITLE
Woocommerce - PayPal refuses unique sale for the reason of an duplicate order ID

### ISSUE THREAD

**Issue by sqwhhe** [woocommerce/woocommerce-paypal-payments#2458]
### Describe the Bug

After trying to buy a product at the woocommerce checkout via PayPal the user gets successfully redirected to PayPal. Payment can be selected and submitted. After redirecting back to the checkout an error appears: The transaction has been refused because the Invoice ID already exists. Please create a new order or reach out to the store owner. https://developer.paypal.com/docs/api/orders/v2/#error-DUPLICATE_INVOICE_ID

### To Reproduce

1. Start the checkout 
2. Click on PayPal Buy now
3. Do the payment at PayPal
4. See error after being redirected to the checkout

### Screenshots

<img width="1099" alt="image" src="https://github.com/user-attachments/assets/893adb06-f6cc-4ccc-9a24-c9bcc36b0cb6">

### Expected Behavior

Order should be completed

### Actual Behavior

Order is not completed

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.1.2
 - Plugin Version 2.8.2
 - Browser Chrome 126.0.6478.183 (Offizieller Build) (x86_64), Safari 17.5 (17618.2.12.111.5, 17618)
 - Any other plugins installed, yes
 

### Additional Details

The first failed order appeared today (24th of July) at 08:00pm CET
We changed today WP Version from 6.5.X to  6.6.1, **but** that was 6 hours earlier and we have a lot successful orders via PayPal between 2:30p.m and 8p.m.

<details><summary>System status</summary>

![image](https://github.com/user-attachments/assets/5127dce5-015e-4486-86be-d5dde312e715)

</details>

**Comment by SydeKrystian** [comment]
Hello @sqwhhe 

The error DUPLICATE_INVOICE_ID error is a security feature from PayPal which aims to prevent accidental double-payments.

PayPal Payments automatically sets an "invoice prefix" and then sends the WooCommerce order numbers in the pattern "invoice prefix+ordernumber" to PayPal.
So when your prefix is set to "cfbdg-" and your order number is "123", PayPal Payments sends the invoice ID "cfbdg-123" to PayPal.

Under certain circumstances, for example when you restore a backup from your website, it is possible that the most recent WooCommerce orders do not exist anymore after the restore.
So as soon as WooCommerce attempts to create a new order with the number 123 and the same invoice prefix, PayPal would throw this error to prevent accidental double payments because there is already a payment at PayPal with the same invoice ID.
This feature can be disabled, though we usually recommend keeping it enabled. To disable it, follow these steps:

1. Log in to your Business PayPal account (https://www.paypal.com/businessmanage/preferences/payments)
2. Go to the Payments Preferences section
3. Under the "Block accidental payments:" section, select the option "No, allow multiple payments per invoice ID"

With this feature disabled, PayPal would no longer complain when you submit an invoice number that already exists in the system. But instead of disabling this feature, it would be better to figure out the true cause for this error. A buyer during the normal checkout process should normally not encounter this error. 

For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by SeymourNickelson** [comment]
Just ran into this myself. In my case I did some test purchases on a staging site in the sandbox environment, then switched to production environment to do test orders and they failed.

In case anyone runs into the same thing you can workaround it by putting putting sandbox in front of the url above (https://www.sandbox.paypal.com/businessmanage/preferences/payments) and login with the sandbox business account you are using. Then change the "block accidental payments" to No for the sandbox environment.
