### ISSUE TITLE
Can't finish to activate PayPal no matter hw many times says is ready.

### ISSUE THREAD

**Issue by hfranco73** [woocommerce/woocommerce-paypal-payments#2472]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @hfranco73 

Occasionally, the onboarding wizard might encounter issues. This can be due to interference from certain plugins during the connection process. If you're facing challenges connecting your PayPal account, a proven solution is to input your credentials manually. For a step-by-step guide on this manual method, you can refer to this tutorial: [https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input](https://woocommerce.com/document/woocommerce-paypal-payments/#manual-credential-input)  

For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

**Comment by hfranco73** [comment]
Thanks. Finally activated using manual activation.
