### ISSUE TITLE
Paypal does not apply the coupons discounts in Woocommerce subscriptions

### ISSUE THREAD

**Issue by talentform-spa** [woocommerce/woocommerce-paypal-payments#2514]
### Describe the Bug

When the customer choose a subscription products then applying a discount coupon, the cart shows properly the total amount, but going to pya in paypal the discount disappear e Paypal ask for the total withount applyng the cooupon discount

### To Reproduce

1. Go to 'https://www.perimparare.it/prodotto/abbonamento-annuale-per-tutti-i-corsi/ ', add subscription the go to 'https://www.perimparare.it/checkout/'
2. use the coupon 20e250824
3. Click on Paypal
4. Paypal does not apply the coupon

### Screenshots

![image](https://github.com/user-attachments/assets/cde2cf4d-1467-4f4c-905b-7576c8b9a7ab)
![image](https://github.com/user-attachments/assets/e008ae01-c722-4fff-a16d-ff29ab8a2bc3)
![image](https://github.com/user-attachments/assets/fb4e3b3e-f849-46d2-b667-94300e9a13bc)

### Expected Behavior

The coupon should be applied to paypal total

### Actual Behavior

The paypal total is full without any coupon discount

### Environment

 - WordPress Version 6.6.1
 - WooCommerce Version 9.1.4
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version All browsers
 - Any other plugins installed WooCommerce Subscriptions WooCommerce Checkout Manager WooCommerce PayPal Payments WooCommerce Shipping & Tax WooCommerce.com Update Manager WooPayments

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```
Salute del sito (Site Health)
Buono
</details>

**Comment by SydeKrystian** [comment]
Hello @talentform-spa 

Without a system report, I can only guess, but I assume you're using PayPal Subscriptions instead of PayPal Vaulting. 

PayPal Subscriptions offer a convenient way to handle recurring payments, but they have some drawbacks. Unlike PayPal Vaulting, you can't easily adjust prices, apply coupons, or add shipping costs with PayPal Subscriptions. This is because the subscription system, particularly through the PayPal button (JS SDK), doesn't support updates to subscription details. Adding these features would require significant development work and expense, which is why they haven't been implemented yet. This option hasn't been ruled out, but it's on hold for now.

PayPal Subscriptions is a feature-limited subscription integration available to every PayPal business account holder. PayPal controls the subscription and some limitations technically cannot be overcome (e.g. discounts or shipping). It's not a bug that coupons don't work, it's simply not possible with this implementation. So this feature is mostly interesting for virtual products or when shipping costs are fixed.  
  
To get access to fully-features subscription functionality (incl. shipping, discounts, etc.), we recommend [Vault approval (Reference Transactions)](https://woocommerce.com/document/woocommerce-paypal-payments/#get-vaulting-approval).

Please also keep in mind that GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

Kind regards,
Krystian
