### ISSUE TITLE
Error con el z-index de los botones de paypal

### ISSUE THREAD

**Issue by AlProgram** [woocommerce/woocommerce-paypal-payments#2530]
Los botones de paypal se ven por encima de todo en mi web, incluso del header. Adjunto una imagen para que lo vean, esto pasa con todos los botones, en la ficha de producto, en el carrito y en el checkout en mi caso 
![Captura de pantalla 2024-08-25 191801](https://github.com/user-attachments/assets/de2a7016-1819-4732-bc4a-06dc7a30e7e1)

**Comment by SydeKrystian** [comment]
Hello @AlProgram

This issue can typically be resolved by adjusting the placement and layering of elements via filter, but I'm not sure since I haven't received the screenshot you mentioned.

I recommend utilizing the smart button customizations available through the WooCommerce PayPal Payments plugin. You can adjust the settings by adding custom CSS or modifying the button behavior using the filters provided.

Here are some resources to guide you:

For general customizations and examples of how to use filters, please check this guide: [PayPal Smart Button Customizations](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#smart-button-customizations).
You might also find this comprehensive list of WooCommerce hooks useful for further customizations: [WooCommerce Hooks Guide](https://premmerce.com/woocommerce-hooks-guide/).

If you are not familiar with adding custom code we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly.

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian
