### ISSUE TITLE
Paypal Payment ISsue

### ISSUE THREAD

**Issue by worksupplies** [woocommerce/woocommerce-paypal-payments#2533]
Frequently using the following error message from Paypal payments.

Failed to process the payment. Please try again or contact the shop admin. [UNPROCESSABLE_ENTITY] The transaction has been refused by the payment processor. Please reach out to the PayPal support for more information. https://developer.paypal.com/docs/api/orders/v2/#error-TRANSACTION_REFUSED CardButtonGateway.php:314 [UNPROCESSABLE_ENTITY] The transaction has been refused by the payment processor. Please reach out to the PayPal support for more information. https://developer.paypal.com/docs/api/orders/v2/#error-TRANSACTION_REFUSED OrderEndpoint.php:346 Order status changed from Pending payment to Failed.

**Comment by worksupplies** [comment]
Any update please ?

**Comment by callmeahmedr** [comment]
Hi @worksupplies, 

Looking at the error, here's the probable cause 

**Transaction Refusal by PayPal**
- This can happen if the card details are incorrect, the card is expired, or the issuing bank has blocked the transaction. 
- Check your card details or try a different payment method. 

If this issue persists across multiple transactions, it might be beneficial to reach out to PayPal support with the specific error code for further clarification.

> Any update please ?

**Comment by worksupplies** [comment]
thanks very much for the reply.

**Comment by worksupplies** [comment]
Sure. Thanks very much.

 

 

 

 

Best Regards, 

Fawad Qayyum (Account Manager)
CONTACT: 03 9747 6588 / 0416 461 696
Email:  ***@***.***> ***@***.***
Web:  <http://www.worksupplies.net.au/> www.worksupplies.net.au






We provide Printing Solutions For TOP Brands




LinkedIn:  <https://lsems.gravityzone.bitdefender.com/scan/aHR0cHM6Ly93d3cubGlua2VkaW4uY29tL2luL2Zhd2FkcWF5eXVtLXBwZS8=/C57B681A1BB3C28531CD8708BE01BCC84C1498F2B06C6943A86743E01C8D0E88?c=1&i=1&docs=1> https://www.linkedin.com/in/fawadqayyum-ppe/

ABN: 79640018300

**Comment by SydeKrystian** [comment]
Hello @worksupplies 

The TRANSACTION_REFUSED response from PayPal typically signifies a regular decline so the outcome in the log is a bit different, but the reason is pretty much the same. It doesn’t usually point to an integration or technical issue but suggests something is questionable with the buyers’ card or PayPal account.

To ensure that the plugin is functioning correctly on your end, I would recommend setting up a sandbox account. This can be done by following the instructions provided here: [Testing in Sandbox](https://woocommerce.com/document/woocommerce-paypal-payments/#testing-in-sandbox). Using a sandbox account, you can perform transactions with [test credit cards](https://developer.paypal.com/tools/sandbox/card-testing/) or another sandbox account to verify that everything is working as expected without any real financial transactions taking place.

Please proceed with these steps and let us know if the problem persists in the sandbox.

Kind regards,
Krystian
