### ISSUE TITLE
Error 10525 on $0 ticket

### ISSUE THREAD

**Issue by LindaShore** [woocommerce/woocommerce-paypal-payments#2559]
### Describe the Bug
Receiving error 10525 on a $0 ticket created using the WooCommerce PayPal Payments plugin in conjunction with Events Tickets Plus

### To Reproduce
I've been using this combination of plugins on the site https://scfpapresents.org/ for three years but ran into the problem when I created a $0 for an event that I wanted to create tickets because there are a limited number of seats for the event. I submitted the issue to the Events Support team and received this response: 

_Thanks for reaching out about this. I see that you're having some issues when using PayPal payments for free tickets where you get an error and the checkout doesn't continue. That certainly isn't ideal, so let's see what I can do to point you in the right direction to get this working._
 
_From your description, and searching for information on this, this is most likely due to the way the site is set up. If it's a free ticket, the request shouldn't be going to PayPal in the first place since it won't handle 0$ transactions. It seems to me that the site isn't set up to handle free products._ 
 
_The way our plugins work with WooCommerce is that it creates a ticket as a product when someone purchases it, and uses whichever payment system you have on your site. For free tickets, that should be bypassed and not go directly to PayPal since it's a 0$ transaction and that won't work._ 
 
_Unfortunately, this isn't something that can be fixed on our end at all, since the site using WooCommerce to handle the checkout. Usually, for a free ticket, the payment would just be bypassed ocmpletely, but the site doesn't seem to be doing that for some reason, so you will have to contact whichever payment plugin you're using. If you're using the default WooCommerce PayPal plugin then you should reach out to them here https://woocommerce.com/contact-us/___

### Screenshots

![Screenshot (283)](https://github.com/user-attachments/assets/893c3e97-e868-4b1a-9844-c84959b9f0c0)

### Expected Behavior

A customer could complete the transaction for a $0 ticket in the Events plugin without erroring out.

### Actual Behavior

As you can see on the screenshot, the only option for creating the ticket is to check out using PayPal.  That works correctly for priced tickets but not for the free ones. I'm hoping you can help me figure this out as the Opera House is planning to offer more free events this coming season and we do need to keep track of the number of attendees since the seating is limited.   

**Is the point I should be using your RSVP functionality instead of a free ticket?**  

Thanks in advance for your help.
Linda

### Environment

https://scfpapresents.org/
 - WordPress Version 6.6.1
 - WooCommerce Version 9.2.3
 - WooCommerce PayPal Payments 2.9.0
 - Chrome & Bing
 - Any other plugins installed 
 - Event Tickets 5.13.2, 
 - Event Tickets Plus, 6.0.2
 - Payment Gateway Plugin for PayPal WooCommerce ( Free ) 1.8.6

**Comment by InpsydeNiklas** [comment]
Hello @LindaShore, this PayPal button on your website and the error are coming from the [Payment Gateway Plugin for PayPal WooCommerce](https://wordpress.org/plugins/express-checkout-paypal-payment-gateway-for-woocommerce/) plugin, which is created by [WebToffee](https://www.webtoffee.com/product/paypal-express-checkout-gateway-for-woocommerce/), a third-party developer.

The [official PayPal Payments plugin](https://wordpress.org/plugins/woocommerce-paypal-payments/) is designed to not show the PayPal buttons or the PayPal payment method in general for free products. Since PayPal normally does not process $0 payments, unless there is, e.g., a free trial subscription that would require saving the payment method for future transactions.

We recommend disabling any other PayPal plugins and only using one single PayPal integration to avoid confusion or potential issues. It seems your site currently may not be configured to provide a link to the [checkout page to buyers](https://scfpapresents.org/checkout/), but this will likely be needed to allow users to reserve a ticket without paying. 
If you need more guidance on setting up PayPal Payments for your needs, you can find [the documentation here](https://woocommerce.com/document/woocommerce-paypal-payments/), and our [support team can be reached from here](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) if any questions remain. 

That said, we use this GitHub repository primarily for development and bug tracking, so I will close this issue. Our support team is available to help with any questions beyond that. Thank you!
