### ISSUE TITLE
Add loading animation to the "Debit or Credit Card" button on checkout

### ISSUE THREAD

**Issue by asafm7** [woocommerce/woocommerce-paypal-payments#257]
On checkout, after clicking the "Debit or Credit Card" button, it takes about 3 seconds for the form to open.

I've already confirmed with your support that it's a known issue. I understand there are limitations regarding the integration with PayPal.

I suggest asking PayPal to add a processing/loading animation to the button after clicking it. This way, the user gets visual feedback assuring everything is okay and that they should wait.

**Comment by asafm7** [comment]
Hi, @Dinamiko are you sure there isn't a mixup?

In what way does #458 solve this?

**Comment by Dinamiko** [comment]
Hi @asafm7,

Yes that was a mixup from my side, I wrongly mentioned this issue in #458 PR, now the PR points correctly to the issues it fixes (#457 and #456).

Thanks and sorry for the confusion :)

**Comment by InpsydeNiklas** [comment]
PayPal improved the timing of the spinner that appears when clicking the standard card button. A recent plugin update also included a feature to modify the card billing data handling, which can impact the speed of the smart card fields.
Custom spinner solutions were internally tested, but deemed not reliable enough. Since PayPal improved the speed, this should no longer be a major problem and maybe take a second at most.
Please also keep in mind that the click of the button already creates a PayPal order, so there is a short processing time in any case.

For any further questions or suggestions, please [get in touch with the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly. Thanks!
