### ISSUE TITLE
Translation loading trigger too early -- WooCommerce for WordPress

### ISSUE THREAD

**Issue by stevenp8080** [woocommerce/woocommerce-paypal-payments#2829]
Started to receive the below error all over WordPress and on my website. 

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /xxxx/xxxx/xxxx/wp-includes/functions.php on line 6114

**Comment by pierorocca** [comment]
Also reported by 9069128-zd-a8c

**Comment by SydeKrystian** [comment]
Hello @pierorocca 

The deprecation warning you’re seeing in WordPress 6.7 indicates that the translation loading for the woocommerce-paypal-payments domain is being triggered earlier than recommended. WordPress now advises that translations be loaded at the init action or later to ensure compatibility with the latest core changes. This is why you’re seeing the _load_textdomain_just_in_time notice.

This issue may indeed be due to an early loading function within the WooCommerce PayPal Payments plugin, which could affect compatibility with WordPress 6.7.

We have noted this and will look into it. Also please note that this is not a critical issue and should not break any functions won the plugin or your site.

Kind regards,
Krystian

**Comment by pierorocca** [comment]
Thanks Kristian. I noted to the merchant that it's a warning notice rather than a hard error and that it would not be impactful.
