### ISSUE TITLE
Issue on Wordpress 6.7.1

### ISSUE THREAD

**Issue by CTEcreativeATL** [woocommerce/woocommerce-paypal-payments#2833]
### Describe the Bug
Getting error after update to 6.7.1

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/vhtdocs/userweb62159/html/wp-includes/functions.php on line 6114

### To Reproduce

1. Update to the latest WP
2. Install widget 
3. Notice banner at top of page
4. Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/vhtdocs/userweb62159/html/wp-includes/functions.php on line 6114

### Screenshots

![Image](https://github.com/user-attachments/assets/73e59ea3-3dd2-4503-912c-db45ae5ba5df)

### Expected Behavior
The plugin works without the error banner

### Actual Behavior
An error banner displays
### Environment

 - WordPress Version: 6.7.1
 - WooCommerce Version: 9.4.2
 - Plugin Version: 2.9.4
 - Browser [e.g. Chrome, Safari] and Version: Chrome
 - Any other plugins installed: yes

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @CTEcreativeATL 

The deprecation warning you’re seeing in WordPress 6.7 indicates that the translation loading for the woocommerce-paypal-payments domain is being triggered earlier than recommended. WordPress now advises that translations be loaded at the init action or later to ensure compatibility with the latest core changes. This is why you’re seeing the _load_textdomain_just_in_time notice.

This issue may indeed be due to an early loading function within the WooCommerce PayPal Payments plugin, which could affect compatibility with WordPress 6.7.

We have noted this and will look into it. Also please note that this is not a critical issue and should not break any functions won the plugin or your site.

Kind regards,
Krystian

**Comment by CTEcreativeATL** [comment]
Thank you for this info and letting me know this isn't critical.
Take care!
