### ISSUE TITLE
Transactions failing - Authorization Error

### ISSUE THREAD

**Issue by vrsong** [woocommerce/woocommerce-paypal-payments#2841]
### Describe the Bug

I am running a WooCommerce store using the "WooCommerce PayPal Payments" plugin.

"Advanced Card Processing" has been working fine up till now.

When I try to process a transaction I receive either of these two errors:

"There was an error processing your order. Please check for any charges in your payment method and review your order history before placing the order again."

2.
"ERROR: reCAPTCHA verification failed"

When I check the Paypal error logs this what I see:

{
  "additional_properties": {},
  "body": {
    "name": "AUTHORIZATION_ERROR",
    "message": "Authorization error",
    "information_link": "https://developer.paypal.com/webapps/developer/docs/api/#AUTHORIZATION_ERROR",
    "details": [
      {
        "name": "REFUSED_MARK_REF_TXN_NOT_ENABLED",
        "message": "This merchant account is not permitted to create Merchant Initiated Billing Agreement"
      }
    ]
  },
  "duration_time": "xxxxxx",
  "header": {
    "APPLICATION_ID": "APP-4MU13848GD7464536",
    "Access-Control-Expose-Headers": "xxxxxx",
    "BORDER-IP": "xxxxxx",
    "CALLER_ACCT_NUM": "9T25E25KAG5JC",
    "Date": "Mon, 25 Nov 2024 22:55:47 GMT",
    "Keep-Alive": "xxxxxx",
    "PROCESSING-IP": "xxxxxx",
    "PayPal-Gateway-Metadata": "xxxxxx",
    "Server-Timing": "xxxxxx",
    "paypal-debug-id": "b994b5c5685af"
  },
  "status": 403
}

As far as I know I am not initiating any 'biller agreement'. This is just a standard one-off transaction.

### To Reproduce

The website is:
https://jwcarterpublishing.com.au

I have currently disabled this payment method.

### Environment

 - WordPress 6.7.1 running JupiterX Child theme.
 - WooCommerce Version - Version 9.4.2
 - WooCommerce PayPal Payments - Version 2.9.4
 - Any browser
 - Any other plugins installed - Screenshot here - https://prnt.sc/N7ODuKNKfz3B

### Additional Details

Plugin setup:
https://prnt.sc/If2OVXo_rZx_

PayPal error list:
https://prnt.sc/37WGTmgXxg2w

General status:

https://prnt.sc/oYC_eDBHj6uU

</details>

**Comment by SydeKrystian** [comment]
Hello @vrsong 

We have identified what is causing this behavior with Advanced Card Processing (ACDC). It appears that when our JavaScript (JS) is not enabled on the checkout page, ACDC payments are affected. This is unintended behavior, as ACDC should work independently of the smart buttons (JS). As a temporary workaround, we recommend enabling Smart Button Locations (in Standrad Payments tab) on the Classic Checkout or Express Checkout page, depending on which setup you are currently using.

This should resolve the issue until we implement a fix. If this workaround does not resolve the problem, please let us know. There is a slight chance that, despite enabling the buttons, they might not appear due to a conflict with a third-party plugin or theme. If that is the case, we will work with you to investigate further.

 For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

Kind Regards,
Krystian
