### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by krymazz** [woocommerce/woocommerce-paypal-payments#2849]
### Describe the Bug

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the woocommerce-paypal-payments domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /var/www/vhosts/maxufficio.it/subdomains/shop/httpdocs/wp-includes/functions.php on line 6114

### To Reproduce

![Image](https://github.com/user-attachments/assets/53c4308b-1c44-49ef-a6d1-275eac1272b4)

### Screenshots

![Image](https://github.com/user-attachments/assets/a41361f9-6ef4-4736-acce-49301e8a0b07)

### Environment

 - WordPress 6.7.1
 - WooCommerce Version 9.4.2
 - Plugin Version  2.9.4
 - Browser [e.g. Chrome, Safari] and Version: All browser![Image](https://github.com/user-attachments/assets/d25fc600-63af-4c96-9a3f-e8a07b96271c)

 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by SydeKrystian** [comment]
Hello @krymazz 

The fix for this issue is already available for testing. You can download it from the following link: https://github.com/woocommerce/woocommerce-paypal-payments/releases/tag/2.9.5-rc1

Alternatively, if you prefer to wait until officially released you can disable debugging or even better use [this code snippet](https://developer.woocommerce.com/2024/11/11/developer-advisory-translation-loading-changes-in-wordpress-6-7/) to suppress the notice:

add_filter( 'doing_it_wrong_trigger_error', '__return_false' );

Please let us know if you have any further questions.

Kind regards,
Krystian
