### ISSUE TITLE
Call center plugin

### ISSUE THREAD

**Issue by wgailey** [woocommerce/woocommerce-paypal-payments#2931]
Hello @wgailey 

It seems that your GitHub issue is primarily a support request. While we value your input and feedback, GitHub is predominantly used for our development activities. For a prompt and detailed response, we kindly ask that you reach out directly to our [support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help).  

When you contact our support team, please include a copy of your [WooComnmerce system report](https://woocommerce.com/document/understanding-the-woocommerce-system-status-report/). This will help us get to the bottom of your issue more quickly. 

We'll be closing this GitHub issue for now. However, once you reach out to our support team, rest assured they'll be ready to assist you with your concerns. Thank you for your understanding!

Kind regards,
Krystian

_Originally posted by @SydeKrystian in https://github.com/woocommerce/woocommerce-paypal-payments/issues/2923#issuecomment-2550603120_

Guy apparently just want to close tickets like he works in a call center, not fix bugs.

**Comment by SydeKrystian** [comment]
Hello @wgailey 

Thank you for sharing your feedback.

I have already clarified our position in this [response](https://github.com/woocommerce/woocommerce-paypal-payments/issues/2923#issuecomment-2550872894). 

To explain further, the way we classify issues on GitHub might seem confusing, but for us, GitHub is specifically reserved for reporting development bugs. Unfortunately, your submission did not meet the criteria for this classification, which is why I suggested to reach out to us via support, it simply sped up resolution. 

Thank you for your understanding, and we appreciate your input.

Kind Regards,

Krystian

**Comment by wgailey** [comment]
I understand you're confused on github, when you learn to code and understand diagnostic information let me know scammer.
    On Wednesday, December 18, 2024 at 02:01:41 AM PST, Krystian Kep ***@***.***> wrote:  
 
 


Closed #2931 as completed.
