### ISSUE TITLE
WooCommerce PayPal Payments – Unable to Disable or Save Changes for PayPal Credit Banners

### ISSUE THREAD

**Issue by celerymist** [woocommerce/woocommerce-paypal-payments#2953]
Describe the Bug
The PayPal Credit promotional banner appears repeatedly on WooCommerce product pages, cart, and checkout screens. Despite attempts to disable the banners in the WooCommerce PayPal Payments plugin settings, changes cannot be saved. This results in persistent promotional content, creating visual clutter across the store.

To Reproduce
Go to WooCommerce > Settings > Payments > PayPal Payments.
Scroll down to PayPal Credit Messaging or Banners section.
Attempt to disable the option or toggle banner visibility.
Click Save Changes.
The page refreshes, but the settings revert, and PayPal banners remain active across the site.
Screenshots
Attach screenshots of the plugin settings and banners still appearing after disabling them.

Expected Behavior
Disabling the PayPal Credit banner in the plugin settings should immediately remove the promotional content from product and checkout pages. The plugin settings should save without reverting.

Actual Behavior
Attempts to disable PayPal Credit messaging fail to save.
The banners continue to display across product pages and the checkout screen, even after toggling off the option.
The issue persists regardless of the browser or WordPress cache clearing.
Environment
WordPress Version: [6.7.1]
WooCommerce Version: [9.5.1]
Plugin Version: [PayPal Plugin]
Browser: [Chrome]
Other Plugins Installed: [LiteSpeedCache]

**Comment by InpsydeNiklas** [comment]
Hi @celerymist, this issue is likely due to your cache plugin interfering with PayPal's new messaging configurator. Please try disabling your cache plugin or alternatively adding the [code snippet here](https://github.com/woocommerce/woocommerce-paypal-payments/wiki/Actions-and-Filters#disable-pay-later-messaging-configurator-in-260) to revert to the legacy messaging configuration. 
If you need more help, you can contact the support team via this link: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thank you!
