### ISSUE TITLE
Bump version of wikimedia/composer-merge-plugin (476)

### ISSUE THREAD

**Issue by helgatheviking** [woocommerce/woocommerce-paypal-payments#338]
### Describe the bug
`composer install` fails to install when using composer 2.0.

```
Problem 1
    - wikimedia/composer-merge-plugin[v1.4.0, ..., v1.4.1] require composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - Root composer.json requires wikimedia/composer-merge-plugin ^1.4 -> satisfiable by wikimedia/composer-merge-plugin[v1.4.0, v1.4.1].
 ```

### To reproduce
1. upgrade to Composer 2.0
2. run `composer install`

Can be resolved by bumping the requirement from ^1.4 to ^2.0.
https://github.com/woocommerce/woocommerce-paypal-payments/blob/79e2dd2ef5f9b46ce6f6b8a74c28be1bc38f36e4/composer.json#L15

**Comment by Dinamiko** [comment]
Hi @helgatheviking, thanks and sorry for the delay in the response. 

I´ve just tried but it´s not currently possible to upgrade `wikimedia/composer-merge-plugin` to version 2 because it requires PHP 7.2. and we are using PHP 7.1 at the moment, when trying to upgrade the package **using PHP 7.1 interpreter** we got this error:
`wikimedia/composer-merge-plugin v2.0.1 requires php >=7.2.0 -> your PHP version (7.1.33) does not satisfy that requirement.`

I take note of this, as soon as we´ll be able to upgrade the plugin PHP version we´ll upgrade this package, thanks.
