### ISSUE TITLE
Failed manual payment change sets related subscription from "Active" to "Pending" status (461)

### ISSUE THREAD

**Issue by steffans** [woocommerce/woocommerce-paypal-payments#434]
### Describe the Bug

If you try to change a currently active subscription payment method to Paypal and it shows the following message:

`No PayPal payments saved, in order to use a saved payment you first need to create it through a purchase.`

The subscription status will change from "Active" to "Pending", even though the subscription should remain active.

### To Reproduce

1. Go to My Account - Subscriptions
2. Select an active Subscription and click on 'change payment' button
3. Select "Paypal" from the available payment options
4. See info: `No PayPal payments saved, in order to use a saved payment you first need to create it through a purchase.`
5. See error: `The payment method can not be changed for that subscription.`
6. Check the related subscription status which is now `Pending`
7. Check admin subscription notes: `Could not process order. Status changed from Active to Pending`

### Expected Behavior

Since the subscription is still "Active" the status should remain the same and not be change to "Pending"

### Actual Behavior

Subscription status is always changed from "Active" to "Pending"

### Environment

- WordPress Version 5.8.2
- WooCommerce Version 6.0.0
- WooCommerce Subscriptions 3.1.6
- WooCommerce PayPal Payments Plugin Version 1.6.4

**Comment by InpsydeNiklas** [comment]
The "Change payment method" button shouldn't be visible on this page when there is no vaulted payment method. The reported behavior is not intended, but when the button is removed from this page when there is no vaulted payment method, then the resulting issue should be prevented at the very least.

**Comment by Gorbas** [comment]
@InpsydeNiklas how could I check that there is no vaulted payment method in order to hide the "Change Payment method" button?

It is pretty easy to remove it, but I do not know how to check that there is no vaulted payment method.

Button removal can be done using the following snippet


``    add_filter( 'wcs_view_subscription_actions', function( $actions, $subscription ) {
        if (isset($actions['change_payment_method'])) {
            unset($actions['change_payment_method']);
        } return $actions; 
    }, 100, 2);
``

**Comment by EdithAllison** [comment]
Following as I'm interested in a fix

**Comment by InpsydeNiklas** [comment]
The problematic behavior of the subscription ending up in the `Pending` status was addressed in https://github.com/woocommerce/woocommerce-paypal-payments/pull/1953 and this issue wasn't linked correctly in the system. So, using the latest plugin versions, the behavior reported in this issue should not be possible because the PayPal payment method is not visible if there is no saved payment token.

This means when an existing subscriber wants to switch e.g. their credit card subscription to PayPal, the buyer must first save the PayPal account either from the `Add payment method` endpoint or with a purchase. As long as there is no saved PayPal account, the PayPal payment method will be hidden on the `Change payment` endpoint. So there is one extra step involved in switching the subscription payment method to PayPal:

https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/9d293f79-69d1-4dcd-a962-ee80a7b474a0


However, when the buyer already has a PayPal payment method saved and wants to switch to a card (via Advanced Card Processing), then the new card can be saved directly from the `Change payment` endpoint:

https://github.com/woocommerce/woocommerce-paypal-payments/assets/70433191/9d25e8d2-1a76-4a84-a7e3-2d46d903e412


We haven't found a great solution yet to integrate the PayPal button directly on the `Change payment` endpoint, but this will be revisited at a later date. For now, if you encounter any difficulties or have questions about it, I recommend [contacting the support team directly](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) with a link to this issue for the best possible assistance. Thank you!
