### ISSUE TITLE
Improve payment token checking for subscriptions (562)

### ISSUE THREAD

**Issue by Dinamiko** [woocommerce/woocommerce-paypal-payments#525]
Currently when purchasing a subscription product, just after the payment is processed we check if the payment is saved on PayPal and if it´s not then we update the order status as failed and the subscription as cancelled. Because vaulting a paymet through the JSSDK is asynchronous it could be that when we check it it´s not there yet and therefore we handle a false negative.

We could wait for the incoming webhook and also register an event for checking if the payment is saved on PayPal after some minutes, then if it is not there fail the order as we do now.

Here is how the workflow could look like:

![PCP Issues drawio (1)](https://user-images.githubusercontent.com/456223/156731981-faa584fa-29a5-4ea4-aed4-944c37fa1195.png)

### Acceptance Criteria

- Add subscription product to the cart and go to Checkout.
- Click PayPal button and process payment.
- Immediatelly after order is placed succesfully, check that subscription status is on-hold.
- After one minute or so check subscription status is active and order status is processing.

**Comment by steffans** [comment]
Is this related to this issue https://github.com/woocommerce/woocommerce-paypal-payments/issues/410 ? Sounds like a race condition.

**Comment by InpsydeNiklas** [comment]
This issue will reduce the probability of false negatives that trigger the #410 error when it should not be the case. The error is currently thrown if no saved payment method could be detected which can have a variety of causes, including a race condition. If the payment method could actually not be saved though, the error is the intentional behavior for the moment.
