### ISSUE TITLE
"The value of a field does not conform to the expected format" error when using certain e-mail addresses

### ISSUE THREAD

**Issue by jorgeatorres** [woocommerce/woocommerce-paypal-payments#56]
During checkout, if the e-mail address contains certain characters, for instance `+` (plus sign), the following error is presented to the user:

![Screen Shot 2020-10-08 at 17 14 01](https://user-images.githubusercontent.com/184724/95510339-2245c000-098c-11eb-8499-b3d90e08a939.png)

This refers to `payer/email_address` specifically.

Not sure if the e-mail address has to be encoded a certain way or if this is an issue on PayPal's side, but e-mail addresses such as "test+user@woo.test" are both valid e-mail addresses and common practice.

**Comment by ryanhalliday** [comment]
I believe this issue is happening again with the latest version of the plugin. Tested using me+sample@pretenddomain.org

The email being sent in the AJAX request to `ppc-create-order` is formatted as `billing_email=me%2Bsample%40pretenddomain.org` but PayPal's response is like:
```json
{
	"success": false,
	"data": {
		"name": "INVALID_REQUEST",
		"message": "[INVALID_REQUEST] Request is not well-formed, syntactically incorrect, or violates schema. https:\/\/developer.paypal.com\/docs\/api\/orders\/v2\/#error-INVALID_PARAMETER_SYNTAX",
		"code": 400,
		"details": [
			{
				"field": "\/payer\/email_address",
				"value": "me sample@pretenddomain.org",
				"location": "body",
				"issue": "INVALID_PARAMETER_SYNTAX",
				"description": "The value of a field does not conform to the expected format."
			}
		]
	}
}
```

Note that the `+` is stripped out for a ` ` (space) in their response. Not sure at what step this is happening. Also the link to their docs doesn't work. This page has some real information: https://developer.paypal.com/api/rest/reference/orders/v2/errors/#link-createorder

This shows `INVALID_PARAMETER_SYNTAX The value of a field does not conform to the expected format` at the top of the cart.

**Comment by ryanhalliday** [comment]
Just found that this is being tracked in https://github.com/woocommerce/woocommerce-paypal-payments/issues/523
