### ISSUE TITLE
No PayPal order found in the current WooCommerce session.

### ISSUE THREAD

**Issue by smartwaypharma** [woocommerce/woocommerce-paypal-payments#579]
### Describe the Bug

No PayPal order found in the current WooCommerce session on checkout page

### To Reproduce

When I select paypal option for payment and hit place an order button then I am getting that error.

**Comment by InpsydeNiklas** [comment]
This error message would be the expected behavior when clicking the regular "Place order" button. It should be more difficult to trigger with the latest version 1.7.1 as the button is now hidden sooner.
If there are any open questions regarding the setup, please open a support ticket from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!
