### ISSUE TITLE
Text Change Request Vaulting Payments (938)

### ISSUE THREAD

**Issue by ingenuitor** [woocommerce/woocommerce-paypal-payments#613]
Can you kindly change this to Stored Payments vs PayPal payment, ~Best regards,

REF: [Text Change Request Vaulting Payments] https://github.com/woocommerce/woocommerce-paypal-payments/blob/d18df34e9bafd21c2a63e73a36ec37cbb1c46ec8/modules/ppcp-vaulting/src/VaultingModule.php#L55

**Comment by InpsydeNiklas** [comment]
The next step would be to add it to the translation files, but the goal is to eventually use the default endpoint provided by WooCommerce for saved payment methods instead of the custom one that is currently created when Vaulting is enabled. 
This will take a bit of time though and the string likely will be made translatable in one of the next few updates.

**Comment by ingenuitor** [comment]
> The next step would be to add it to the translation files, but the goal is to eventually use the default endpoint provided by WooCommerce for saved payment methods instead of the custom one that is currently created when Vaulting is enabled. This will take a bit of time though and the string likely will be made translatable in one of the next few updates.

Ok this sounds great, thank you for considering the idea.  Otherwise the plugin seems to be very well developed and allot of hard work was put into it's creation, no question, so thank you for all your efforts and contribution to the community.

**Comment by ingenuitor** [comment]
When will we see this live to control on our end? Thanks so much...
