### ISSUE TITLE
Paypal button is not blocked by any error from woocommerce hook "woocommerce_after_checkout_validation"

### ISSUE THREAD

**Issue by nam-truong-le** [woocommerce/woocommerce-paypal-payments#720]
### Describe the Bug

Paypal button is not blocked by any error from woocommerce hook "woocommerce_after_checkout_validation"

### To Reproduce

Add a dummy action to this hook "woocommerce_after_checkout_validation"

```php
$errors->add('validation', 'Dummy error');
```

### Expected Behavior

After click the paypal button, the error should be shown and user can't proceed.

### Actual Behavior

Paypal payment popup is shown.

### Environment

 - WordPress Version
 - WooCommerce Version
 - Plugin Version
 - Browser [e.g. Chrome, Safari] and Version
 - Any other plugins installed

### Additional Details

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by InpsydeNiklas** [comment]
Hi @nam-truong-le!
Thanks for reporting. However, this is expected behavior as the regular WooCommerce form field validation occurs after the PayPal order was created as outlined in #513. 
So the actual error will occur after the popup window is closed.
The last plugin version to validate immediately upon button click is version 1.6.1 but this had to be changed due to compatibility issues when third-party plugins are hooking into the validation, similar to your example.
Update 1.9.0 only added a basic field validation that checks whether or not required fields are populated and the regular validation still happens afterward. A better long-term solution that does not sacrifice compatibility is still under investigation.
