### ISSUE TITLE
Initial Subscription payment issue: Could not process order because it was not possible to save the payment on PayPal.

### ISSUE THREAD

**Issue by adamkentdev** [woocommerce/woocommerce-paypal-payments#727]
### Describe the Bug

When placing a new order for a WC subscription product, the order goes through but order fails with following note: _'Could not process order because it was not possible to save the payment on PayPal. Order status changed from On hold to Failed.'_

### To Reproduce

- Add Woocommerce subscription product to cart.
- Proceed to checkout
- Proceed with payment using paypal modal using sandbox mode with customer email in paypal modal such as: sb-vdxpa144545435@personal.example.com

### Expected Behavior

Order status should be set to processing, subscription should be setup, and test payment should be processed successfully.

### Actual Behavior

- Order completes successfully
- Order notes shows in cron order:
-- PayPal transaction ID: xxx
-- Awaiting payment. Order status changed from Pending payment to On hold.
-- Could not process order because it was not possible to save the payment on PayPal. Order status changed from On hold to Failed.
- Order status is set to: failed

### Environment

 - WordPress Version 5.9.3
 - WooCommerce Version 6.4.1
 - Plugin Version 1.9.0

### Additional Details

- Relevant errors in error logs:
-- ERROR Webhook verification failed.
-- ERROR Payment for subscription parent order #373982 was not saved on PayPal.
- When simulating webhook in payment gateway admin page it completes successfully: ✔️ The webhook was received successfully.

**Comment by InpsydeNiklas** [comment]
Your "Expected Behavior" assumes a positive outcome which is not the case here. The order failure is the intended behavior when saving the payment method failed: https://woocommerce.com/document/woocommerce-paypal-payments/#subscription-flow
https://github.com/woocommerce/woocommerce-paypal-payments/pull/729 implements a feature to choose between failing the order and capturing the payment regardless. Without a saved payment method, automatic renewals will not be possible though.
For any questions about the subscription flow, please reach out to the support from here: https://paypal.inpsyde.com/docs/request-support/
Thanks!

**Comment by adamkentdev** [comment]
This is whilst in sandbox mode - I'm trying to simulate a successful payment with a positive outcome. Why isn't the payment method being saved?

**Comment by Misha327** [comment]
Getting the same behavior for unknown reasons, has worked a couple of times before - sandbox mode too.
