### ISSUE TITLE
Error "Could not retrieve order" on mobile & tablet

### ISSUE THREAD

**Issue by Instantitan** [woocommerce/woocommerce-paypal-payments#819]
### Describe the Bug

1. "Could not retrieve order" when click "Place Order" button in the Checkout page on mobile & tablet.
2. The Paypal smart button is not showing in the Checkout page on mobile and tablet, but showing on PC.

### Environment

 - WordPress Version - 6.0.2
 - WooCommerce Version - 6.8.2
 - WooCommerce PayPal Payments - 1.9.3
 - Any other plugins installed

### Additional Details

Added filter (mentioned on https://woocommerce.com/document/woocommerce-paypal-payments/#faq-paypal-smart-buttons-not-loading) but still not working.

**Comment by InpsydeNiklas** [comment]
Hi @Instantitan, This error means the smart buttons are not loading on your mobile browsers. The "Place order" button is meant to be replaced and will create failed order when clicked.
The filter from the docs won't help in that case because it's a different problem that relates mostly to old/unsupported browsers.
Please contact the plugin support with more details like a system report and which browsers you are using as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
