### ISSUE TITLE
It's showing on product to buy without collecting data for shipping address, 

### ISSUE THREAD

**Issue by sameerssayyad** [woocommerce/woocommerce-paypal-payments#826]
It's showing on product to buy without collecting customer data for shipping address, 
![bugg](https://user-images.githubusercontent.com/112498955/188632320-32217611-3f74-4f02-be6d-c12dc3c067fe.JPG)
 after clicking on paypal button to buy, this redirect to make payment
![bugg2](https://user-images.githubusercontent.com/112498955/188632797-ce540580-18d9-4b31-94d4-2ec45a2c4756.JPG)

**Comment by InpsydeNiklas** [comment]
Hi @sameerssayyad,
I don't see what's the issue here as this is expected behavior: https://woocommerce.com/document/woocommerce-paypal-payments/#paypal-on-non-checkout-pages

For any questions, please contact the support directly as described here: https://woocommerce.com/document/woocommerce-paypal-payments/#get-help
Thanks!
