### ISSUE TITLE
Problem with payment and order creation

### ISSUE THREAD

**Issue by Berciu** [woocommerce/woocommerce-paypal-payments#834]
When the buyer orders a product in the store and selects, for example, the payment blik (Poland), a new PayPal window opens. Then, when I close the previous window with the shop and the current payment window on the PayPal website, but copy this PayPal payment link, open it again in a new window and pay, it takes money from my bank account and does not receive it on my paypal account and the store is not created new order

**Comment by Sirvijver** [comment]
Hello @Berciu 

Alternative payment methods such as iDEAL are push payments, so it will debit the customer's bank account as soon as they have authorized/approved the payment.
If the merchant doesn't capture this payment, it will be refunded automatically after 3 hours. Depending on the bank, the buyer should see the refund in a few days, as SEPA transactions take a day to process.
When no order has been created in WooCommerce, then PayPal Payments will also not have captured the payment and so no funds will be added to the merchant account.
The only scenarios in which I could see this happen are either when the webhooks are not registered, or the buyer did not correctly complete the checkout process as described in this issue: https://github.com/woocommerce/woocommerce-paypal-payments/issues/513

This issue is probably not occurring any longer, we had a big improvement on this matter in the previous (not last) release.

If you need additional support on this matter, please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance. We do not provide support via GitHub, we only work on development activities here. This thread will be closed.

Kind regards, 
Joost
