### ISSUE TITLE
message "Paypal login failed. Could not create token.

### ISSUE THREAD

**Issue by capitancapo** [woocommerce/woocommerce-paypal-payments#920]
### To Reproduce

1. Go to '…'
2. Click on '…'
3. Scroll down to …'

### Screenshots
<img width="1148" alt="Bildschirmfoto 2022-10-19 um 15 06 43" src="https://user-images.githubusercontent.com/70807174/196701423-defcc5e5-ac6d-4bb4-b6eb-03dae269a6f3.png">

### Environment

 - WordPress Version 6.0.3
 - WooCommerce Version 7.0.0
 - Plugin Version 1.9.4
 - Browser [e.g. Chrome, Safari] and Version Safari 105.0.3 
 - Any other plugins installed

### Additional Details

Attached is a screenshot. It appears randomly and disappears again after a few minutes and then reappears.

<details><summary>System status</summary>

  ```
  <!--If applicable, paste the system status here. Please ensure you redact or remove any identifying information. -->
  ```

</details>

**Comment by Sirvijver** [comment]
Hello @capitancapo 

the GitHub platform is not used by us for providing plugin support, only plugin development. This is also the reason why you did not get any response from us so far. Please [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

Please provide more details about the issue, so that we can help you (in case you still need our support). 

Kind regards, 
Joost
