### ISSUE TITLE
Help with WooCommerce PayPal Version 1.9.4

### ISSUE THREAD

**Issue by Will981** [woocommerce/woocommerce-paypal-payments#927]
Hi, 
I have an issue with Failed orders. Happens often and radomly. An error msg appears as follows:
 
. [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-COMPLIANCE_VIOLATION PayPalGateway.php:500 [UNPROCESSABLE_ENTITY] The requested action could not be performed, semantically incorrect, or failed business validation. https://developer.paypal.com/docs/api/orders/v2/#error-COMPLIANCE_VIOLATION OrderEndpoint.php:393 Order status changed from Pending payment to Failed.

Can any one help please. 

Many thanks 

Will

**Comment by InpsydeNiklas** [comment]
This error usually relates to the PayPal merchant account and must be clarified with the [PayPal Merchant Support](https://www.paypal.com/smarthelp/contact-us/). We have seen it in the past for buyers from certain regions, but only PayPal can tell you the specific reason, as this is not an issue with the integration.
The best you could do is enable logging so that the PayPal support can check your log files and look up the corresponding debug ID.

But if any questions come up, please consider [reaching out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly to receive more guidance. Thanks!
