### ISSUE TITLE
WooCommerce PayPal Payments - PayPal Card Processing - Data to Paypal is missing or incorrect

### ISSUE THREAD

**Issue by vorticy** [woocommerce/woocommerce-paypal-payments#954]
When a customer processes an order using the credit card option (PayPal Card Processing) in WooCommerce PayPal Payments plugin (Version 1.9.4 by WooCommerce), the data that is sent to Paypal is missing or incorrect.  

Problems I am seeing:
1) When viewing the Paypal activity, in some cases, there is nothing in the name field and therefore, there is no link to click on to open the order and view the information.  
2) Sometimes, instead of a name in the activity, there is an email such as 22V83841CL2758431@dcc2.paypal.com.   
3) In case of problem 2, the customer information is missing from the order.  The order says "Payment Type: Direct Card Payments"
Card and the Processor Response Details
Card Type: MCARD
Address Verification Service (AVS): Yes
Card Security Code(CSC): Match

However, when a customer uses the "Mobile Payments" of that same plugin which I think is "PayPal Checkout" then the data seems to be correct in Paypal.  So I'm not sure why one payment feature of the plugin would work fine while the other one does not.  When using a different Paypal plugin with REST credit card payments (from Angel Eye) the information is correct in Paypal.  So it would seem there is an error in the code with WooCommerce Paypal Payments plugin and the Paypal Card Processing feature.

**Comment by Sirvijver** [comment]
Hello @vorticy,

thank you for reaching out. We want to help you, but do not support our plugin via GitHub and would like to ask you to [reach out to the support team](https://woocommerce.com/document/woocommerce-paypal-payments/#get-help) directly for more guidance.

The issue you are facing could have many causes. The 2 most common ones are:
1) There is a plugin or setting that causes the order overview to differ between WooCommerce and PayPal. This causes the plugin to drop and not send the specifics of the order to PayPal, and only send the final amount. You could try to find out what is causing this issue by doing test purchases while disabling other plugins (and possibly also replacing the theme). I would advise doing this on a [staging site](https://wordpress.org/plugins/wp-staging/) and making a backup of your site before you attempt this.
2) There was an issue with our Advanced Card Processing payment option, that was caused by a change on PayPal side. This was resolved last week and should not occur any longer. When a payment was done via ACDC, the order address would show "We have no postal address on file". This has been corrected by PayPal!

If you require additional support, please open a new ticket/thread via the instructions given above.

Kind regards, 
Joost
